//! GitHub Copilot model catalog ported from Pi's `packages/ai/src/providers/github-copilot.models.ts`.

/// Pricing metadata for a GitHub Copilot model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GithubCopilotModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// Compatibility metadata for a GitHub Copilot model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GithubCopilotModelCompat {
    /// Whether the model supports the OpenAI store option.
    pub supports_store: Option<bool>,
    /// Whether the model supports the developer role.
    pub supports_developer_role: Option<bool>,
    /// Whether the model supports the reasoning-effort parameter.
    pub supports_reasoning_effort: Option<bool>,
    /// Whether the model supports eager tool input streaming.
    pub supports_eager_tool_input_streaming: Option<bool>,
    /// Whether Pi forces adaptive thinking for the model.
    pub force_adaptive_thinking: Option<bool>,
    /// Whether the model supports the temperature parameter.
    pub supports_temperature: Option<bool>,
}

/// Request headers from Pi's GitHub Copilot model catalog.
pub type GithubCopilotHeaders = &'static [(&'static str, &'static str)];

/// A `thinkingLevelMap` entry from Pi's GitHub Copilot model catalog.
pub type GithubCopilotThinkingLevelMap = &'static [(&'static str, Option<&'static str>)];

/// One GitHub Copilot model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GithubCopilotModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// Request headers.
    pub headers: GithubCopilotHeaders,
    /// Optional compatibility flags.
    pub compat: Option<GithubCopilotModelCompat>,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Optional Pi thinking-level mapping.
    pub thinking_level_map: Option<GithubCopilotThinkingLevelMap>,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: GithubCopilotModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];
const GITHUB_COPILOT_HEADERS: GithubCopilotHeaders = &[
    ("User-Agent", "GitHubCopilotChat/0.35.0"),
    ("Editor-Version", "vscode/1.107.0"),
    ("Editor-Plugin-Version", "copilot-chat/0.35.0"),
    ("Copilot-Integration-Id", "vscode-chat"),
];

const GITHUB_COPILOT_COMPAT_1: GithubCopilotModelCompat = GithubCopilotModelCompat {
    supports_store: Some(false),
    supports_developer_role: Some(false),
    supports_reasoning_effort: Some(false),
    supports_eager_tool_input_streaming: None,
    force_adaptive_thinking: None,
    supports_temperature: None,
};
const GITHUB_COPILOT_COMPAT_2: GithubCopilotModelCompat = GithubCopilotModelCompat {
    supports_store: None,
    supports_developer_role: None,
    supports_reasoning_effort: None,
    supports_eager_tool_input_streaming: Some(false),
    force_adaptive_thinking: None,
    supports_temperature: None,
};
const GITHUB_COPILOT_COMPAT_3: GithubCopilotModelCompat = GithubCopilotModelCompat {
    supports_store: None,
    supports_developer_role: None,
    supports_reasoning_effort: None,
    supports_eager_tool_input_streaming: None,
    force_adaptive_thinking: Some(true),
    supports_temperature: None,
};
const GITHUB_COPILOT_COMPAT_4: GithubCopilotModelCompat = GithubCopilotModelCompat {
    supports_store: None,
    supports_developer_role: None,
    supports_reasoning_effort: None,
    supports_eager_tool_input_streaming: None,
    force_adaptive_thinking: Some(true),
    supports_temperature: Some(false),
};

const THINKING_1: GithubCopilotThinkingLevelMap = &[("xhigh", Some("max"))];
const THINKING_2: GithubCopilotThinkingLevelMap =
    &[("xhigh", Some("xhigh")), ("minimal", Some("low"))];
const THINKING_3: GithubCopilotThinkingLevelMap =
    &[("minimal", Some("low")), ("xhigh", Some("max"))];
const THINKING_4: GithubCopilotThinkingLevelMap = &[("off", None), ("minimal", Some("low"))];
const THINKING_5: GithubCopilotThinkingLevelMap = &[
    ("off", None),
    ("minimal", Some("low")),
    ("xhigh", Some("xhigh")),
];

/// GitHub Copilot models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const GITHUB_COPILOT_MODELS: &[GithubCopilotModel] = &[
    GithubCopilotModel {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 10.0,
            output: 50.0,
            cache_read: 1.0,
            cache_write: 12.5,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "claude-haiku-4.5",
        name: "Claude Haiku 4.5 (latest)",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_2),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.0,
            output: 5.0,
            cache_read: 0.1,
            cache_write: 1.25,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "claude-opus-4.5",
        name: "Claude Opus 4.5 (latest)",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "claude-opus-4.6",
        name: "Claude Opus 4.6",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_3),
        reasoning: true,
        thinking_level_map: Some(THINKING_1),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 1000000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "claude-opus-4.7",
        name: "Claude Opus 4.7",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_4),
        reasoning: true,
        thinking_level_map: Some(THINKING_2),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "claude-opus-4.8",
        name: "Claude Opus 4.8",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_4),
        reasoning: true,
        thinking_level_map: Some(THINKING_2),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "claude-sonnet-4",
        name: "Claude Sonnet 4 (latest)",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_2),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 216000,
        max_tokens: 16000,
    },
    GithubCopilotModel {
        id: "claude-sonnet-4.5",
        name: "Claude Sonnet 4.5 (latest)",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_2),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_3),
        reasoning: true,
        thinking_level_map: Some(THINKING_3),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 1000000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        api: "anthropic-messages",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_3),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 2.0,
            output: 10.0,
            cache_read: 0.2,
            cache_write: 2.5,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.25,
            output: 10.0,
            cache_read: 0.125,
            cache_write: 0.0,
        },
        context_window: 128000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 0.5,
            output: 3.0,
            cache_read: 0.05,
            cache_write: 0.0,
        },
        context_window: 128000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 2.0,
            output: 12.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.5,
            output: 9.0,
            cache_read: 0.15,
            cache_write: 0.0,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "gpt-4.1",
        name: "GPT-4.1",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: false,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 2.0,
            output: 8.0,
            cache_read: 0.5,
            cache_write: 0.0,
        },
        context_window: 128000,
        max_tokens: 16384,
    },
    GithubCopilotModel {
        id: "gpt-5-mini",
        name: "GPT-5 Mini",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_4),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 0.25,
            output: 2.0,
            cache_read: 0.025,
            cache_write: 0.0,
        },
        context_window: 264000,
        max_tokens: 64000,
    },
    GithubCopilotModel {
        id: "gpt-5.2",
        name: "GPT-5.2",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.4",
        name: "GPT-5.4",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 2.5,
            output: 15.0,
            cache_read: 0.25,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 0.75,
            output: 4.5,
            cache_read: 0.075,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 0.2,
            output: 1.25,
            cache_read: 0.02,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "gpt-5.5",
        name: "GPT-5.5",
        api: "openai-responses",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: None,
        reasoning: true,
        thinking_level_map: Some(THINKING_5),
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 5.0,
            output: 30.0,
            cache_read: 0.5,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    GithubCopilotModel {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: GithubCopilotModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.19,
            cache_write: 0.0,
        },
        context_window: 256000,
        max_tokens: 32000,
    },
    GithubCopilotModel {
        id: "mai-code-1-flash-picker",
        name: "MAI-Code-1-Flash",
        api: "openai-completions",
        provider: "github-copilot",
        base_url: "https://api.individual.githubcopilot.com",
        headers: GITHUB_COPILOT_HEADERS,
        compat: Some(GITHUB_COPILOT_COMPAT_1),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: GithubCopilotModelCost {
            input: 0.75,
            output: 4.5,
            cache_read: 0.075,
            cache_write: 0.0,
        },
        context_window: 256000,
        max_tokens: 128000,
    },
];
