//! Hugging Face model catalog ported from Pi's `packages/ai/src/providers/huggingface.models.ts`.

/// Pricing metadata for a Hugging Face model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HuggingFaceModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// Compatibility metadata for a Hugging Face model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HuggingFaceModelCompat {
    /// Whether the model supports the developer role.
    pub supports_developer_role: bool,
}

/// One Hugging Face model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HuggingFaceModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// Compatibility flags.
    pub compat: HuggingFaceModelCompat,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: HuggingFaceModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];
const HUGGINGFACE_COMPAT: HuggingFaceModelCompat = HuggingFaceModelCompat {
    supports_developer_role: false,
};

/// Hugging Face models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const HUGGINGFACE_MODELS: &[HuggingFaceModel] = &[
    HuggingFaceModel {
        id: "MiniMaxAI/MiniMax-M2",
        name: "MiniMax-M2",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 128_000,
    },
    HuggingFaceModel {
        id: "MiniMaxAI/MiniMax-M2.1",
        name: "MiniMax-M2.1",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax-M2.5",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.03,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "MiniMaxAI/MiniMax-M2.7",
        name: "MiniMax-M2.7",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "MiniMaxAI/MiniMax-M3",
        name: "MiniMax-M3",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 524_288,
        max_tokens: 128_000,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-235B-A22B",
        name: "Qwen3 235B-A22B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.2,
            output: 0.8,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 40_960,
        max_tokens: 16_384,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen3-235B-A22B-Thinking-2507",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 3.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-32B",
        name: "Qwen3 32B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.29,
            output: 0.59,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 16_384,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        name: "Qwen3-Coder 30B-A3B Instruct",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.07,
            output: 0.26,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen3-Coder-480B-A35B-Instruct",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 2.0,
            output: 2.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 66_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-Coder-Next",
        name: "Qwen3-Coder-Next",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.2,
            output: 1.5,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen3-Next-80B-A3B-Instruct",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.25,
            output: 1.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 66_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3-Next-80B-A3B-Thinking",
        name: "Qwen3-Next-80B-A3B-Thinking",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 2.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.5-122B-A10B",
        name: "Qwen3.5 122B-A10B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.4,
            output: 3.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.5-27B",
        name: "Qwen3.5 27B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.3,
            output: 2.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.5-35B-A3B",
        name: "Qwen3.5 35B-A3B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.25,
            output: 2.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.5-397B-A17B",
        name: "Qwen3.5-397B-A17B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 3.6,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 32_768,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.5-9B",
        name: "Qwen3.5 9B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.17,
            output: 0.25,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.6-27B",
        name: "Qwen3.6 27B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.47,
            output: 3.19,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "Qwen/Qwen3.6-35B-A3B",
        name: "Qwen3.6 35B-A3B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.15,
            output: 0.95,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "XiaomiMiMo/MiMo-V2-Flash",
        name: "MiMo-V2-Flash",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.1,
            output: 0.3,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 4_096,
    },
    HuggingFaceModel {
        id: "XiaomiMiMo/MiMo-V2.5-Pro",
        name: "MiMo-V2.5-Pro",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.0,
            output: 3.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek-R1",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.7,
            output: 2.5,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 64_000,
        max_tokens: 32_768,
    },
    HuggingFaceModel {
        id: "deepseek-ai/DeepSeek-R1-0528",
        name: "DeepSeek-R1-0528",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 3.0,
            output: 5.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 163_840,
        max_tokens: 163_840,
    },
    HuggingFaceModel {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek-V3.2",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.28,
            output: 0.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 163_840,
        max_tokens: 65_536,
    },
    HuggingFaceModel {
        id: "deepseek-ai/DeepSeek-V4-Flash",
        name: "DeepSeek V4 Flash",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.14,
            output: 0.28,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 384_000,
    },
    HuggingFaceModel {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        name: "DeepSeek V4 Pro",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.435,
            output: 0.87,
            cache_read: 0.003625,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 393_216,
    },
    HuggingFaceModel {
        id: "google/gemma-4-26B-A4B-it",
        name: "Gemma 4 26B A4B IT",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.13,
            output: 0.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 32_768,
    },
    HuggingFaceModel {
        id: "google/gemma-4-31B-it",
        name: "Gemma 4 31B IT",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.14,
            output: 0.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 32_768,
    },
    HuggingFaceModel {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama-3.3-70B-Instruct",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.59,
            output: 0.79,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 4_096,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2-Instruct",
        name: "Kimi-K2-Instruct",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.0,
            output: 3.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 16_384,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi-K2-Instruct-0905",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: false,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.0,
            output: 3.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 16_384,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2-Thinking",
        name: "Kimi-K2-Thinking",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 2.5,
            cache_read: 0.15,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi-K2.5",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 3.0,
            cache_read: 0.1,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi-K2.6",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.16,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    HuggingFaceModel {
        id: "moonshotai/Kimi-K2.7-Code",
        name: "Kimi K2.7 Code",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    HuggingFaceModel {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.25,
            output: 0.69,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 32_768,
    },
    HuggingFaceModel {
        id: "stepfun-ai/Step-3.5-Flash",
        name: "Step 3.5 Flash",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.1,
            output: 0.3,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 256_000,
    },
    HuggingFaceModel {
        id: "stepfun-ai/Step-3.7-Flash",
        name: "Step 3.7 Flash",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.2,
            output: 1.15,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 256_000,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.5",
        name: "GLM-4.5",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 2.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 98_304,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.5-Air",
        name: "GLM-4.5-Air",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.13,
            output: 0.85,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 98_304,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.5V",
        name: "GLM-4.5V",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 1.8,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 65_536,
        max_tokens: 16_384,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.6",
        name: "GLM-4.6",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.55,
            output: 2.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.7",
        name: "GLM-4.7",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.6,
            output: 2.2,
            cache_read: 0.11,
            cache_write: 0.0,
        },
        context_window: 204_800,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-4.7-Flash",
        name: "GLM-4.7-Flash",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 200_000,
        max_tokens: 128_000,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-5",
        name: "GLM-5",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.0,
            output: 3.2,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 202_752,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-5.1",
        name: "GLM-5.1",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.0,
            output: 3.2,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 202_752,
        max_tokens: 131_072,
    },
    HuggingFaceModel {
        id: "zai-org/GLM-5.2",
        name: "GLM-5.2",
        api: "openai-completions",
        provider: "huggingface",
        base_url: "https://router.huggingface.co/v1",
        compat: HUGGINGFACE_COMPAT,
        reasoning: true,
        input: TEXT,
        cost: HuggingFaceModelCost {
            input: 1.4,
            output: 4.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
];
