//! Mistral model catalog ported from Pi's `packages/ai/src/providers/mistral.models.ts`.

/// Pricing metadata for a Mistral model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MistralModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// One Mistral model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MistralModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: MistralModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];

/// Mistral models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const MISTRAL_MODELS: &[MistralModel] = &[
    MistralModel {
        id: "codestral-latest",
        name: "Codestral (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.3,
            output: 0.9,
            cache_read: 0.03,
            cache_write: 0.0,
        },
        context_window: 256_000,
        max_tokens: 4_096,
    },
    MistralModel {
        id: "devstral-2512",
        name: "Devstral 2",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "devstral-latest",
        name: "Devstral 2",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "devstral-medium-2507",
        name: "Devstral Medium",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "devstral-medium-latest",
        name: "Devstral 2 (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "devstral-small-2505",
        name: "Devstral Small 2505",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.1,
            output: 0.3,
            cache_read: 0.01,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "devstral-small-2507",
        name: "Devstral Small",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.1,
            output: 0.3,
            cache_read: 0.01,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "labs-devstral-small-2512",
        name: "Devstral Small 2",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 256_000,
        max_tokens: 256_000,
    },
    MistralModel {
        id: "magistral-medium-latest",
        name: "Magistral Medium (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT,
        cost: MistralModelCost {
            input: 2.0,
            output: 5.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 16_384,
    },
    MistralModel {
        id: "magistral-small",
        name: "Magistral Small",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.5,
            output: 1.5,
            cache_read: 0.05,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "ministral-3b-latest",
        name: "Ministral 3B (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.04,
            output: 0.04,
            cache_read: 0.004,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "ministral-8b-latest",
        name: "Ministral 8B (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.1,
            output: 0.1,
            cache_read: 0.01,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "mistral-large-2411",
        name: "Mistral Large 2.1",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 2.0,
            output: 6.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 16_384,
    },
    MistralModel {
        id: "mistral-large-2512",
        name: "Mistral Large 3",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.5,
            output: 1.5,
            cache_read: 0.05,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-large-latest",
        name: "Mistral Large (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.5,
            output: 1.5,
            cache_read: 0.05,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-medium-2505",
        name: "Mistral Medium 3",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 131_072,
    },
    MistralModel {
        id: "mistral-medium-2508",
        name: "Mistral Medium 3.1",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-medium-2604",
        name: "Mistral Medium 3.5",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 1.5,
            output: 7.5,
            cache_read: 0.15,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-medium-3.5",
        name: "Mistral Medium 3.5",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 1.5,
            output: 7.5,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-medium-latest",
        name: "Mistral Medium (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.4,
            output: 2.0,
            cache_read: 0.04,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    MistralModel {
        id: "mistral-nemo",
        name: "Mistral Nemo",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.15,
            output: 0.15,
            cache_read: 0.015,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "mistral-small-2506",
        name: "Mistral Small 3.2",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.1,
            output: 0.3,
            cache_read: 0.01,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 16_384,
    },
    MistralModel {
        id: "mistral-small-2603",
        name: "Mistral Small 4",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.15,
            output: 0.6,
            cache_read: 0.015,
            cache_write: 0.0,
        },
        context_window: 256_000,
        max_tokens: 256_000,
    },
    MistralModel {
        id: "mistral-small-latest",
        name: "Mistral Small (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: true,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.15,
            output: 0.6,
            cache_read: 0.015,
            cache_write: 0.0,
        },
        context_window: 256_000,
        max_tokens: 256_000,
    },
    MistralModel {
        id: "open-mistral-7b",
        name: "Mistral 7B",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.25,
            output: 0.25,
            cache_read: 0.025,
            cache_write: 0.0,
        },
        context_window: 8_000,
        max_tokens: 8_000,
    },
    MistralModel {
        id: "open-mistral-nemo",
        name: "Open Mistral Nemo",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.15,
            output: 0.15,
            cache_read: 0.015,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "open-mixtral-8x22b",
        name: "Mixtral 8x22B",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 2.0,
            output: 6.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 64_000,
        max_tokens: 64_000,
    },
    MistralModel {
        id: "open-mixtral-8x7b",
        name: "Mixtral 8x7B",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT,
        cost: MistralModelCost {
            input: 0.7,
            output: 0.7,
            cache_read: 0.07,
            cache_write: 0.0,
        },
        context_window: 32_000,
        max_tokens: 32_000,
    },
    MistralModel {
        id: "pixtral-12b",
        name: "Pixtral 12B",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 0.15,
            output: 0.15,
            cache_read: 0.015,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
    MistralModel {
        id: "pixtral-large-latest",
        name: "Pixtral Large (latest)",
        api: "mistral-conversations",
        provider: "mistral",
        base_url: "https://api.mistral.ai",
        reasoning: false,
        input: TEXT_IMAGE,
        cost: MistralModelCost {
            input: 2.0,
            output: 6.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 128_000,
        max_tokens: 128_000,
    },
];
