//! OpenCode model catalog ported from Pi's `packages/ai/src/providers/opencode.models.ts`.

/// Pricing metadata for an OpenCode model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct OpenCodeModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// Compatibility metadata for an OpenCode model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpenCodeModelCompat {
    /// Whether the model supports the OpenAI store option.
    pub supports_store: Option<bool>,
    /// Whether the model supports the developer role.
    pub supports_developer_role: Option<bool>,
    /// OpenAI-compatible max-token field override.
    pub max_tokens_field: Option<&'static str>,
    /// Whether Pi forces adaptive thinking for the model.
    pub force_adaptive_thinking: Option<bool>,
    /// Whether the model accepts the temperature request field.
    pub supports_temperature: Option<bool>,
    /// Whether the model supports long prompt cache retention.
    pub supports_long_cache_retention: Option<bool>,
    /// Whether replayed assistant messages must include reasoning content.
    pub requires_reasoning_content_on_assistant_messages: Option<bool>,
    /// Whether the model supports OpenAI reasoning effort.
    pub supports_reasoning_effort: Option<bool>,
    /// Pi thinking payload format identifier.
    pub thinking_format: Option<&'static str>,
}

/// A `thinkingLevelMap` entry from Pi's OpenCode model catalog.
pub type OpenCodeThinkingLevelMap = &'static [(&'static str, Option<&'static str>)];

/// One OpenCode model entry from Pi's model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct OpenCodeModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// Optional compatibility flags.
    pub compat: Option<OpenCodeModelCompat>,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Optional Pi thinking-level mapping.
    pub thinking_level_map: Option<OpenCodeThinkingLevelMap>,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: OpenCodeModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];

/// OpenCode models keyed by `id`, preserving Pi's catalog order and metadata.
pub const OPENCODE_MODELS: &[OpenCodeModel] = &[
    OpenCodeModel {
        id: "big-pickle",
        name: "Big Pickle",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    OpenCodeModel {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 10.0,
            output: 50.0,
            cache_read: 1.0,
            cache_write: 12.5,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.0,
            output: 5.0,
            cache_read: 0.1,
            cache_write: 1.25,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "claude-opus-4-1",
        name: "Claude Opus 4.1",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 15.0,
            output: 75.0,
            cache_read: 1.5,
            cache_write: 18.75,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    OpenCodeModel {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[("xhigh", Some("max"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: Some(false),
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: Some(false),
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 0.5,
            cache_write: 6.25,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "claude-sonnet-4",
        name: "Claude Sonnet 4",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 200000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.3,
            cache_write: 3.75,
        },
        context_window: 1000000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: Some(OpenCodeModelCompat {
            supports_store: None,
            supports_developer_role: None,
            max_tokens_field: None,
            force_adaptive_thinking: Some(true),
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 2.0,
            output: 10.0,
            cache_read: 0.2,
            cache_write: 2.5,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: Some(false),
            requires_reasoning_content_on_assistant_messages: Some(true),
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[
            ("minimal", None),
            ("low", None),
            ("medium", None),
            ("high", Some("high")),
            ("xhigh", Some("max")),
        ]),
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.14,
            output: 0.28,
            cache_read: 0.028,
            cache_write: 0.0,
        },
        context_window: 1000000,
        max_tokens: 384000,
    },
    OpenCodeModel {
        id: "deepseek-v4-flash-free",
        name: "DeepSeek V4 Flash Free",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: Some(true),
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[
            ("minimal", None),
            ("low", None),
            ("medium", None),
            ("high", Some("high")),
            ("xhigh", Some("max")),
        ]),
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 200000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: Some(false),
            requires_reasoning_content_on_assistant_messages: Some(true),
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[
            ("minimal", None),
            ("low", None),
            ("medium", None),
            ("high", Some("high")),
            ("xhigh", Some("max")),
        ]),
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 1.74,
            output: 3.84,
            cache_read: 0.145,
            cache_write: 0.0,
        },
        context_window: 1000000,
        max_tokens: 384000,
    },
    OpenCodeModel {
        id: "gemini-3-flash",
        name: "Gemini 3 Flash",
        api: "google-generative-ai",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.5,
            output: 3.0,
            cache_read: 0.05,
            cache_write: 0.0,
        },
        context_window: 1048576,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro Preview",
        api: "google-generative-ai",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[
            ("off", None),
            ("minimal", None),
            ("low", Some("LOW")),
            ("medium", None),
            ("high", Some("HIGH")),
        ]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 2.0,
            output: 12.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 1048576,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        api: "google-generative-ai",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.5,
            output: 9.0,
            cache_read: 0.15,
            cache_write: 0.0,
        },
        context_window: 1048576,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "glm-5",
        name: "GLM-5",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 1.0,
            output: 3.2,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 204800,
        max_tokens: 131072,
    },
    OpenCodeModel {
        id: "glm-5.1",
        name: "GLM-5.1",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 1.4,
            output: 4.4,
            cache_read: 0.26,
            cache_write: 0.0,
        },
        context_window: 204800,
        max_tokens: 131072,
    },
    OpenCodeModel {
        id: "glm-5.2",
        name: "GLM-5.2",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 1.4,
            output: 4.4,
            cache_read: 0.26,
            cache_write: 0.0,
        },
        context_window: 1000000,
        max_tokens: 131072,
    },
    OpenCodeModel {
        id: "gpt-5",
        name: "GPT-5",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.07,
            output: 8.5,
            cache_read: 0.107,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5-codex",
        name: "GPT-5 Codex",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.07,
            output: 8.5,
            cache_read: 0.107,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.05,
            output: 0.4,
            cache_read: 0.005,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.1",
        name: "GPT-5.1",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.07,
            output: 8.5,
            cache_read: 0.107,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.07,
            output: 8.5,
            cache_read: 0.107,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.25,
            output: 10.0,
            cache_read: 0.125,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None)]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.25,
            output: 2.0,
            cache_read: 0.025,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.2",
        name: "GPT-5.2",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.75,
            output: 14.0,
            cache_read: 0.175,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.4",
        name: "GPT-5.4",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 2.5,
            output: 15.0,
            cache_read: 0.25,
            cache_write: 0.0,
        },
        context_window: 272000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.75,
            output: 4.5,
            cache_read: 0.075,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 Nano",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.2,
            output: 1.25,
            cache_read: 0.02,
            cache_write: 0.0,
        },
        context_window: 400000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 30.0,
            output: 180.0,
            cache_read: 30.0,
            cache_write: 0.0,
        },
        context_window: 1050000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.5",
        name: "GPT-5.5",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[("off", None), ("xhigh", Some("xhigh"))]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 5.0,
            output: 30.0,
            cache_read: 0.5,
            cache_write: 0.0,
        },
        context_window: 1050000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        api: "openai-responses",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: None,
        reasoning: true,
        thinking_level_map: Some(&[
            ("off", None),
            ("xhigh", Some("xhigh")),
            ("minimal", None),
            ("low", None),
        ]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 30.0,
            output: 180.0,
            cache_read: 30.0,
            cache_write: 0.0,
        },
        context_window: 1050000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "grok-build-0.1",
        name: "Grok Build 0.1",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: Some(false),
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: Some(&[
            ("off", None),
            ("minimal", None),
            ("low", None),
            ("medium", None),
        ]),
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 1.0,
            output: 2.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 256000,
        max_tokens: 256000,
    },
    OpenCodeModel {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: Some(false),
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.6,
            output: 3.0,
            cache_read: 0.08,
            cache_write: 0.0,
        },
        context_window: 262144,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: Some(false),
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: Some(false),
            thinking_format: Some("deepseek"),
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.16,
            cache_write: 0.0,
        },
        context_window: 262144,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.19,
            cache_write: 0.0,
        },
        context_window: 262144,
        max_tokens: 262144,
    },
    OpenCodeModel {
        id: "mimo-v2.5-free",
        name: "MiMo V2.5 Free",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 200000,
        max_tokens: 32000,
    },
    OpenCodeModel {
        id: "minimax-m2.5",
        name: "MiniMax-M2.5",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 204800,
        max_tokens: 131072,
    },
    OpenCodeModel {
        id: "minimax-m2.7",
        name: "MiniMax-M2.7",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: Some(false),
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 204800,
        max_tokens: 131072,
    },
    OpenCodeModel {
        id: "minimax-m3",
        name: "MiniMax-M3",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 512000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "nemotron-3-ultra-free",
        name: "Nemotron 3 Ultra Free",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 1000000,
        max_tokens: 128000,
    },
    OpenCodeModel {
        id: "north-mini-code-free",
        name: "North Mini Code Free",
        api: "openai-completions",
        provider: "opencode",
        base_url: "https://opencode.ai/zen/v1",
        compat: Some(OpenCodeModelCompat {
            supports_store: Some(false),
            supports_developer_role: Some(false),
            max_tokens_field: Some("max_tokens"),
            force_adaptive_thinking: None,
            supports_temperature: None,
            supports_long_cache_retention: None,
            requires_reasoning_content_on_assistant_messages: None,
            supports_reasoning_effort: None,
            thinking_format: None,
        }),
        reasoning: true,
        thinking_level_map: None,
        input: TEXT,
        cost: OpenCodeModelCost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 256000,
        max_tokens: 64000,
    },
    OpenCodeModel {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.2,
            output: 1.2,
            cache_read: 0.02,
            cache_write: 0.25,
        },
        context_window: 262144,
        max_tokens: 65536,
    },
    OpenCodeModel {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus",
        api: "anthropic-messages",
        provider: "opencode",
        base_url: "https://opencode.ai/zen",
        compat: None,
        reasoning: true,
        thinking_level_map: None,
        input: TEXT_IMAGE,
        cost: OpenCodeModelCost {
            input: 0.5,
            output: 3.0,
            cache_read: 0.05,
            cache_write: 0.625,
        },
        context_window: 262144,
        max_tokens: 65536,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_opencode_catalog_metadata() {
        assert_eq!(OPENCODE_MODELS.len(), 49);
        assert_eq!(OPENCODE_MODELS[0].id, "big-pickle");
        assert_eq!(
            OPENCODE_MODELS[0].compat.expect("compat").max_tokens_field,
            Some("max_tokens")
        );
        assert_eq!(OPENCODE_MODELS[48].id, "qwen3.6-plus");
        assert_eq!(OPENCODE_MODELS[48].input, TEXT_IMAGE);
    }
}
