//! Together model catalog ported from Pi's `packages/ai/src/providers/together.models.ts`.
//!
//! Pi marks this catalog as generated by `scripts/generate-models.ts`; this Rust port
//! preserves the generated entries as checked in for this port row.

/// Pricing metadata for a Together model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TogetherModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// OpenAI-compatible feature flags for a Together model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TogetherModelCompat {
    /// Whether the model supports the OpenAI store option.
    pub supports_store: bool,
    /// Whether the model supports the developer role.
    pub supports_developer_role: bool,
    /// Whether the model supports the reasoning-effort parameter.
    pub supports_reasoning_effort: bool,
    /// Name of the field Pi uses for the maximum output token limit.
    pub max_tokens_field: &'static str,
    /// Reasoning/thinking parameter format from Pi's compatibility metadata.
    pub thinking_format: Option<&'static str>,
    /// Whether the model supports strict JSON schema mode.
    pub supports_strict_mode: bool,
    /// Whether the model supports long prompt-cache retention.
    pub supports_long_cache_retention: bool,
}

/// A `thinkingLevelMap` entry list from Pi's Together model catalog.
pub type TogetherThinkingLevelMap = &'static [(&'static str, Option<&'static str>)];

/// One Together model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TogetherModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// OpenAI-compatible feature flags.
    pub compat: TogetherModelCompat,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Optional Pi thinking-level mapping.
    pub thinking_level_map: Option<TogetherThinkingLevelMap>,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: TogetherModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];
const BASE_URL: &str = "https://api.together.ai/v1";
const API: &str = "openai-completions";
const PROVIDER: &str = "together";

const COMPAT_DEFAULT: TogetherModelCompat = TogetherModelCompat {
    supports_store: false,
    supports_developer_role: false,
    supports_reasoning_effort: false,
    max_tokens_field: "max_tokens",
    thinking_format: Some("together"),
    supports_strict_mode: false,
    supports_long_cache_retention: false,
};
const COMPAT_NO_THINKING_FORMAT: TogetherModelCompat = TogetherModelCompat {
    thinking_format: None,
    ..COMPAT_DEFAULT
};
const COMPAT_REASONING_EFFORT_TOGETHER: TogetherModelCompat = TogetherModelCompat {
    supports_reasoning_effort: true,
    ..COMPAT_DEFAULT
};
const COMPAT_REASONING_EFFORT_OPENAI: TogetherModelCompat = TogetherModelCompat {
    supports_reasoning_effort: true,
    thinking_format: Some("openai"),
    ..COMPAT_DEFAULT
};

const THINKING_OFF_MINIMAL_LOW_MEDIUM: TogetherThinkingLevelMap = &[
    ("off", None),
    ("minimal", None),
    ("low", None),
    ("medium", None),
];
const THINKING_MINIMAL_LOW_MEDIUM: TogetherThinkingLevelMap =
    &[("minimal", None), ("low", None), ("medium", None)];
const THINKING_MINIMAL_LOW_MEDIUM_HIGH_XHIGH: TogetherThinkingLevelMap = &[
    ("minimal", None),
    ("low", None),
    ("medium", None),
    ("high", Some("high")),
    ("xhigh", None),
];
const THINKING_OFF_MINIMAL: TogetherThinkingLevelMap = &[("off", None), ("minimal", None)];

/// Together models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const TOGETHER_MODELS: &[TogetherModel] = &[
    TogetherModel {
        id: "MiniMaxAI/MiniMax-M2.7",
        name: "MiniMax-M2.7",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_NO_THINKING_FORMAT,
        reasoning: true,
        thinking_level_map: Some(THINKING_OFF_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 202_752,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "MiniMaxAI/MiniMax-M3",
        name: "MiniMax-M3",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT_IMAGE,
        cost: TogetherModelCost {
            input: 0.3,
            output: 1.2,
            cache_read: 0.06,
            cache_write: 0.0,
        },
        context_window: 524_288,
        max_tokens: 250_000,
    },
    TogetherModel {
        id: "Qwen/Qwen2.5-7B-Instruct-Turbo",
        name: "Qwen 2.5 7B Instruct Turbo",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: false,
        thinking_level_map: None,
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.3,
            output: 0.3,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 32_768,
        max_tokens: 32_768,
    },
    TogetherModel {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
        name: "Qwen3 235B A22B Instruct 2507 FP8",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: false,
        thinking_level_map: None,
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.2,
            output: 0.6,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 262_144,
    },
    TogetherModel {
        id: "Qwen/Qwen3.5-397B-A17B",
        name: "Qwen3.5 397B A17B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT_IMAGE,
        cost: TogetherModelCost {
            input: 0.6,
            output: 3.6,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 130_000,
    },
    TogetherModel {
        id: "Qwen/Qwen3.5-9B",
        name: "Qwen3.5 9B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT_IMAGE,
        cost: TogetherModelCost {
            input: 0.17,
            output: 0.25,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    TogetherModel {
        id: "Qwen/Qwen3.6-Plus",
        name: "Qwen3.6 Plus",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.5,
            output: 3.0,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 1_000_000,
        max_tokens: 500_000,
    },
    TogetherModel {
        id: "Qwen/Qwen3.7-Max",
        name: "Qwen3.7 Max",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: false,
        thinking_level_map: None,
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.25,
            output: 3.75,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 1_000_000,
        max_tokens: 500_000,
    },
    TogetherModel {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        name: "DeepSeek V4 Pro",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_REASONING_EFFORT_TOGETHER,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM_HIGH_XHIGH),
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.74,
            output: 3.48,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 512_000,
        max_tokens: 384_000,
    },
    TogetherModel {
        id: "essentialai/Rnj-1-Instruct",
        name: "Rnj-1 Instruct",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: false,
        thinking_level_map: None,
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.15,
            output: 0.15,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 32_768,
        max_tokens: 32_768,
    },
    TogetherModel {
        id: "google/gemma-4-31B-it",
        name: "Gemma 4 31B Instruct",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT_IMAGE,
        cost: TogetherModelCost {
            input: 0.39,
            output: 0.97,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: false,
        thinking_level_map: None,
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.04,
            output: 1.04,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi K2.6",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT_IMAGE,
        cost: TogetherModelCost {
            input: 1.2,
            output: 4.5,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_000,
    },
    TogetherModel {
        id: "moonshotai/Kimi-K2.7-Code",
        name: "Kimi K2.7 Code",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.95,
            output: 4.0,
            cache_read: 0.19,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "nvidia/nemotron-3-ultra-550b-a55b",
        name: "Nemotron 3 Ultra 550B A55B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.6,
            output: 3.6,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 512_300,
        max_tokens: 512_300,
    },
    TogetherModel {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_REASONING_EFFORT_OPENAI,
        reasoning: true,
        thinking_level_map: Some(THINKING_OFF_MINIMAL),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.15,
            output: 0.6,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_REASONING_EFFORT_OPENAI,
        reasoning: true,
        thinking_level_map: Some(THINKING_OFF_MINIMAL),
        input: TEXT,
        cost: TogetherModelCost {
            input: 0.05,
            output: 0.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "zai-org/GLM-5",
        name: "GLM-5",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.0,
            output: 3.2,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 202_752,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "zai-org/GLM-5.1",
        name: "GLM-5.1",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.4,
            output: 4.4,
            cache_read: 0.0,
            cache_write: 0.0,
        },
        context_window: 202_752,
        max_tokens: 131_072,
    },
    TogetherModel {
        id: "zai-org/GLM-5.2",
        name: "GLM-5.2",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT_DEFAULT,
        reasoning: true,
        thinking_level_map: Some(THINKING_MINIMAL_LOW_MEDIUM),
        input: TEXT,
        cost: TogetherModelCost {
            input: 1.4,
            output: 4.4,
            cache_read: 0.26,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 164_000,
    },
];
