//! xAI model catalog ported from Pi's `packages/ai/src/providers/xai.models.ts`.
//!
//! Pi marks this catalog as generated by `scripts/generate-models.ts`; this Rust port
//! preserves the generated entries as checked in for this port row.

/// Pricing metadata for an xAI model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XaiModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// OpenAI-compatible feature flags for an xAI model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct XaiModelCompat {
    /// Whether the model supports the OpenAI store option.
    pub supports_store: bool,
    /// Whether the model supports the developer role.
    pub supports_developer_role: bool,
    /// Whether the model supports the reasoning-effort parameter.
    pub supports_reasoning_effort: bool,
}

/// One xAI model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XaiModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// OpenAI-compatible feature flags.
    pub compat: XaiModelCompat,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: XaiModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];
const API: &str = "openai-completions";
const PROVIDER: &str = "xai";
const BASE_URL: &str = "https://api.x.ai/v1";
const COMPAT: XaiModelCompat = XaiModelCompat {
    supports_store: false,
    supports_developer_role: false,
    supports_reasoning_effort: false,
};

/// xAI models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const XAI_MODELS: &[XaiModel] = &[
    XaiModel {
        id: "grok-3",
        name: "Grok 3",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: false,
        input: TEXT,
        cost: XaiModelCost {
            input: 3.0,
            output: 15.0,
            cache_read: 0.75,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 8_192,
    },
    XaiModel {
        id: "grok-3-fast",
        name: "Grok 3 Fast",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: false,
        input: TEXT,
        cost: XaiModelCost {
            input: 5.0,
            output: 25.0,
            cache_read: 1.25,
            cache_write: 0.0,
        },
        context_window: 131_072,
        max_tokens: 8_192,
    },
    XaiModel {
        id: "grok-4.20-0309-non-reasoning",
        name: "Grok 4.20 (Non-Reasoning)",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: false,
        input: TEXT_IMAGE,
        cost: XaiModelCost {
            input: 1.25,
            output: 2.5,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 1_000_000,
        max_tokens: 30_000,
    },
    XaiModel {
        id: "grok-4.20-0309-reasoning",
        name: "Grok 4.20 (Reasoning)",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: XaiModelCost {
            input: 1.25,
            output: 2.5,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 1_000_000,
        max_tokens: 30_000,
    },
    XaiModel {
        id: "grok-4.3",
        name: "Grok 4.3",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: XaiModelCost {
            input: 1.25,
            output: 2.5,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 1_000_000,
        max_tokens: 30_000,
    },
    XaiModel {
        id: "grok-build-0.1",
        name: "Grok Build 0.1",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: XaiModelCost {
            input: 1.0,
            output: 2.0,
            cache_read: 0.2,
            cache_write: 0.0,
        },
        context_window: 256_000,
        max_tokens: 256_000,
    },
    XaiModel {
        id: "grok-code-fast-1",
        name: "Grok Code Fast 1",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: false,
        input: TEXT,
        cost: XaiModelCost {
            input: 0.2,
            output: 1.5,
            cache_read: 0.02,
            cache_write: 0.0,
        },
        context_window: 32_768,
        max_tokens: 8_192,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_xai_catalog_metadata() {
        assert_eq!(XAI_MODELS.len(), 7);
        assert_eq!(XAI_MODELS[0].id, "grok-3");
        assert_eq!(XAI_MODELS[0].cost.cache_read, 0.75);
        assert!(!XAI_MODELS[2].reasoning);
        assert!(XAI_MODELS[3].reasoning);
        assert_eq!(XAI_MODELS[4].context_window, 1_000_000);
        assert_eq!(XAI_MODELS[5].max_tokens, 256_000);
        assert_eq!(XAI_MODELS[6].input, TEXT);
        assert_eq!(XAI_MODELS[6].compat, COMPAT);
    }
}
