//! Xiaomi model catalog ported from Pi's `packages/ai/src/providers/xiaomi.models.ts`.
//!
//! Pi marks this catalog as generated by `scripts/generate-models.ts`; this Rust port
//! preserves the generated entries as checked in for this port row.

/// Pricing metadata for a Xiaomi model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XiaomiModelCost {
    /// Input token price in Pi's model catalog units.
    pub input: f64,
    /// Output token price in Pi's model catalog units.
    pub output: f64,
    /// Cache-read token price in Pi's model catalog units.
    pub cache_read: f64,
    /// Cache-write token price in Pi's model catalog units.
    pub cache_write: f64,
}

/// OpenAI-compatible behavior overrides for a Xiaomi model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct XiaomiModelCompat {
    /// Whether replayed assistant messages require reasoning content.
    pub requires_reasoning_content_on_assistant_messages: bool,
    /// Pi thinking payload format identifier.
    pub thinking_format: &'static str,
}

/// One Xiaomi model entry from Pi's generated model catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XiaomiModel {
    /// Model id and catalog key.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// API implementation id.
    pub api: &'static str,
    /// Provider id.
    pub provider: &'static str,
    /// Base API URL.
    pub base_url: &'static str,
    /// Compatibility flags.
    pub compat: XiaomiModelCompat,
    /// Whether the model supports reasoning.
    pub reasoning: bool,
    /// Supported input modalities.
    pub input: &'static [&'static str],
    /// Model cost metadata.
    pub cost: XiaomiModelCost,
    /// Context window in tokens.
    pub context_window: u32,
    /// Maximum output tokens.
    pub max_tokens: u32,
}

const TEXT: &[&str] = &["text"];
const TEXT_IMAGE: &[&str] = &["text", "image"];
const API: &str = "openai-completions";
const PROVIDER: &str = "xiaomi";
const BASE_URL: &str = "https://api.xiaomimimo.com/v1";
const COMPAT: XiaomiModelCompat = XiaomiModelCompat {
    requires_reasoning_content_on_assistant_messages: true,
    thinking_format: "deepseek",
};

/// Xiaomi models keyed by `id`, preserving Pi's generated catalog order and metadata.
pub const XIAOMI_MODELS: &[XiaomiModel] = &[
    XiaomiModel {
        id: "mimo-v2-flash",
        name: "MiMo-V2-Flash",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT,
        cost: XiaomiModelCost {
            input: 0.14,
            output: 0.28,
            cache_read: 0.0028,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 65_536,
    },
    XiaomiModel {
        id: "mimo-v2-omni",
        name: "MiMo-V2-Omni",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: XiaomiModelCost {
            input: 0.14,
            output: 0.28,
            cache_read: 0.0028,
            cache_write: 0.0,
        },
        context_window: 262_144,
        max_tokens: 131_072,
    },
    XiaomiModel {
        id: "mimo-v2-pro",
        name: "MiMo-V2-Pro",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT,
        cost: XiaomiModelCost {
            input: 0.435,
            output: 0.87,
            cache_read: 0.0036,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
    },
    XiaomiModel {
        id: "mimo-v2.5",
        name: "MiMo-V2.5",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT_IMAGE,
        cost: XiaomiModelCost {
            input: 0.14,
            output: 0.28,
            cache_read: 0.0028,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
    },
    XiaomiModel {
        id: "mimo-v2.5-pro",
        name: "MiMo-V2.5-Pro",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT,
        cost: XiaomiModelCost {
            input: 0.435,
            output: 0.87,
            cache_read: 0.0036,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
    },
    XiaomiModel {
        id: "mimo-v2.5-pro-ultraspeed",
        name: "MiMo-V2.5-Pro-UltraSpeed",
        api: API,
        provider: PROVIDER,
        base_url: BASE_URL,
        compat: COMPAT,
        reasoning: true,
        input: TEXT,
        cost: XiaomiModelCost {
            input: 1.305,
            output: 2.61,
            cache_read: 0.0108,
            cache_write: 0.0,
        },
        context_window: 1_048_576,
        max_tokens: 131_072,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_xiaomi_catalog_metadata() {
        assert_eq!(XIAOMI_MODELS.len(), 6);
        assert_eq!(XIAOMI_MODELS[0].id, "mimo-v2-flash");
        assert_eq!(XIAOMI_MODELS[0].max_tokens, 65_536);
        assert_eq!(XIAOMI_MODELS[1].input, TEXT_IMAGE);
        assert_eq!(XIAOMI_MODELS[2].cost.input, 0.435);
        assert_eq!(XIAOMI_MODELS[3].context_window, 1_048_576);
        assert_eq!(XIAOMI_MODELS[5].cost.output, 2.61);
        assert_eq!(XIAOMI_MODELS[5].compat, COMPAT);
    }
}
