import { generateContentConfigSchema, toolDeclarationSchema } from '../models/model.js';
import { z } from 'zod';
import { jsonObjectSchema, jsonValueSchema } from '../core/json.js';
import * as m from './model.js';
export const strategySelectionSchema = z.discriminatedUnion('kind', [z.strictObject({ kind: z.literal('draft'), strategy: m.contextStrategySchema }), z.strictObject({ kind: z.literal('file'), key: z.string().min(1), hash: z.string().min(1) })]);
export type StrategySelection = z.input<typeof strategySelectionSchema>;
export const contextPreviewProfileSchema = z.strictObject({ provider: z.string(), model: z.string(), config: generateContentConfigSchema, tools: z.record(z.string(), toolDeclarationSchema).optional(), media: jsonObjectSchema.optional(), reasoningEffort: z.string().nullish(), reasoningSummary: z.string().nullish(), textVerbosity: z.string().nullish() });
export type ContextPreviewProfile = z.input<typeof contextPreviewProfileSchema>;
export const previewContextInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), selection: strategySelectionSchema, types: m.contextTypesSchema.optional(), library: m.contextLibrarySchema.optional(), resources: jsonObjectSchema.optional(), grantedCapabilities: z.array(z.string()).optional(), profile: contextPreviewProfileSchema.optional() });
export type PreviewContextInput = z.input<typeof previewContextInputSchema>;
export const validateContextInputSchema = previewContextInputSchema.omit({ profile: true, resources: true }).extend({ resources: m.contextTypesSchema.optional() });
export type ValidateContextInput = z.input<typeof validateContextInputSchema>;
export const saveContextInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), strategy: m.contextStrategySchema, expectedHash: z.string().optional(), types: m.contextTypesSchema.optional(), library: m.contextLibrarySchema.optional() });
export type SaveContextInput = z.input<typeof saveContextInputSchema>;
export const saveContextLibraryInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), key: z.string().min(1), library: m.contextLibrarySchema, expectedHash: z.string().optional(), types: m.contextTypesSchema.optional() });
export type SaveContextLibraryInput = z.input<typeof saveContextLibraryInputSchema>;
export const saveContextTypesInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), key: z.string().min(1), types: m.contextTypesSchema, expectedHash: z.string().optional() });
export type SaveContextTypesInput = z.input<typeof saveContextTypesInputSchema>;
export const convertContextInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), strategy: m.contextStrategySchema, bindings: z.record(z.string(), m.resourceBindingSchema).optional(), formats: z.record(z.string(), m.fragmentFormatSchema).optional() });
export type ConvertContextInput = z.input<typeof convertContextInputSchema>;
export const exportContextPackageInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), artifacts: z.array(m.artifactSelectionSchema) });
export type ExportContextPackageInput = z.input<typeof exportContextPackageInputSchema>;
export const contextPackageInputSchema = z.strictObject({ workspaceId: z.string().min(1).optional(), package: m.contextPackageSchema });
export type ContextPackageInput = z.input<typeof contextPackageInputSchema>;
export const typeExampleQuerySchema = z.strictObject({ workspaceId: z.string().min(1).optional(), dataType: m.contextTypeSchema, types: m.contextTypesSchema.optional() });
export type TypeExampleQuery = z.input<typeof typeExampleQuerySchema>;
export const saveTypeExampleInputSchema = typeExampleQuerySchema.extend({ label: z.string().min(1), value: jsonValueSchema });
export type SaveTypeExampleInput = z.input<typeof saveTypeExampleInputSchema>;
