<script setup lang="ts">
const client=useClient()
import { useClient } from '@zedflow/vue'
import { computed, ref, shallowRef, watch } from 'vue'
import { VueFlow, Handle, Position, MarkerType } from '@vue-flow/core'
import { Background } from '@vue-flow/background'
import { Controls } from '@vue-flow/controls'
import type { FlowFile } from '@zedflow/sdk'
import { flowExports, routeModes, type BridgeStudioController } from '../../compositionEngine'
import type { BridgeFile, RuntimeGraph } from '@zedflow/sdk'
const props=defineProps<{studio:BridgeStudioController}>()
const emit=defineEmits<{edit:[file:BridgeFile]}>()
const resolved=shallowRef<RuntimeGraph|null>(null)
function editCurrent(){if(current.value)emit('edit',current.value.owner)}
const flows=shallowRef<FlowFile[]>([]),root=ref(''),entry=ref('main'),selected=ref<string[]>([]),error=ref(''),diagnostics=ref<{path:string;message:string}[]>([]),route=ref('')
watch(()=>props.studio.workspaceId,async workspace=>{root.value='';selected.value=[];flows.value=[];try{const value=await client.flows.list({workspaceId:workspace});if(workspace===props.studio.workspaceId)flows.value=value}catch(cause){error.value=String(cause)}},{immediate:true})
const files=computed(()=>props.studio.session.files.filter(file=>file.bridge))
const included=computed(()=>{const result=new Map<string,BridgeFile>();function add(key:string){if(result.has(key))return;const file=files.value.find(file=>file.key===key);if(!file)return;result.set(key,file);file.bridge!.requires.forEach(add)}selected.value.forEach(add);return [...result.values()]})
const instances=computed(()=>{if(resolved.value)return new Map(Object.entries(resolved.value.instances).map(([id,item])=>[id,{name:flows.value.find(file=>file.key===item.flow)?.name||item.flow,flow:item.flow}]));const values=new Map<string,{name:string;flow:string}>();values.set('root',{name:flows.value.find(file=>file.key===root.value)?.name||'Flow d’entrée à choisir',flow:root.value});for(const file of included.value)for(const [alias,item] of Object.entries(file.bridge!.imports))values.set(`${file.key}/${alias}`,{name:flows.value.find(flow=>flow.key===item.flow)?.name||item.flow,flow:item.flow});return values})
const routes=computed(()=>resolved.value?Object.entries(resolved.value.routes).flatMap(([id,value])=>{const owner=files.value.find(file=>file.key===value.bridge);return owner?[{id,owner,...value}]:[]}):included.value.flatMap(file=>Object.entries(file.bridge!.connections).map(([id,value])=>({id:`${file.key}/${id}`,owner:file,...value}))))
const nodes=computed(()=>[...instances.value].map(([id,item],i)=>({id,type:'instance',position:{x:(i%3)*320,y:Math.floor(i/3)*170},data:item})))
const edges=computed(()=>routes.value.map(item=>({id:item.id,source:resolved.value?item.from.instance:item.from.instance==='root'?'root':`${item.owner.key}/${item.from.instance}`,target:resolved.value?item.to.instance:item.to.instance==='root'?'root':`${item.owner.key}/${item.to.instance}`,label:`${item.from.port} → ${item.to.port}`,markerEnd:MarkerType.ArrowClosed})))
const current=computed(()=>routes.value.find(item=>item.id===route.value))
const entries=computed(()=>Object.keys(flowExports(flows.value.find(file=>file.key===root.value)?.composition)?.contract.entries||{}))
let intent=0
watch(()=>JSON.stringify([root.value,entry.value,selected.value,files.value,flows.value]),async()=>{const request=++intent;diagnostics.value=[];resolved.value=null;if(!root.value)return;const catalog={types:Object.assign({},...flows.value.map(file=>flowExports(file.composition)?.types||{})),flows:Object.fromEntries(flows.value.flatMap(file=>{const exports=flowExports(file.composition);return exports?[[file.key,exports.contract]]:[]})),bridges:Object.fromEntries(files.value.map(file=>[file.key,file.bridge]))};try{const value=await client.composition.analyze({catalog,request:{flow:root.value,entry:entry.value,bridges:selected.value}});if(request===intent){diagnostics.value=value.diagnostics;resolved.value=value.graph;error.value=''}}catch(cause){if(request===intent)error.value=String(cause)}})
</script>
<template><section class="composition-overview" aria-label="Composition des bridges"><p>Choisissez les définitions à examiner. Cette vue ne lance aucune exécution et n’active aucun bridge dans une session.</p><div class="selectors"><label>Flow d’entrée<select v-model="root"><option value="">Choisir un flow</option><option v-for="file in flows" :key="file.key" :value="file.key">{{file.name}}</option></select></label><label>Entrée<select v-model="entry"><option v-for="name in entries" :key="name" :value="name">{{name}}</option></select></label></div><label v-for="file in files" :key="file.key" class="bridge-choice"><input v-model="selected" type="checkbox" :value="file.key"/>{{file.key}}</label><p v-if="error" role="alert">{{error}}</p><p>{{resolved?'Composition résolue':'Déclarations des bridges · composition non résolue'}}</p><div class="composition-canvas"><VueFlow :nodes="nodes" :edges="edges" :nodes-connectable="false" :delete-key-code="null" fit-view-on-init @edge-click="route=$event.edge.id"><Background/><Controls/><template #node-instance="node"><div class="instance"><Handle type="target" :position="Position.Left"/><small>{{node.id}}</small><strong>{{node.data.name}}</strong><Handle type="source" :position="Position.Right"/></div></template></VueFlow></div><p v-for="item in diagnostics" :key="item.path+item.message" role="alert"><code>{{item.path}}</code> · {{item.message}}</p><button v-for="item in routes" :key="item.id" @click="route=item.id">{{item.id}}</button><aside v-if="current"><h3>{{current.id}}</h3><p>{{current.from.instance}} / {{current.from.port}} → {{current.to.instance}} / {{current.to.port}}</p><p>{{routeModes.find(mode=>mode.value===current?.mode)?.label}} · {{current.invocation}}</p><pre v-if="current.condition">{{JSON.stringify(current.condition,null,2)}}</pre><button @click="editCurrent">Modifier dans {{current.owner.key}}</button></aside></section></template>
<style scoped>.composition-overview{font-size:12px}.selectors{display:flex;gap:16px}.selectors label{display:flex;flex-direction:column;gap:6px;flex:1}.bridge-choice{display:inline-flex;gap:6px;margin:14px}.composition-canvas{height:420px;background:#17181c;border:1px solid #3a3c44}.instance{width:230px;padding:18px;border:1px solid #696b77;border-radius:6px;background:#27292f;display:flex;flex-direction:column;gap:9px}.instance small{color:#aaa}.composition-overview aside{padding:12px;border:1px solid #454750}.composition-overview [role=alert]{color:#e5b3a0}</style>
