<script setup lang="ts">
import { computed, ref } from 'vue'
import { Plus, X } from 'lucide-vue-next'
import type { Composition } from '@zedflow/sdk'
import { builtInChannels, emptyFlowExports, flowExports } from '../../compositionEngine'
import type { FlowExports, InvocationKind } from '@zedflow/sdk'
import ContextTypeEditor from '../context/ContextTypeEditor.vue'
const props=defineProps<{composition:Composition}>()
const value=computed(()=>flowExports(props.composition))
const needsSeparation=computed(()=>props.composition.nodes.some(node=>node.data.kind==='agent'))
const start=computed(()=>props.composition.nodes.find(node=>node.data.kind==='start')!)
const channels=computed(()=>[...new Set([...builtInChannels,...(props.composition.channels||[]).map(channel=>channel.name)])])
const section=ref<'entries'|'branches'|'data'|'requires'|'inferenceNodes'|'types'>('entries'),name=ref(''),error=ref('')
function enable(on:boolean){if(on){start.value.data.config.exports=emptyFlowExports();start.value.data.config.exports.interactive=props.composition.nodes.some(node=>['input','inbox'].includes(node.data.kind))}else delete start.value.data.config.exports}
function contextConfig(node:Composition['nodes'][number]){return node.data.kind==='model'?props.composition.nodes.find(candidate=>candidate.id===node.data.config.contextNode)?.data.config||{}:node.data.config}
function branchNodes(kind:InvocationKind){return props.composition.nodes.filter(node=>kind==='tool'?['agent','model'].includes(node.data.kind):kind==='context'?['agent','context'].includes(node.data.kind):node.data.kind==='route')}
function add(){
  if(!value.value)return
  const id=name.value.trim(),scope=section.value==='types'?value.value.types:value.value.contract[section.value]
  if(!id||Object.hasOwn(scope,id)){error.value='Choisissez une identité unique dans cette famille.';return}
  const v=value.value
  if(section.value==='entries'){v.contract.entries[id]={input:{kind:'text'},output:{kind:'text'}};v.entries[id]={node:start.value.id,inputField:'input',outputField:'output'}}
  if(section.value==='branches'){v.contract.branches[id]={contract:{input:{kind:'text'},output:{kind:'text'}},invocations:(props.composition.formatVersion||1)>=4?[]:['node'],...((props.composition.formatVersion||1)>=4?{requesters:[]}: {})};v.branches[id]=props.composition.nodes.find(node=>node.data.kind==='route')?.id||''}
  if(section.value==='data'){v.contract.data[id]={dataType:{kind:'text'},permissions:{read:true,write:false}};v.data[id]='output'}
  if(section.value==='requires'){v.contract.requires[id]={dataType:{kind:'text'},permissions:{read:true,write:false},optional:false};v.requires[id]='input'}
  if(section.value==='types')v.types[id]={kind:'record',fields:{}}
  if(section.value==='inferenceNodes'){const node=props.composition.nodes.find(node=>node.id===id&&['agent','model'].includes(node.data.kind));if(!node){error.value='Choisissez un nœud d’inférence du flow.';return}const config=node.data.config;v.contract.inferenceNodes[id]={model:config.modelBinding==='runtime'?{kind:'runtime'}:{kind:'fixed',provider:config.provider||'fixture',model:config.model||'fixture'},contextStrategy:contextConfig(node).contextStrategy?.key||contextConfig(node).contextStrategy||null,resources:[],capabilities:[]}}
  name.value='';error.value=''
}
function remove(family:'entries'|'branches'|'data'|'requires',id:string){if(value.value){delete value.value.contract[family][id];delete value.value[family][id]}}
function hasOutput(family:'entries'|'branches',id:string,enabled:boolean){if(!value.value)return;const port=family==='entries'?value.value.contract.entries[id]:value.value.contract.branches[id].contract;if(enabled){port.output={kind:'text'};if(family==='entries')value.value.entries[id].outputField='output'}else{delete port.output;if(family==='entries')delete value.value.entries[id].outputField}}
function branchKind(id:string,kind:InvocationKind){if(!value.value)return;value.value.contract.branches[id].invocations=[kind];value.value.branches[id]=branchNodes(kind)[0]?.id||''}
const neutralNodes=computed(()=>props.composition.nodes.filter(node=>['route','context','model'].includes(node.data.kind)))
function neutral(id:string){if(!value.value)return;const branch=value.value.contract.branches[id];branch.requesters=value.value.branches[id]?[value.value.branches[id]]:[];branch.invocations=[]}
function modelReference(id:string){const node=props.composition.nodes.find(node=>node.id===id);if(!node||!value.value)return;const config=node.data.config;value.value.contract.inferenceNodes[id].model=config.modelBinding==='runtime'?{kind:'runtime'}:{kind:'fixed',provider:config.provider||'fixture',model:config.model||'fixture'};value.value.contract.inferenceNodes[id].contextStrategy=contextConfig(node).contextStrategy?.key||contextConfig(node).contextStrategy||null}
</script>
<template><section class="flow-exports-editor" aria-label="Contrats publics du flow"><p v-if="needsSeparation" class="muted">Séparez d’abord le contexte et le modèle avec la conversion du graphe pour exposer cette définition.</p><button v-if="!needsSeparation&&(composition.formatVersion||1)>=2&&(composition.formatVersion||1)<3" @click="composition.formatVersion=3">Activer les contrats publics · format 3</button><p v-if="(composition.formatVersion||1)<2" class="muted">Convertissez d’abord ce flow en v2 depuis la barre d’actions.</p><label class="check-field"><input type="checkbox" :disabled="(composition.formatVersion||1)<3||needsSeparation" :checked="!!value" @change="enable(($event.target as HTMLInputElement).checked)"/>Exposer ce flow à la composition</label><template v-if="value"><p class="muted">Les bridges utilisent ces ports et ces données. Les champs d’état restent locaux au flow.</p><label class="check-field"><input v-model="value.interactive" type="checkbox"/>Ce flow peut attendre une réponse humaine</label><label>Famille de contrats<select v-model="section" aria-label="Famille de contrats"><option value="entries">Entrées publiques</option><option value="branches">Points de branchement</option><option value="data">Données exposées</option><option value="requires">Données requises</option><option value="inferenceNodes">Inférences exposées</option><option value="types">Types partagés</option></select></label>
<template v-if="section==='entries'"><div v-for="(port,id) in value.contract.entries" :key="id" class="public-contract"><header><strong>{{id}}</strong><button :aria-label="`Retirer l’entrée ${id}`" @click="remove('entries',id)"><X :size="12"/></button></header><label>Nœud d’entrée<select :aria-label="`Nœud de l’entrée ${id}`" v-model="value.entries[id].node"><option v-for="node in composition.nodes.filter(node=>node.data.kind!=='end')" :key="node.id" :value="node.id">{{node.data.label}} · {{node.id}}</option></select></label><label>Canal d’entrée<select v-model="value.entries[id].inputField" :aria-label="`Canal d’entrée ${id}`"><option v-for="name in channels" :key="name">{{name}}</option></select></label><ContextTypeEditor v-model="port.input" label="Type d’entrée publique" :names="Object.keys(value.types)"/><label class="check-field"><input type="checkbox" :checked="!!port.output" @change="hasOutput('entries',id,($event.target as HTMLInputElement).checked)"/>Retourne une sortie</label><template v-if="port.output"><ContextTypeEditor v-model="port.output" label="Type de sortie publique" :names="Object.keys(value.types)"/><label>Canal de sortie<select v-model="value.entries[id].outputField" :aria-label="`Canal de sortie ${id}`"><option v-for="name in channels" :key="name">{{name}}</option></select></label></template></div></template>
<template v-else-if="section==='branches'"><div v-for="(branch,id) in value.contract.branches" :key="id" class="public-contract"><header><strong>{{id}}</strong><button :aria-label="`Retirer le branchement ${id}`" @click="remove('branches',id)"><X :size="12"/></button></header><button v-if="(composition.formatVersion||1)>=4&&!branch.requesters" @click="neutral(id)">Convertir en prise neutre</button><label v-if="!branch.requesters">Déclenchement<select :value="branch.invocations[0]" :aria-label="`Déclenchement ${id}`" @change="branchKind(id,($event.target as HTMLSelectElement).value as InvocationKind)"><option value="tool">Appel d’outil du modèle</option><option value="context">Production de contexte</option><option value="node">Nœud de route</option><option value="condition">Condition de route</option></select></label><label>Nœud du branchement<select v-model="value.branches[id]" :aria-label="`Nœud du branchement ${id}`"><option value="" disabled>Choisir un nœud</option><option v-for="node in (branch.requesters?neutralNodes:branchNodes(branch.invocations[0]))" :key="node.id" :value="node.id">{{node.data.label}}</option></select></label><fieldset v-if="branch.requesters"><legend>Demandeurs autorisés</legend><p class="muted">Le bridge choisit le déclenchement. Seuls ces nœuds peuvent solliciter cette prise.</p><label v-for="node in neutralNodes" :key="node.id" class="check-field"><input v-model="branch.requesters" type="checkbox" :value="node.id"/>{{node.data.label}} · {{node.id}}</label></fieldset><ContextTypeEditor v-model="branch.contract.input" label="Type d’entrée du branchement" :names="Object.keys(value.types)"/><label class="check-field"><input type="checkbox" :checked="!!branch.contract.output" @change="hasOutput('branches',id,($event.target as HTMLInputElement).checked)"/>Retourne une sortie</label><ContextTypeEditor v-if="branch.contract.output" v-model="branch.contract.output" label="Type de retour du branchement" :names="Object.keys(value.types)"/></div></template>
<template v-else-if="section==='data'||section==='requires'"><div v-for="(dataset,id) in value.contract[section]" :key="id" class="public-contract"><header><strong>{{id}}</strong><button :aria-label="`Retirer la donnée ${id}`" @click="remove(section as 'data'|'requires',id)"><X :size="12"/></button></header><ContextTypeEditor v-model="dataset.dataType" label="Type de donnée" :names="Object.keys(value.types)"/><label>Canal du flow<select v-model="value[section][id]" :aria-label="`Canal de ${id}`"><option v-for="name in channels" :key="name">{{name}}</option></select></label><label>Permissions<select :value="dataset.permissions.write?'write':'read'" :aria-label="`Permissions de ${id}`" @change="dataset.permissions={read:true,write:($event.target as HTMLSelectElement).value==='write'}"><option value="read">Lecture</option><option value="write">Lecture et écriture</option></select></label><label v-if="section==='requires'" class="check-field"><input v-model="value.contract.requires[id].optional" type="checkbox"/>Donnée facultative</label></div></template>
<template v-else-if="section==='types'"><div v-for="(_,id) in value.types" :key="id" class="public-contract"><header><strong>{{id}}</strong><button :aria-label="`Retirer le type partagé ${id}`" @click="delete value.types[id]"><X :size="12"/></button></header><ContextTypeEditor v-model="value.types[id]" label="Définition du type" :names="Object.keys(value.types)"/></div></template>
<template v-else><div v-for="(inference,id) in value.contract.inferenceNodes" :key="id" class="public-contract"><header><strong>{{composition.nodes.find(node=>node.id===id)?.data.label||id}}</strong><button aria-label="Retirer cette inférence publique" @click="delete value.contract.inferenceNodes[id]"><X :size="12"/></button></header><small>{{inference.model.kind==='runtime'?'Modèle choisi à l’exécution':`${inference.model.provider} · ${inference.model.model}`}} · {{inference.contextStrategy||'Aucune stratégie de contexte'}}</small><button @click="modelReference(id)">Actualiser depuis le nœud</button><label v-for="resource in [...Object.keys(value.contract.data),...Object.keys(value.contract.requires)]" :key="resource" class="check-field"><input v-model="inference.resources" type="checkbox" :value="resource"/>{{resource}}</label><label>Capacités exposées<input :value="inference.capabilities.join(', ')" @change="inference.capabilities=($event.target as HTMLInputElement).value.split(',').map(item=>item.trim()).filter(Boolean)" placeholder="read, review"/></label></div></template>
<div class="ctx-add-field"><select v-if="section==='inferenceNodes'" v-model="name" aria-label="Inférence à exposer"><option value="" disabled>Choisir un nœud</option><option v-for="node in composition.nodes.filter(node=>['agent','model'].includes(node.data.kind))" :key="node.id" :value="node.id">{{node.data.label}}</option></select><input v-else v-model="name" aria-label="Nom du contrat public" placeholder="Identité publique" @keydown.enter.prevent="add"/><button aria-label="Ajouter le contrat public" @click="add"><Plus :size="13"/></button></div><p v-if="error" role="alert" class="field-error">{{error}}</p><p class="muted">Pour exposer un canal supplémentaire, déclarez-le dans les paramètres ADK du flow.</p></template></section></template>
<style scoped>.flow-exports-editor{display:flex;flex-direction:column;gap:12px;margin-top:18px}.public-contract{display:flex;flex-direction:column;gap:10px;padding:12px 0;border-top:1px solid #393940}.public-contract>header{display:flex;justify-content:space-between;font-size:12px;align-items:center}.public-contract>header button{border:0;padding:3px;background:transparent}.public-contract small{font-size:11px;color:#9898a3}.flow-exports-editor .ctx-add-field{margin:0}.flow-exports-editor .ctx-add-field input{min-width:0;flex:1}</style>
