use std::{
    fs,
    path::PathBuf,
    time::{SystemTime, UNIX_EPOCH},
};

use zedflow_coding_agent::{
    package_manager::{DefaultPackageManager, PackageScope},
    resource_loader::DefaultResourceLoader,
};

fn temp_dir() -> PathBuf {
    std::env::temp_dir().join(format!(
        "zedflow-package-manager-{}-{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ))
}

#[test]
fn installs_lists_and_removes_only_locally_built_source_extensions() {
    let root = temp_dir();
    let source = root.join("input");
    fs::create_dir_all(source.join("src")).unwrap();
    fs::write(
        source.join("Cargo.toml"),
        "[package]\nname = \"zedflow-rust-extension-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[workspace]\n\n[lib]\ncrate-type = [\"cdylib\"]\n",
    )
    .unwrap();
    fs::write(
        source.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"zedflow-rust-extension-fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(
        source.join("src/lib.rs"),
        "#[unsafe(no_mangle)]\npub extern \"C\" fn zedflow_rust_extension_fixture() {}\n",
    )
    .unwrap();
    fs::create_dir_all(source.join("skills/example")).unwrap();
    fs::write(
        source.join("skills/example/SKILL.md"),
        "---\nname: example\ndescription: package skill\n---\n",
    )
    .unwrap();

    fs::create_dir_all(root.join("cwd")).unwrap();
    let manager = DefaultPackageManager::new(root.join("cwd"), root.join("agent"));
    let source_spec = format!("path:{}", source.display());
    // The command-facing source install derives Cargo's cdylib name; callers
    // cannot provide a prebuilt artifact path.
    let install = manager
        .install_source(&source_spec, PackageScope::User)
        .unwrap();
    assert!(install.artifact.is_file());
    assert_eq!(manager.list_configured_packages().len(), 1);
    let mut resources = DefaultResourceLoader::new(root.join("cwd"), root.join("agent"));
    resources.reload();
    assert!(
        resources
            .get_skills()
            .skills
            .iter()
            .any(|skill| skill.name == "example"),
        "skills: {:?}; diagnostics: {:?}; extensions: {:?}",
        resources.get_skills().skills,
        resources.get_skills().diagnostics,
        resources.get_extensions().errors,
    );
    assert!(manager.remove(&source_spec, PackageScope::User).unwrap());
    assert!(manager.list_configured_packages().is_empty());
    let _ = fs::remove_dir_all(root);
}
