<script setup lang="ts">
const client=useClient()
import { useClient } from '@zedflow/vue'

import { useReloadDrafts, managedReload } from '../../composables/reloadState'
import { computed, reactive, ref, watch, onUnmounted } from 'vue'
import ContextTypeEditor from './ContextTypeEditor.vue'
import ContextTypeExplorer from './ContextTypeExplorer.vue'
import type { ContextSourceEntry } from '../../contextSources'
import AppDialog from '../AppDialog.vue'
import { cloneContext, contextId, } from '../../contextEngine'
import type { ContextType, ContextTypesFile } from '@zedflow/sdk'
const props=defineProps<{workspaceId:string;active:boolean}>()
const emit=defineEmits<{saved:[file:ContextTypesFile];use:[file:ContextTypesFile]}>()
interface Draft{key:string;types:Record<string,ContextType>;file?:ContextTypesFile;baseline:string;error:string;notice:string;pending:boolean}
interface Session{files:ContextTypesFile[];drafts:Record<string,Draft>;selected:string;error:string}
const sessions=reactive<Record<string,Session>>({})
  useReloadDrafts('type-drafts',sessions)
function blank():Draft{return{key:contextId('types'),types:{},baseline:'{}',error:'',notice:'',pending:false}}
function state(){return sessions[props.workspaceId]||={files:[],drafts:{new:blank()},selected:'new',error:''}}
const session=computed(state),draft=computed(()=>session.value.drafts[session.value.selected]),dirty=computed(()=>JSON.stringify(draft.value.types)!==draft.value.baseline)
const exploring=ref(true)
function copyType(entry:ContextSourceEntry){create();draft.value.types=cloneContext(entry.types);if(entry.type.kind!=='named')draft.value.types[entry.label]=cloneContext(entry.type)}
const name=ref(''),sourceOpen=ref(false),reloadOpen=ref(false)
async function refresh(){const workspace=props.workspaceId,current=state();if(!workspace)return;try{const value=await client.context.listTypes({workspaceId:workspace});current.files=Array.isArray(value)?value:[];current.error=''}catch(cause){current.error=cause instanceof Error?cause.message:String(cause)}}
function create(copy=false){exploring.value=false;const value=blank();if(copy)value.types=cloneContext(draft.value.types);const key=`draft:${value.key}`;session.value.drafts[key]=value;session.value.selected=key}
async function open(key:string,reload=false){exploring.value=false;const current=state(),workspace=props.workspaceId;if(!key)return;if(current.drafts[key]&&!reload){current.selected=key;return}const value=current.drafts[key]||=blank();current.selected=key;value.pending=true;try{const file=await client.context.readTypes(key,{workspaceId:workspace});value.file=file;value.key=file.key;value.types=cloneContext(file.types||{});value.baseline=JSON.stringify(value.types);value.error=file.diagnostics.map(item=>item.message).join('; ')}catch(cause){value.error=cause instanceof Error?cause.message:String(cause)}finally{value.pending=false;reloadOpen.value=false}}
function add(){const key=name.value.trim();if(!key||Object.hasOwn(draft.value.types,key)){draft.value.error='Choisissez une identité de type unique.';return}draft.value.types[key]={kind:'record',fields:{}};name.value='';draft.value.error=''}
async function save(){const current=state(),value=draft.value,workspace=props.workspaceId,slot=current.selected;if(value.pending)return;value.pending=true;value.error='';value.notice='';const types=cloneContext(value.types);try{const file=await client.context.saveTypes({workspaceId:workspace,key:value.key,types,...(value.file?{expectedHash:value.file.hash}:{})});value.file=file;value.baseline=JSON.stringify(types);value.notice='Catalogue de types enregistré en Rust';current.files=[...current.files.filter(item=>item.key!==file.key),file];if(slot!==file.key){current.drafts[file.key]=value;delete current.drafts[slot];if(current.selected===slot)current.selected=file.key}emit('saved',file)}catch(cause){value.error=cause instanceof Error?cause.message:String(cause)}finally{value.pending=false}}
function keys(event:KeyboardEvent){if(props.active&&!exploring.value&&(event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();event.stopPropagation();void save()}}
watch(()=>[props.workspaceId,props.active],()=>{if(props.active)void refresh()},{immediate:true})
const beforeUnload=(event:BeforeUnloadEvent)=>{if(!managedReload&&Object.values(sessions).some(session=>Object.values(session.drafts).some(value=>JSON.stringify(value.types)!==value.baseline)))event.preventDefault()}
window.addEventListener('beforeunload',beforeUnload);onUnmounted(()=>window.removeEventListener('beforeunload',beforeUnload))

</script>
<template><section class="ctx-types-library" aria-label="Éditeur de types" @keydown="keys"><header class="ctx-function-toolbar"><button :aria-pressed="exploring" @click="exploring=true">Tous les types</button><label v-if="!exploring">Catalogue ouvert<select aria-label="Catalogue de types ouvert" :value="session.selected" @change="open(($event.target as HTMLSelectElement).value)"><option v-for="file in session.files" :key="file.key" :value="file.key">{{file.key}}</option><option v-for="(value,key) in session.drafts" v-show="!value.file" :key="key" :value="key">{{value.key}} · brouillon</option></select></label><button @click="create()">Nouveau catalogue de types</button><button v-if="!exploring" @click="create(true)">Dupliquer le catalogue</button><button v-if="!exploring" :disabled="draft.pending||!!draft.file&&!draft.file.types" @click="save">Enregistrer les types</button><button v-if="draft.file" :disabled="draft.pending" @click="reloadOpen=true">Recharger</button><button :disabled="!draft.file?.source" @click="sourceOpen=true">Rust des types</button><button :disabled="!draft.file?.types||dirty" @click="emit('use',draft.file!)">Utiliser pour l’aperçu</button></header><p v-if="draft.error||session.error" role="alert" class="ctx-alert ctx-error">{{draft.error||session.error}}</p><p v-if="draft.notice" role="status" class="ctx-alert">{{draft.notice}}</p><ContextTypeExplorer v-if="exploring" :workspace-id="workspaceId" @copy="copyType"/><fieldset v-else :disabled="draft.pending||!!draft.file&&!draft.file.types" class="ctx-types-content"><label>Identifiant du catalogue<input aria-label="Identifiant du catalogue de types" v-model="draft.key" :readonly="!!draft.file"/></label><small>{{dirty?'Brouillon modifié':draft.file?.hash||'Nouveau catalogue'}} · .zedflow/types</small><p>Les types nommés conservent leur identité métier. Le nœud sélectionne explicitement ce catalogue.</p><div v-for="(_,key) in draft.types" :key="key" class="ctx-resource"><header><strong>{{key}}</strong><button :aria-label="`Retirer le type ${key}`" @click="delete draft.types[key]">Retirer</button></header><ContextTypeEditor v-model="draft.types[key]" :label="`Définition de ${key}`" :names="Object.keys(draft.types)"/></div><div class="ctx-add-field"><input aria-label="Nom du type du catalogue" v-model="name" @keydown.enter.prevent="add"/><button aria-label="Ajouter un type au catalogue" @click="add">Ajouter un type</button></div></fieldset><AppDialog v-model:open="sourceOpen" title="Rust du catalogue de types" wide><p v-if="dirty">Source de la dernière version enregistrée.</p><pre class="source-preview">{{draft.file?.source}}</pre></AppDialog><AppDialog v-model:open="reloadOpen" title="Recharger les types"><p>Remplacer ce brouillon par le fichier Rust du catalogue ?</p><footer><button @click="reloadOpen=false">Conserver le brouillon</button><button @click="open(draft.file!.key,true)">Recharger depuis le disque</button></footer></AppDialog></section></template>
<style scoped>.ctx-types-library{min-height:0;display:flex;flex-direction:column;height:100%;overflow:auto}.ctx-types-content{min-width:0;padding:20px;display:flex;flex-direction:column;gap:14px;border:0;max-width:850px;width:100%}.ctx-types-content>label{display:flex;flex-direction:column;gap:8px;font-size:12px}.ctx-types-content p,.ctx-types-content small{font-size:11px;color:#a4a0b0;line-height:1.6}.ctx-types-content header{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;font-size:12px}</style>
