<script setup lang="ts">
import { shallowRef } from 'vue'
const client=useClient()
import { useClient } from '@zedflow/vue'

import { computed, ref, watch } from 'vue'
import type { Workspace } from '@zedflow/sdk'
import AppDialog from '../AppDialog.vue'
import type { ContextDiagnostic } from '@zedflow/sdk'
type Kind='strategy'|'library'|'bridge'|'types'|'example'
import { contextPackageSchema, type SourceArtifact, type ContextPackage, type ContextPackageValidation } from '@zedflow/sdk'
const open=defineModel<boolean>('open',{required:true})
const props=defineProps<{workspaceId:string;workspaces:Workspace[]}>()
const emit=defineEmits<{imported:[]}>()
const mode=ref<'export'|'import'>('export'),workspace=ref(''),files=ref<(Omit<SourceArtifact,'source'>&{valid:boolean})[]>([]),selected=ref<string[]>([])
const packageValue=shallowRef<ContextPackage>(),validation=shallowRef<ContextPackageValidation>(),error=ref(''),notice=ref(''),busy=ref(false),filename=ref('');let intent=0
const labels:Record<Kind,string>={strategy:'Stratégies',library:'Bibliothèques',bridge:'Bridges',types:'Types',example:'Exemples par type'}
const groups=computed(()=>Object.entries(labels).map(([kind,label])=>({kind,label,files:files.value.filter(file=>file.kind===kind)})))
const identity=(file:{kind:Kind;key:string})=>`${file.kind}/${file.key}`
async function refresh(){const request=++intent,id=workspace.value;if(!id||!open.value)return;busy.value=true;error.value='';selected.value=[];try{const query={workspaceId:id};const groups=await Promise.all([
  client.context.list(query).then(files=>({kind:'strategy' as const,files})),
  client.context.listLibraries(query).then(files=>({kind:'library' as const,files})),
  client.composition.listBridges(query).then(files=>({kind:'bridge' as const,files})),
  client.context.listTypes(query).then(files=>({kind:'types' as const,files})),
  client.context.exampleCatalog(query).then(files=>({kind:'example' as const,files})),
]);const results=groups.map(({kind,files})=>files.map(file=>({kind,key:file.key,hash:file.hash,valid:!file.diagnostics?.length})));if(request===intent)files.value=results.flat()}catch(cause){if(request===intent)error.value=cause instanceof Error?cause.message:String(cause)}finally{if(request===intent)busy.value=false}}
async function exportPackage(){const request=++intent,id=workspace.value;busy.value=true;error.value='';try{const artifacts=files.value.filter(file=>selected.value.includes(identity(file))).map(({kind,key})=>({kind,key}));const value=await client.context.exportPackage({workspaceId:id,artifacts});if(request!==intent)return;const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='zedflow-definitions.json';link.click();URL.revokeObjectURL(url);notice.value=`${value.artifacts.length} fichiers de définition et d’exemple exportés avec leurs empreintes.`}catch(cause){if(request===intent)error.value=cause instanceof Error?cause.message:String(cause)}finally{if(request===intent)busy.value=false}}
async function validate(){const value=packageValue.value;if(!value)return;const request=++intent;busy.value=true;error.value='';validation.value=undefined;try{const result=await client.context.validatePackage({workspaceId:workspace.value,package:value});if(request===intent)validation.value=result}catch(cause){if(request===intent)error.value=cause instanceof Error?cause.message:String(cause)}finally{if(request===intent)busy.value=false}}
async function readFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;intent++;packageValue.value=undefined;validation.value=undefined;filename.value=file.name;error.value='';notice.value='';if(file.size>64*1024*1024){error.value='Le package dépasse 64 Mo.';return}try{const value=contextPackageSchema.parse(JSON.parse(await file.text()));packageValue.value=value;await validate()}catch(cause){error.value=cause instanceof Error?cause.message:String(cause)}}
async function importPackage(){if(!validation.value?.valid||!packageValue.value)return;const request=++intent;busy.value=true;error.value='';try{const result=await client.context.importPackage({workspaceId:workspace.value,package:packageValue.value});if(request===intent){notice.value=`${result.files.length} fichiers importés dans le workspace sélectionné.`;emit('imported')}}catch(cause){if(request===intent)error.value=cause instanceof Error?cause.message:String(cause)}finally{if(request===intent)busy.value=false}}
watch(open,value=>{intent++;if(value){workspace.value=props.workspaceId;error.value='';notice.value='';void refresh()}else busy.value=false})
watch(workspace,()=>{if(!open.value)return;if(mode.value==='export')void refresh();else if(packageValue.value)void validate()})
watch(mode,value=>{error.value='';notice.value='';if(value==='export')void refresh()})

</script>
<template><AppDialog v-model:open="open" title="Partager des définitions" wide><section class="context-package"><nav aria-label="Transfert de définitions"><button :aria-pressed="mode==='export'" @click="mode='export'">Exporter</button><button :aria-pressed="mode==='import'" @click="mode='import'">Importer</button></nav><label>Workspace du transfert<select aria-label="Workspace du transfert" v-model="workspace" :disabled="busy"><option v-for="item in workspaces" :key="item.id" :value="item.id">{{item.name}} · {{item.path}}</option></select></label><p>Le package contient les sources Rust exactes, les exemples JSON sélectionnés et leurs empreintes. Les flows requis par les bridges sont des dépendances explicites.</p><template v-if="mode==='export'"><section v-for="group in groups" :key="group.kind"><h3>{{group.label}}</h3><label v-for="file in group.files" :key="identity(file)" class="package-file"><input type="checkbox" v-model="selected" :value="identity(file)" :disabled="!file.valid||busy"/><span>{{file.key}}<small>{{file.hash.slice(0,12)}}{{file.valid?'':' · diagnostic de source'}}</small></span></label><small v-if="!group.files.length">Aucun fichier dans ce catalogue.</small></section><button :disabled="busy||!selected.length" @click="exportPackage">Télécharger le package</button></template><template v-else><label>Fichier du package<input aria-label="Fichier du package" type="file" accept="application/json,.json" :disabled="busy" @change="readFile"/></label><p v-if="filename">{{filename}}</p><ul v-if="packageValue"><li v-for="file in packageValue.artifacts" :key="identity(file)">{{labels[file.kind]||file.kind}} · {{file.key}}</li></ul><template v-if="validation"><p :class="validation.valid?'package-valid':'field-error'" role="status">{{validation.valid?'Sources et empreintes valides':'Le package contient des erreurs'}}</p><ul v-if="validation.prerequisites.length" aria-label="Dépendances du package"><li v-for="item in validation.prerequisites" :key="`${item.kind}/${item.key}`">{{item.kind}} requis · {{item.key}}</li></ul><p v-for="(item,index) in validation.diagnostics" :key="index" role="alert" class="field-error">{{item.path}} · {{item.message}}</p></template><button :disabled="busy||!validation?.valid" @click="importPackage">Importer les définitions</button><p>Les conflits de fichiers sont signalés ; les sources présentes ne sont pas écrasées silencieusement.</p></template><p v-if="busy" role="status">{{mode==='import'?'Validation / import en cours…':'Chargement des fichiers…'}}</p><p v-if="error" role="alert" class="field-error">{{error}}</p><p v-if="notice" role="status">{{notice}}</p></section></AppDialog></template>
<style scoped>.context-package{display:flex;flex-direction:column;gap:13px;max-height:75vh;overflow:auto;font-size:12px}.context-package nav{display:flex;gap:7px}.context-package label{display:flex;flex-direction:column;gap:8px}.context-package h3{font-size:12px;margin:6px 0}.context-package small,.context-package p{color:#a5a1ae;font-size:11px;line-height:1.6}.context-package .package-file{flex-direction:row;align-items:center;padding:7px 4px;gap:10px}.package-file input{width:auto}.package-file span{display:flex;flex-direction:column;gap:3px}.context-package button[aria-pressed=true]{background:#46414f}.context-package ul{padding-left:20px;line-height:1.8}.package-valid{color:#91b897!important}</style>
