<script setup lang="ts">
import type { JsonValue } from '@zedflow/sdk'

import { ref, watch } from 'vue'
import { contextId, defaultContextValue } from '../../contextEngine'
import type { ContextItem, ContextType } from '@zedflow/sdk'
import ContextTypeEditor from './ContextTypeEditor.vue'
import ContextValueEditor from './ContextValueEditor.vue'
const value=defineModel<ContextItem>({required:true})
const props=withDefaults(defineProps<{depth?:number}>(),{depth:0})
function infer(input:JsonValue):ContextType{if(typeof input==='string')return{kind:'text'};if(typeof input==='boolean')return{kind:'boolean'};if(typeof input==='number')return{kind:'number'};if(Array.isArray(input))return{kind:'list',item:input.length?infer(input[0]):{kind:'text'}};if(input&&typeof input==='object')return{kind:'record',fields:Object.fromEntries(Object.entries(input).map(([key,item])=>[key,infer(item)]))};return{kind:'text'}}
const dataType=ref<ContextType>({kind:'text'})
watch(()=>value.value.id,()=>{if(value.value.kind==='fragment')dataType.value=infer(value.value.value)},{immediate:true})
function kind(next:string){if(next===value.value.kind)return;const id=value.value.id;value.value=next==='group'?{kind:'group',id,label:'Nouveau groupe',items:[]}:{kind:'fragment',id,role:'data',format:'text',value:'',sources:[]}}
function format(next:'text'|'json'|'media'|'adkMessages'){if(value.value.kind!=='fragment')return;value.value.format=next;dataType.value=next==='media'?{kind:'media',mediaType:'image/png'}:next==='adkMessages'?{kind:'list',item:{kind:'record',fields:{role:{kind:'text'},text:{kind:'text'}}}}:next==='json'?{kind:'record',fields:{}}:{kind:'text'};value.value.value=defaultContextValue(dataType.value)}
function changeType(next:ContextType){dataType.value=next;if(value.value.kind==='fragment')value.value.value=defaultContextValue(next)}
function add(kind:'fragment'|'group'){if(value.value.kind==='group')value.value.items.push(kind==='group'?{kind,id:contextId('group'),label:'Nouveau groupe',items:[]}:{kind,id:contextId('fragment'),role:'data',format:'text',value:'',sources:[]})}
</script>
<template><fieldset class="context-item-editor"><legend>{{value.id}}</legend><label>Élément<select aria-label="Type d’élément de fenêtre" :value="value.kind" @change="kind(($event.target as HTMLSelectElement).value)"><option value="fragment">Fragment</option><option value="group">Groupe</option></select></label><template v-if="value.kind==='group'"><label>Nom du groupe<input aria-label="Nom du groupe de fenêtre" v-model="value.label"/></label><div v-for="(child,index) in value.items" :key="child.id"><ContextItemEditor v-if="depth<16" v-model="value.items[index]" :depth="depth+1"/><button :aria-label="`Retirer l’élément ${child.id}`" @click="value.items.splice(index,1)">Retirer cet élément</button></div><div class="ctx-row"><button @click="add('fragment')">Ajouter un fragment</button><button v-if="depth<16" @click="add('group')">Ajouter un groupe</button></div></template><template v-else><label>Rôle<select aria-label="Rôle du fragment" v-model="value.role"><option value="data">Donnée</option><option value="instruction">Instruction</option></select></label><label>Format<select aria-label="Format du remplacement" :value="value.format" @change="format(($event.target as HTMLSelectElement).value as 'text'|'json'|'media'|'adkMessages')"><option value="text">Texte</option><option value="json">JSON structuré</option><option value="media">Référence média</option><option value="adkMessages">Messages ADK structurés</option></select></label><ContextTypeEditor v-if="value.format==='json'||value.format==='adkMessages'" :model-value="dataType" label="Structure du remplacement" @update:model-value="changeType"/><ContextValueEditor v-model="value.value" :type="value.format==='text'?{kind:'text'}:value.format==='media'?{kind:'media',mediaType:typeof value.value==='object'&&value.value&&!Array.isArray(value.value)?String(value.value.mediaType||'image/png'):'image/png'}:dataType" label="Contenu du remplacement"/><small>Sources conservées : {{value.sources.join(', ')||'élément créé dans la fenêtre'}}</small></template></fieldset></template>
<style scoped>.context-item-editor{border:1px solid #4a4551;min-width:0;padding:13px;display:flex;flex-direction:column;gap:12px;margin:10px 0}.context-item-editor legend,.context-item-editor small{font-size:10px;color:#aaa5b6;overflow-wrap:anywhere}.context-item-editor label{display:flex;flex-direction:column;gap:6px;font-size:12px}.context-item-editor button{font-size:11px}.context-item-editor .ctx-row{flex-wrap:wrap}</style>
