<script setup lang="ts">
import { computed, ref } from 'vue'
import type { Composition, FlowNode } from '@zedflow/sdk'
import { requireNodeConfig } from '@zedflow/sdk'
import { flowExports } from '../../compositionEngine'

const props=defineProps<{node:FlowNode;composition?:Composition}>()
const config=computed(()=>requireNodeConfig(props.node.data.config)),alias=ref(''),error=ref('')
const branches=computed(()=>Object.entries(flowExports(props.composition)?.contract.branches||{}).filter(([name,port])=>port.invocations.includes('context')&&flowExports(props.composition)?.branches[name]===props.node.id).map(([name])=>name))
function enable(on:boolean){if(on)config.value.contextWindow={alias:`context-${props.node.id}`};else delete config.value.contextWindow}
function prepare(on:boolean){const window=config.value.contextWindow;if(!window)return;if(on)window.prepare={branch:branches.value[0]||'',routeId:''};else delete window.prepare}
function grant(){const name=alias.value.trim();if(!name||config.value.windowGrants?.some((item:{alias:string})=>item.alias===name)){error.value='Choisissez un alias de fenêtre unique.';return}config.value.windowGrants=[...(config.value.windowGrants||[]),{alias:name,permission:'read'}];alias.value='';error.value=''}
function toggleTool(name:string,on:boolean){config.value.attachments||={};config.value.attachments.tools||={items:[]};const items=config.value.attachments.tools.items;const found=items.find((item:{name:string})=>item.name===name);if(on&&found)found.enabled=true;else if(on)items.push({id:crypto.randomUUID(),name});else config.value.attachments.tools.items=items.filter((item:{name:string})=>item.name!==name)}
</script>
<template><details class="settings-group context-runtime-settings"><summary>Fenêtre révisable</summary><p class="muted">La stratégie prépare un contexte frais à chaque passage. Une fenêtre nommée conserve des révisions inspectables ; une révision modifiée doit être sélectionnée explicitement pour le prochain passage.</p><label class="check-field"><input type="checkbox" :checked="!!config.contextWindow" @change="enable(($event.target as HTMLInputElement).checked)"/>Nommer la fenêtre de ce nœud</label><template v-if="config.contextWindow"><label>Alias de la fenêtre<input v-model="config.contextWindow.alias" aria-label="Alias de la fenêtre"/></label><label class="check-field"><input type="checkbox" :checked="!!config.contextWindow.prepare" @change="prepare(($event.target as HTMLInputElement).checked)"/>Préparation par une route de contexte</label><template v-if="config.contextWindow.prepare"><label>Branchement de préparation<select v-model="config.contextWindow.prepare.branch" aria-label="Branchement de préparation"><option value="" disabled>Choisir un branchement exposé</option><option v-for="name in branches" :key="name">{{name}}</option></select></label><label>Route de préparation · requise<input v-model="config.contextWindow.prepare.routeId" placeholder="bridge/connexion"/></label><p v-if="!branches.length" class="muted">Exposez un branchement de contexte sur ce nœud dans les contrats du Départ.</p></template></template><h4>Fenêtres accessibles aux outils</h4><div v-for="(grant,index) in config.windowGrants||[]" :key="grant.alias" class="ctx-row"><code>{{grant.alias}}</code><select v-model="grant.permission" :aria-label="`Permission fenêtre ${grant.alias}`"><option value="read">Lecture</option><option value="write">Lecture et écriture</option></select><button :aria-label="`Retirer l’accès à ${grant.alias}`" @click="config.windowGrants?.splice(index,1)">×</button></div><div class="ctx-add-field"><input v-model="alias" aria-label="Alias de fenêtre à autoriser" placeholder="Alias exact" @keydown.enter.prevent="grant"/><button aria-label="Autoriser cette fenêtre" @click="grant">+</button></div><label v-for="tool in [{name:'context_window_read',label:'Lire une fenêtre'},{name:'context_window_patch',label:'Modifier une fenêtre'}]" :key="tool.name" class="check-field"><input type="checkbox" :checked="config.attachments?.tools?.items.some((item)=>item.name===tool.name&&item.enabled!==false)" @change="toggleTool(tool.name,($event.target as HTMLInputElement).checked)"/>{{tool.label}}</label><small class="muted">Les outils et les permissions sur les alias sont accordés séparément. Un outil ne donne pas accès aux autres fenêtres.</small><p v-if="error" role="alert" class="field-error">{{error}}</p></details></template>
<style scoped>.context-runtime-settings h4{font-size:12px;margin:18px 0 10px}.context-runtime-settings .ctx-row{align-items:center}.context-runtime-settings .ctx-row code{font-size:11px;overflow-wrap:anywhere}.context-runtime-settings .ctx-row select{min-width:0}.context-runtime-settings small{display:block;font-size:11px}</style>
