<script setup lang="ts">
const client=useClient()
import { useClient } from '@zedflow/vue'

import { onScopeDispose, computed, ref, shallowRef, watch } from 'vue'
import type { ContextBlock, ContextLibrary, ContextStrategy, ContextType } from '@zedflow/sdk'
import ContextExpressionEditor from './ContextExpressionEditor.vue'
import ContextPredicateEditor from './ContextPredicateEditor.vue'
import AppDialog from '../AppDialog.vue'
import type { ContextProgram } from '@zedflow/sdk'
const open=defineModel<boolean>('open',{required:true})
const props=defineProps<{runId:string;workspaceId?:string;nodePath:string;hash:string;blockId?:string}>()
const emit=defineEmits<{copy:[program:ContextProgram,blockId:string]}>()
const value=shallowRef<ContextProgram>(),selected=ref(''),error=ref(''),loading=ref(false),tab=ref<'block'|'source'>('block')
let intent=0
function flatten(blocks:ContextBlock[],prefix=''): {id:string;label:string;block:ContextBlock}[]{return blocks.flatMap(block=>[{id:block.id,label:`${prefix}${block.kind==='group'?block.label:block.kind==='if'?'Condition':block.id}`,block},...((block.kind==='group'||block.kind==='forEach')?flatten(block.items,`${prefix}› `):block.kind==='if'?[...flatten(block.then,`${prefix}oui › `),...flatten(block.else,`${prefix}non › `)]:[])])}
const blocks=computed(()=>flatten(value.value?.strategy.program||[])),block=computed(()=>blocks.value.find(item=>item.id===selected.value)?.block)
watch(()=>[open.value,props.runId,props.workspaceId,props.nodePath,props.hash],async()=>{const request=++intent;if(!open.value)return;value.value=undefined;loading.value=true;error.value='';const key=`${props.workspaceId}/${props.runId}/${props.nodePath}/${props.hash}`;try{const program=await client.details.load({runId:props.runId,workspaceId:props.workspaceId||'',kind:'context-program',revision:props.hash,query:{nodePath:props.nodePath,hash:props.hash}});if(request!==intent)return;value.value=program;selected.value=props.blockId||blocks.value[0]?.id||''}catch(cause){if(request===intent)error.value=String(cause instanceof Error?cause.message:cause)}finally{if(request===intent)loading.value=false}},{immediate:true})

onScopeDispose(()=>{intent++})
</script>
<template><AppDialog v-model:open="open" title="Définition de contexte exécutée" wide><div class="context-definition"><p v-if="loading" role="status">Chargement de la définition figée…</p><p v-if="error" role="alert" class="field-error">{{error}}</p><template v-if="value"><header><strong>{{value.strategy.name}}</strong><code>{{hash}}</code><small v-if="hash!==value.hash">Stratégie Rust · {{value.hash}}</small><small>Lecture seule · {{nodePath}}</small></header><nav class="ctx-editor-tabs" aria-label="Définition exécutée"><button :aria-pressed="tab==='block'" @click="tab='block'">Blocs</button><button :aria-pressed="tab==='source'" @click="tab='source'">Source Rust exacte</button></nav><template v-if="tab==='block'"><label>Bloc de la définition<select aria-label="Bloc de la définition" v-model="selected"><option v-for="item in blocks" :key="item.id" :value="item.id">{{item.label}}</option></select></label><fieldset v-if="block" disabled :data-frozen-block="block.id"><legend>{{block.id}}</legend><template v-if="block.kind==='emit'"><p>{{block.role==='instruction'?'Instruction':'Donnée'}} · {{block.format}}</p><ContextExpressionEditor :model-value="block.value" :resources="value.strategy.requirements" :types="value.types" label="Expression exécutée"/></template><ContextPredicateEditor v-else-if="block.kind==='if'" :model-value="block.condition" :resources="value.strategy.requirements" :types="value.types"/><p v-else>{{block.kind==='group'?block.label:'Pour chaque '+block.item}} · {{block.items.length}} blocs</p></fieldset><p v-if="!block" class="muted">Le fragment a été créé ou remplacé dans la fenêtre ; aucun bloc de cette identité n’existe dans la définition figée.</p></template><pre v-else class="source-preview">{{value.source}}</pre><details v-for="file in [...(value.librarySources||[]),...(value.typeSources||[])]" :key="`${file.key}/${file.hash}`" class="frozen-context-source"><summary>{{file.key}} · {{file.hash.slice(0,12)}}</summary><pre class="source-preview">{{file.source}}</pre></details><footer><small>Une copie conserve cette occurrence et les autres brouillons.</small><button @click="emit('copy',value,selected);open=false">Créer un brouillon depuis cette version</button></footer></template></div></AppDialog></template>
<style scoped>.context-definition{max-height:76vh;overflow:auto;display:flex;flex-direction:column;gap:15px;padding:2px}.context-definition>header{display:flex;flex-direction:column;gap:6px}.context-definition code{font-size:11px;color:#a8a8b3;overflow-wrap:anywhere}.context-definition small{font-size:11px;color:#9999a7}.context-definition label{display:flex;flex-direction:column;gap:7px;font-size:12px}.context-definition select{color:#ddd;background:#272730;padding:8px;border:1px solid #4c4c57;border-radius:4px}.context-definition fieldset{min-width:0;padding:15px;border:1px solid #4d4d58}.context-definition fieldset:disabled{opacity:.9}.context-definition legend{font-size:12px}.context-definition :deep(input:disabled),.context-definition :deep(textarea:disabled),.context-definition :deep(select:disabled){color:#d2d2de;opacity:1}.context-definition :deep(.ctx-wrap){display:none}</style>
