<script setup lang="ts">
import { computed } from 'vue'
import { Plus, RefreshCw, FileCode2, AlertTriangle } from 'lucide-vue-next'
import type { Workspace } from '@zedflow/sdk'
import type { ContextStudioController } from '../../contextEngine'

const props=defineProps<{studio:ContextStudioController;workspaces:Workspace[]}>()
const emit=defineEmits<{workspace:[id:string]}>()
const drafts=computed(()=>Object.entries(props.studio.session.drafts).filter(([key,draft])=>!draft.file&&(key===props.studio.session.selected||draft.strategy.name!=='Nouvelle stratégie'||draft.strategy.program.length||Object.keys(draft.strategy.requirements).length||draft.strategy.capabilities.length)))
</script>
<template>
  <div class="ctx-library"><label class="ctx-workspace">Workspace des stratégies<select aria-label="Workspace des stratégies" :value="studio.workspaceId" @change="emit('workspace',($event.target as HTMLSelectElement).value)"><option v-for="workspace in workspaces.filter(item=>item.open)" :key="workspace.id" :value="workspace.id">{{workspace.name}}</option></select></label><div class="ctx-library-actions"><button :disabled="!studio.workspaceId" @click="studio.create()"><Plus :size="14"/>Créer une stratégie</button><button class="icon-button" :disabled="studio.session.loading" aria-label="Actualiser les stratégies" @click="studio.refresh()"><RefreshCw :size="14"/></button></div><p class="ctx-library-caption">.zedflow/context</p><div class="ctx-library-list"><button v-for="file in studio.session.files" :key="file.key" class="ctx-file" :class="{chosen:studio.session.selected===file.key}" :data-context-key="file.key" :title="file.path" @click="studio.open(file)"><FileCode2 v-if="file.strategy" :size="15"/><AlertTriangle v-else :size="15"/><span>{{file.strategy?.name||file.key}}<small>{{file.strategy?(file.key==='workspace-default'?'Contexte du workspace · prêt à utiliser':file.key):'Format non éditable'}}</small></span><span v-if="studio.session.drafts[file.key]&&JSON.stringify(studio.session.drafts[file.key].strategy)!==studio.session.drafts[file.key].saved" class="ctx-unsaved" aria-label="Brouillon modifié">●</span></button><p v-if="!studio.session.files.length&&!studio.session.loading" class="ctx-hint">Créez une stratégie ou ouvrez un exemple depuis le guide du studio.</p><template v-if="drafts.length"><p class="ctx-library-caption">Brouillons</p><button v-for="([key,draft]) in drafts" :key="key" class="ctx-file" :class="{chosen:studio.session.selected===key}" @click="studio.select(key)"><FileCode2 :size="15"/><span>{{draft.strategy.name}}<small>Non enregistré</small></span></button></template></div><p v-if="studio.session.loading" role="status" class="ctx-hint">Chargement du catalogue…</p><p v-if="studio.session.error" role="alert" class="ctx-error">{{studio.session.error}}</p></div>
</template>
