<script setup lang="ts">
import { computed, ref } from 'vue'
import ContextBlockEditor from './ContextBlockEditor.vue'
import ContextPreviewDocument from './ContextPreviewDocument.vue'
import InferenceRaw from '../InferenceRaw.vue'
import CapturedToolDeclarations from './CapturedToolDeclarations.vue'
import AppDialog from '../AppDialog.vue'
const props=defineProps<{snapshot:Record<string,any>;expanded?:boolean}>()
const tab=ref('sources'),selected=ref(''),large=ref(false)
const program=computed(()=>props.snapshot.prepared?.program)
const blocks=computed(()=>JSON.parse(JSON.stringify(program.value?.strategy?.program||[])))
const items=computed(()=>props.snapshot.prepared?.consumedItems || (!props.snapshot.prepared?.window ? props.snapshot.prepared?.evaluation?.items : undefined))
const tabs=[{id:'sources',label:'Sources'},{id:'program',label:'Programme'},{id:'preview',label:'Aperçu'}]
</script>
<template><section class="projected-context" :class="{expanded}" aria-label="Contexte exécuté"><header><small>Invocation {{snapshot.invocationId}}</small><button v-if="!expanded" @click="large=true">Agrandir le contexte</button></header><nav v-if="!expanded" aria-label="Panneaux du contexte exécuté"><button v-for="item in tabs" :key="item.id" :aria-pressed="tab===item.id" @click="tab=item.id">{{item.label}}</button></nav><div class="projected-panels"><section v-if="expanded||tab==='sources'"><h3>Sources capturées</h3><details v-for="(source,index) in snapshot.resources||[]" :key="source.name||source.id||index"><summary>{{source.name||source.path||source.id}}</summary><pre>{{JSON.stringify(source.value??source.content,null,2)}}</pre><details><summary>Provenance</summary><pre>{{JSON.stringify(source.provenance||{},null,2)}}</pre></details></details><h4>Skills présentés</h4><details v-for="skill in snapshot.skillCatalog||[]" :key="skill.activationKey||skill.path"><summary>{{skill.name}}</summary><pre>{{JSON.stringify(skill,null,2)}}</pre></details><h4>Outils exposés</h4><p>{{(snapshot.tools||[]).join(', ')||'Aucun outil'}}</p><CapturedToolDeclarations :invocation="snapshot.invocationId" :revision="[snapshot.requestRef,snapshot.rawRef,snapshot.requestStatus].join('/')"/></section><section v-if="expanded||tab==='program'"><h3>Programme figé</h3><p>{{program?.strategy?.name}} · {{program?.hash}}</p><fieldset disabled @dragstart.prevent @drop.prevent><ContextBlockEditor :model-value="blocks" :version="program?.strategy?.version||2" :resources="program?.strategy?.requirements||{}" :types="program?.types||{}" :selected="selected" :trace="snapshot.prepared?.evaluation?.trace||[]"/></fieldset></section><section v-if="expanded||tab==='preview'"><h3>Fenêtre consommée</h3><small v-if="snapshot.prepared?.window">Révision {{snapshot.prepared.window.revision}}</small><ContextPreviewDocument v-if="items" :items="items" :requirements="program?.strategy?.requirements||{}" :trace="snapshot.prepared?.evaluation?.trace||[]" :selected="selected" @select="selected=$event;tab='program'"/><p v-else>Aucune projection finale capturée pour cette invocation. La requête ADK reste accessible si le modèle a été appelé.</p></section></div><InferenceRaw :invocation="snapshot.invocationId" :revision="[snapshot.requestRef,snapshot.rawRef,snapshot.requestStatus].join('/')"/><AppDialog v-if="!expanded" v-model:open="large" title="Contexte exécuté — Sources, Programme, Aperçu" wide><ProjectedContext v-if="large" :snapshot="snapshot" expanded/></AppDialog></section></template>
<style scoped>.projected-context{min-width:0;font-size:12px}.projected-context header{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap}.projected-context nav{display:flex;gap:5px;margin:14px 0}.projected-context nav button{flex:1}.projected-context nav [aria-pressed=true]{background:#343945}.projected-panels{min-width:0}.expanded .projected-panels{display:grid;grid-template-columns:1fr 1.5fr 1fr;gap:16px}.projected-panels section{min-width:0;max-height:65vh;overflow:auto;padding:8px}.projected-context fieldset{border:0;padding:0;min-width:0}.projected-context pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.projected-context small{color:#a7a9b1;overflow-wrap:anywhere}.projected-context details{margin:12px 0}.projected-context :deep(.ctx-wrap){display:none}@media(max-width:900px){.expanded .projected-panels{grid-template-columns:1fr}}</style>
