//! Shared OpenAI Responses helpers ported from Pi.

use std::collections::{HashMap, HashSet};
use std::error::Error as StdError;
use std::fmt;

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

/// Result type for OpenAI Responses shared helpers.
pub type Result<T> = std::result::Result<T, OpenAIResponsesSharedError>;

/// Errors returned by OpenAI Responses shared helpers.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum OpenAIResponsesSharedError {
    /// The upstream stream emitted an error event.
    StreamError { code: String, message: String },
    /// The upstream response failed.
    ResponseFailed { message: String },
    /// The stream ended before a terminal response event.
    MissingTerminalEvent,
    /// A response status was not known to this port.
    UnhandledStopReason { status: String },
}

impl fmt::Display for OpenAIResponsesSharedError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::StreamError { code, message } => write!(f, "Error Code {code}: {message}"),
            Self::ResponseFailed { message } => f.write_str(message),
            Self::MissingTerminalEvent => {
                f.write_str("OpenAI Responses stream ended before a terminal response event")
            }
            Self::UnhandledStopReason { status } => write!(f, "Unhandled stop reason: {status}"),
        }
    }
}

impl StdError for OpenAIResponsesSharedError {}

/// OpenAI Responses request input represented as JSON API items.
pub type ResponseInput = Vec<Value>;

/// OpenAI Responses function tool represented as JSON.
pub type OpenAITool = Value;

/// Provider/API identifier.
pub type Api = String;

/// OpenAI service tier value.
pub type ServiceTier = String;

/// Cost table in dollars per million tokens.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct ModelCost {
    /// Input token cost.
    pub input: f64,
    /// Output token cost.
    pub output: f64,
    /// Cache-read token cost.
    pub cache_read: f64,
    /// Cache-write token cost.
    pub cache_write: f64,
}

/// Compatibility switches used by Pi's OpenAI Responses conversion.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct OpenAIResponsesCompat {
    /// Whether the model supports the `developer` role instead of `system`.
    pub supports_developer_role: Option<bool>,
}

/// Minimal model shape consumed by this shared port.
#[derive(Debug, Clone, PartialEq)]
pub struct Model {
    /// Model identifier.
    pub id: String,
    /// API identifier.
    pub api: Api,
    /// Provider identifier.
    pub provider: String,
    /// Whether the model uses reasoning.
    pub reasoning: bool,
    /// Supported input modalities such as `text` and `image`.
    pub input: Vec<String>,
    /// Token pricing table.
    pub cost: ModelCost,
    /// OpenAI Responses compatibility flags.
    pub compat: Option<OpenAIResponsesCompat>,
}

/// Conversation context consumed by OpenAI Responses conversion.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Context {
    /// Optional system prompt.
    pub system_prompt: Option<String>,
    /// Conversation messages.
    pub messages: Vec<Message>,
}

/// Tool definition passed to OpenAI Responses.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Tool {
    /// Tool name.
    pub name: String,
    /// Tool description.
    pub description: String,
    /// JSON Schema parameters generated by Pi's TypeBox schema.
    pub parameters: Value,
}

/// Options for [`convert_responses_messages`].
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ConvertResponsesMessagesOptions {
    /// Include the context system prompt when true. Defaults to true.
    pub include_system_prompt: Option<bool>,
}

/// Options for [`convert_responses_tools`].
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ConvertResponsesToolsOptions {
    /// OpenAI strict function-schema flag. Defaults to false.
    pub strict: Option<bool>,
}

/// Service-tier resolver used while finalizing a response stream.
pub type ServiceTierResolver = fn(Option<&str>, Option<&str>) -> Option<ServiceTier>;

/// Options used when finalizing an OpenAI Responses stream.
#[derive(Clone, Default)]
pub struct OpenAIResponsesStreamOptions {
    /// Requested service tier.
    pub service_tier: Option<ServiceTier>,
    /// Resolves the response/request service tier used for pricing.
    pub resolve_service_tier: Option<ServiceTierResolver>,
    /// Applies service-tier-specific pricing to usage.
    pub apply_service_tier_pricing: Option<fn(&mut Usage, Option<&str>)>,
}

/// Text signature phase preserved for OpenAI Responses replay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TextSignaturePhase {
    /// Commentary-channel text.
    Commentary,
    /// Final answer text.
    FinalAnswer,
}

impl TextSignaturePhase {
    fn as_str(self) -> &'static str {
        match self {
            Self::Commentary => "commentary",
            Self::FinalAnswer => "final_answer",
        }
    }
}

/// Pi text-signature metadata version 1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextSignatureV1 {
    /// Signature version.
    pub v: u8,
    /// OpenAI message identifier.
    pub id: String,
    /// Optional text phase.
    pub phase: Option<TextSignaturePhase>,
}

/// Text content block.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TextContent {
    /// Text body.
    pub text: String,
    /// Optional OpenAI Responses text signature.
    pub text_signature: Option<String>,
}

/// Thinking content block.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ThinkingContent {
    /// Thinking text.
    pub thinking: String,
    /// Optional provider reasoning signature.
    pub thinking_signature: Option<String>,
    /// Whether the thinking text was redacted.
    pub redacted: bool,
}

/// Image content block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImageContent {
    /// Base64-encoded image data.
    pub data: String,
    /// MIME type such as `image/png`.
    pub mime_type: String,
}

/// Tool call content block.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Provider tool-call identifier.
    pub id: String,
    /// Tool name.
    pub name: String,
    /// Parsed tool arguments.
    pub arguments: Value,
    /// Optional provider thought signature.
    pub thought_signature: Option<String>,
}

/// Assistant content block.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum AssistantContent {
    /// Text block.
    Text(TextContent),
    /// Thinking block.
    Thinking(ThinkingContent),
    /// Tool-call block.
    ToolCall(ToolCall),
}

/// User content payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UserContent {
    /// Plain text content.
    Text(String),
    /// Rich text/image content parts.
    Parts(Vec<InputContent>),
}

/// User or tool-result input part.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum InputContent {
    /// Text part.
    Text(TextContent),
    /// Image part.
    Image(ImageContent),
}

/// User message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserMessage {
    /// User content.
    pub content: UserContent,
}

/// Assistant message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessage {
    /// Assistant content blocks.
    pub content: Vec<AssistantContent>,
    /// API identifier.
    pub api: Api,
    /// Provider identifier.
    pub provider: String,
    /// Model identifier.
    pub model: String,
    /// Provider response identifier.
    pub response_id: Option<String>,
    /// Token usage.
    pub usage: Usage,
    /// Stop reason.
    pub stop_reason: StopReason,
}

/// Tool-result message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolResultMessage {
    /// Tool-call id being answered.
    pub tool_call_id: String,
    /// Tool name.
    pub tool_name: String,
    /// Result content parts.
    pub content: Vec<InputContent>,
    /// Whether the tool returned an error.
    pub is_error: bool,
}

/// Conversation message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "camelCase")]
pub enum Message {
    /// User message.
    User(UserMessage),
    /// Assistant message.
    Assistant(AssistantMessage),
    /// Tool-result message.
    ToolResult(ToolResultMessage),
}

/// Token usage and calculated cost.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Usage {
    /// Non-cached input tokens.
    pub input: u64,
    /// Output tokens.
    pub output: u64,
    /// Cache-read tokens.
    pub cache_read: u64,
    /// Cache-write tokens.
    pub cache_write: u64,
    /// Cache-write tokens retained for one hour.
    pub cache_write_1h: Option<u64>,
    /// Reasoning tokens, if reported.
    pub reasoning: Option<u64>,
    /// Total provider-reported tokens.
    pub total_tokens: u64,
    /// Calculated cost.
    pub cost: UsageCost,
}

/// Calculated usage cost.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageCost {
    /// Input cost.
    pub input: f64,
    /// Output cost.
    pub output: f64,
    /// Cache-read cost.
    pub cache_read: f64,
    /// Cache-write cost.
    pub cache_write: f64,
    /// Total cost.
    pub total: f64,
}

/// Assistant stop reason.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Default)]
pub enum StopReason {
    /// Normal stop.
    #[default]
    Stop,
    /// Output length limit.
    Length,
    /// Tool use requested.
    ToolUse,
    /// Provider/runtime error.
    Error,
    /// Aborted request.
    Aborted,
}

/// Stream events emitted while processing an assistant message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AssistantMessageEvent {
    /// Thinking block started.
    ThinkingStart {
        /// Content index.
        content_index: usize,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Thinking text delta.
    ThinkingDelta {
        /// Content index.
        content_index: usize,
        /// Text delta.
        delta: String,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Thinking block ended.
    ThinkingEnd {
        /// Content index.
        content_index: usize,
        /// Final thinking text.
        content: String,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Text block started.
    TextStart {
        /// Content index.
        content_index: usize,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Text delta.
    TextDelta {
        /// Content index.
        content_index: usize,
        /// Text delta.
        delta: String,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Text block ended.
    TextEnd {
        /// Content index.
        content_index: usize,
        /// Final text.
        content: String,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Tool-call block started.
    ToolCallStart {
        /// Content index.
        content_index: usize,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Tool-call arguments delta.
    ToolCallDelta {
        /// Content index.
        content_index: usize,
        /// JSON delta.
        delta: String,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
    /// Tool-call block ended.
    ToolCallEnd {
        /// Content index.
        content_index: usize,
        /// Final tool call.
        tool_call: ToolCall,
        /// Partial assistant message.
        partial: AssistantMessage,
    },
}

/// In-memory assistant message event stream used by this port.
pub type AssistantMessageEventStream = Vec<AssistantMessageEvent>;

/// OpenAI response status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResponseStatus {
    /// Completed response.
    Completed,
    /// Incomplete response.
    Incomplete,
    /// Failed response.
    Failed,
    /// Cancelled response.
    Cancelled,
    /// In-progress response.
    InProgress,
    /// Queued response.
    Queued,
}

/// Usage details for input tokens.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputTokensDetails {
    /// Cached input tokens.
    pub cached_tokens: u64,
}

/// Usage details for output tokens.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputTokensDetails {
    /// Reasoning output tokens.
    pub reasoning_tokens: u64,
}

/// OpenAI Responses usage payload.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResponseUsage {
    /// Input tokens including cached tokens.
    pub input_tokens: u64,
    /// Output tokens.
    pub output_tokens: u64,
    /// Total tokens.
    pub total_tokens: u64,
    /// Input token details.
    pub input_tokens_details: Option<InputTokensDetails>,
    /// Output token details.
    pub output_tokens_details: Option<OutputTokensDetails>,
}

/// OpenAI error payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResponseError {
    /// Error code.
    pub code: Option<String>,
    /// Error message.
    pub message: Option<String>,
}

/// OpenAI incomplete details payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IncompleteDetails {
    /// Incomplete reason.
    pub reason: Option<String>,
}

/// OpenAI response object fields used by this port.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Response {
    /// Response identifier.
    pub id: Option<String>,
    /// Response usage.
    pub usage: Option<ResponseUsage>,
    /// Response status.
    pub status: Option<ResponseStatus>,
    /// Service tier returned by the provider.
    pub service_tier: Option<ServiceTier>,
    /// Error details for failed responses.
    pub error: Option<ResponseError>,
    /// Incomplete details for failed responses.
    pub incomplete_details: Option<IncompleteDetails>,
}

/// Output text/refusal item content.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResponseMessageContent {
    /// Content type, usually `output_text` or refusal.
    pub r#type: String,
    /// Output text.
    pub text: Option<String>,
    /// Refusal text.
    pub refusal: Option<String>,
}

/// Reasoning summary/content text item.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReasoningTextPart {
    /// Text value.
    pub text: String,
}

/// OpenAI Responses output item.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ResponseOutputItem {
    /// Reasoning item.
    Reasoning {
        /// Summary text parts.
        summary: Vec<ReasoningTextPart>,
        /// Content text parts.
        content: Vec<ReasoningTextPart>,
        /// Original item as JSON for replay signature.
        raw: Value,
    },
    /// Message item.
    Message {
        /// Message identifier.
        id: String,
        /// Optional text phase.
        phase: Option<TextSignaturePhase>,
        /// Message content.
        content: Vec<ResponseMessageContent>,
    },
    /// Function-call item.
    FunctionCall {
        /// Function-call item id.
        id: Option<String>,
        /// Function-call id.
        call_id: String,
        /// Function name.
        name: String,
        /// Raw JSON arguments.
        arguments: String,
    },
    /// Unsupported item shape preserved as JSON.
    Other {
        /// Original item type.
        item_type: String,
        /// Original item as JSON.
        raw: Value,
    },
}

/// OpenAI Responses stream event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ResponseStreamEvent {
    /// Response was created.
    ResponseCreated {
        /// Response payload.
        response: Response,
    },
    /// Output item was added.
    ResponseOutputItemAdded {
        /// Output index.
        output_index: usize,
        /// Output item.
        item: ResponseOutputItem,
    },
    /// Reasoning summary delta.
    ResponseReasoningSummaryTextDelta {
        /// Output index.
        output_index: usize,
        /// Text delta.
        delta: String,
    },
    /// Reasoning summary part done.
    ResponseReasoningSummaryPartDone {
        /// Output index.
        output_index: usize,
    },
    /// Reasoning text delta.
    ResponseReasoningTextDelta {
        /// Output index.
        output_index: usize,
        /// Text delta.
        delta: String,
    },
    /// Output text delta.
    ResponseOutputTextDelta {
        /// Output index.
        output_index: usize,
        /// Text delta.
        delta: String,
    },
    /// Refusal text delta.
    ResponseRefusalDelta {
        /// Output index.
        output_index: usize,
        /// Text delta.
        delta: String,
    },
    /// Function-call arguments delta.
    ResponseFunctionCallArgumentsDelta {
        /// Output index.
        output_index: usize,
        /// JSON delta.
        delta: String,
    },
    /// Function-call arguments completed.
    ResponseFunctionCallArgumentsDone {
        /// Output index.
        output_index: usize,
        /// Final JSON arguments.
        arguments: String,
    },
    /// Output item completed.
    ResponseOutputItemDone {
        /// Output index.
        output_index: usize,
        /// Final item.
        item: ResponseOutputItem,
    },
    /// Response completed.
    ResponseCompleted {
        /// Response payload.
        response: Response,
    },
    /// Response incomplete.
    ResponseIncomplete {
        /// Response payload.
        response: Response,
    },
    /// Stream error.
    Error {
        /// Error code.
        code: String,
        /// Error message.
        message: String,
    },
    /// Response failed.
    ResponseFailed {
        /// Failed response payload.
        response: Option<Response>,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SlotKind {
    Thinking,
    Text,
    ToolCall,
}

#[derive(Debug, Clone, Copy)]
struct ResponsesOutputSlot {
    kind: SlotKind,
    content_index: usize,
}

#[derive(Debug, Clone)]
struct StreamingToolCall {
    tool_call: ToolCall,
    partial_json: String,
}

fn sanitize_surrogates(text: &str) -> String {
    text.to_owned()
}

fn encode_text_signature_v1(id: &str, phase: Option<TextSignaturePhase>) -> String {
    let mut payload = json!({ "v": 1, "id": id });
    if let Some(phase) = phase {
        payload["phase"] = json!(phase.as_str());
    }
    payload.to_string()
}

fn parse_text_signature(signature: Option<&str>) -> Option<(String, Option<TextSignaturePhase>)> {
    let signature = signature?;
    if signature.starts_with('{')
        && let Ok(parsed) = serde_json::from_str::<TextSignatureV1>(signature)
        && parsed.v == 1
    {
        return Some((parsed.id, parsed.phase));
    }
    Some((signature.to_owned(), None))
}

fn short_hash(str_value: &str) -> String {
    let mut h1 = 0xdead_beefu32;
    let mut h2 = 0x41c6_ce57u32;
    for ch in str_value.encode_utf16() {
        let ch = u32::from(ch);
        h1 = (h1 ^ ch).wrapping_mul(2_654_435_761);
        h2 = (h2 ^ ch).wrapping_mul(1_597_334_677);
    }
    h1 = (h1 ^ (h1 >> 16)).wrapping_mul(2_246_822_507)
        ^ (h2 ^ (h2 >> 13)).wrapping_mul(3_266_489_909);
    h2 = (h2 ^ (h2 >> 16)).wrapping_mul(2_246_822_507)
        ^ (h1 ^ (h1 >> 13)).wrapping_mul(3_266_489_909);
    format!("{}{}", to_base36(h2), to_base36(h1))
}

fn to_base36(mut value: u32) -> String {
    if value == 0 {
        return "0".to_owned();
    }
    let mut chars = Vec::new();
    while value > 0 {
        let digit = (value % 36) as u8;
        let ch = if digit < 10 {
            b'0' + digit
        } else {
            b'a' + (digit - 10)
        };
        chars.push(char::from(ch));
        value /= 36;
    }
    chars.iter().rev().collect()
}

fn normalize_id_part(part: &str) -> String {
    let sanitized: String = part
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
                ch
            } else {
                '_'
            }
        })
        .collect();
    let normalized = if sanitized.len() > 64 {
        sanitized[..64].to_owned()
    } else {
        sanitized
    };
    normalized.trim_end_matches('_').to_owned()
}

fn parse_streaming_json(partial_json: &str) -> Value {
    if partial_json.trim().is_empty() {
        return json!({});
    }
    serde_json::from_str(partial_json).unwrap_or_else(|_| json!({}))
}

fn calculate_cost(model: &Model, usage: &mut Usage) -> UsageCost {
    let long_write = usage.cache_write_1h.unwrap_or(0) as f64;
    let short_write = usage
        .cache_write
        .saturating_sub(usage.cache_write_1h.unwrap_or(0)) as f64;
    usage.cost.input = (model.cost.input / 1_000_000.0) * usage.input as f64;
    usage.cost.output = (model.cost.output / 1_000_000.0) * usage.output as f64;
    usage.cost.cache_read = (model.cost.cache_read / 1_000_000.0) * usage.cache_read as f64;
    usage.cost.cache_write =
        (model.cost.cache_write * short_write + model.cost.input * 2.0 * long_write) / 1_000_000.0;
    usage.cost.total =
        usage.cost.input + usage.cost.output + usage.cost.cache_read + usage.cost.cache_write;
    usage.cost
}

fn has_image_input(model: &Model) -> bool {
    model.input.iter().any(|input| input == "image")
}

fn replace_images_with_placeholder(
    content: &[InputContent],
    placeholder: &str,
) -> Vec<InputContent> {
    let mut result = Vec::new();
    let mut previous_was_placeholder = false;
    for block in content {
        match block {
            InputContent::Image(_) => {
                if !previous_was_placeholder {
                    result.push(InputContent::Text(TextContent {
                        text: placeholder.to_owned(),
                        text_signature: None,
                    }));
                }
                previous_was_placeholder = true;
            }
            InputContent::Text(text) => {
                result.push(InputContent::Text(text.clone()));
                previous_was_placeholder = text.text == placeholder;
            }
        }
    }
    result
}

fn transform_messages(
    messages: &[Message],
    model: &Model,
    allowed_tool_call_providers: &HashSet<String>,
) -> Vec<Message> {
    const NON_VISION_USER_IMAGE_PLACEHOLDER: &str =
        "(image omitted: model does not support images)";
    const NON_VISION_TOOL_IMAGE_PLACEHOLDER: &str =
        "(tool image omitted: model does not support images)";

    let mut transformed = Vec::with_capacity(messages.len());
    let mut tool_call_id_map: HashMap<String, String> = HashMap::new();
    let allow_provider_ids = allowed_tool_call_providers.contains(&model.provider);

    for msg in messages {
        match msg {
            Message::User(user) => {
                let mut user = user.clone();
                if !has_image_input(model)
                    && let UserContent::Parts(parts) = &user.content
                {
                    user.content = UserContent::Parts(replace_images_with_placeholder(
                        parts,
                        NON_VISION_USER_IMAGE_PLACEHOLDER,
                    ));
                }
                transformed.push(Message::User(user));
            }
            Message::ToolResult(tool_result) => {
                let mut tool_result = tool_result.clone();
                if let Some(id) = tool_call_id_map.get(&tool_result.tool_call_id) {
                    tool_result.tool_call_id.clone_from(id);
                }
                if !has_image_input(model) {
                    tool_result.content = replace_images_with_placeholder(
                        &tool_result.content,
                        NON_VISION_TOOL_IMAGE_PLACEHOLDER,
                    );
                }
                transformed.push(Message::ToolResult(tool_result));
            }
            Message::Assistant(assistant) => {
                if matches!(
                    assistant.stop_reason,
                    StopReason::Error | StopReason::Aborted
                ) {
                    continue;
                }
                let is_same_model = assistant.provider == model.provider
                    && assistant.api == model.api
                    && assistant.model == model.id;
                let mut assistant = assistant.clone();
                let source = assistant.clone();
                assistant.content = assistant
                    .content
                    .into_iter()
                    .filter_map(|block| match block {
                        AssistantContent::Thinking(thinking) => {
                            if thinking.redacted {
                                return is_same_model
                                    .then_some(AssistantContent::Thinking(thinking));
                            }
                            if is_same_model && thinking.thinking_signature.is_some() {
                                return Some(AssistantContent::Thinking(thinking));
                            }
                            if thinking.thinking.trim().is_empty() {
                                return None;
                            }
                            if is_same_model {
                                Some(AssistantContent::Thinking(thinking))
                            } else {
                                Some(AssistantContent::Text(TextContent {
                                    text: thinking.thinking,
                                    text_signature: None,
                                }))
                            }
                        }
                        AssistantContent::Text(mut text) => {
                            if !is_same_model {
                                text.text_signature = None;
                            }
                            Some(AssistantContent::Text(text))
                        }
                        AssistantContent::ToolCall(mut tool_call) => {
                            if !is_same_model {
                                tool_call.thought_signature = None;
                                let normalized = normalize_tool_call_id(
                                    &tool_call.id,
                                    model,
                                    &source,
                                    allow_provider_ids,
                                );
                                if normalized != tool_call.id {
                                    tool_call_id_map
                                        .insert(tool_call.id.clone(), normalized.clone());
                                    tool_call.id = normalized;
                                }
                            }
                            Some(AssistantContent::ToolCall(tool_call))
                        }
                    })
                    .collect();
                transformed.push(Message::Assistant(assistant));
            }
        }
    }

    insert_synthetic_tool_results(transformed)
}

fn normalize_tool_call_id(
    id: &str,
    model: &Model,
    source: &AssistantMessage,
    allow_provider_ids: bool,
) -> String {
    if !allow_provider_ids {
        return normalize_id_part(id);
    }
    let Some((call_id, item_id)) = id.split_once('|') else {
        return normalize_id_part(id);
    };
    let normalized_call_id = normalize_id_part(call_id);
    let is_foreign_tool_call = source.provider != model.provider || source.api != model.api;
    let mut normalized_item_id = if is_foreign_tool_call {
        let normalized = format!("fc_{}", short_hash(item_id));
        if normalized.len() > 64 {
            normalized[..64].to_owned()
        } else {
            normalized
        }
    } else {
        normalize_id_part(item_id)
    };
    if !normalized_item_id.starts_with("fc_") {
        normalized_item_id = normalize_id_part(&format!("fc_{normalized_item_id}"));
    }
    format!("{normalized_call_id}|{normalized_item_id}")
}

fn insert_synthetic_tool_results(messages: Vec<Message>) -> Vec<Message> {
    let mut result = Vec::with_capacity(messages.len());
    let mut pending_tool_calls: Vec<ToolCall> = Vec::new();
    let mut existing_tool_result_ids: HashSet<String> = HashSet::new();

    fn insert_pending(
        result: &mut Vec<Message>,
        pending_tool_calls: &mut Vec<ToolCall>,
        existing_tool_result_ids: &mut HashSet<String>,
    ) {
        for tool_call in pending_tool_calls.drain(..) {
            if !existing_tool_result_ids.contains(&tool_call.id) {
                result.push(Message::ToolResult(ToolResultMessage {
                    tool_call_id: tool_call.id,
                    tool_name: tool_call.name,
                    content: vec![InputContent::Text(TextContent {
                        text: "No result provided".to_owned(),
                        text_signature: None,
                    })],
                    is_error: true,
                }));
            }
        }
        existing_tool_result_ids.clear();
    }

    for msg in messages {
        match &msg {
            Message::Assistant(assistant) => {
                insert_pending(
                    &mut result,
                    &mut pending_tool_calls,
                    &mut existing_tool_result_ids,
                );
                pending_tool_calls = assistant
                    .content
                    .iter()
                    .filter_map(|block| match block {
                        AssistantContent::ToolCall(tool_call) => Some(tool_call.clone()),
                        _ => None,
                    })
                    .collect();
                result.push(msg);
            }
            Message::ToolResult(tool_result) => {
                existing_tool_result_ids.insert(tool_result.tool_call_id.clone());
                result.push(msg);
            }
            Message::User(_) => {
                insert_pending(
                    &mut result,
                    &mut pending_tool_calls,
                    &mut existing_tool_result_ids,
                );
                result.push(msg);
            }
        }
    }
    insert_pending(
        &mut result,
        &mut pending_tool_calls,
        &mut existing_tool_result_ids,
    );
    result
}

/// Converts Pi messages into OpenAI Responses input items.
#[must_use]
pub fn convert_responses_messages(
    model: &Model,
    context: &Context,
    allowed_tool_call_providers: &HashSet<String>,
    options: Option<ConvertResponsesMessagesOptions>,
) -> ResponseInput {
    let mut messages = ResponseInput::new();
    let transformed_messages =
        transform_messages(&context.messages, model, allowed_tool_call_providers);

    let include_system_prompt = options
        .and_then(|options| options.include_system_prompt)
        .unwrap_or(true);
    if include_system_prompt && let Some(system_prompt) = &context.system_prompt {
        let supports_developer_role = model
            .compat
            .as_ref()
            .and_then(|compat| compat.supports_developer_role)
            .unwrap_or(true);
        let role = if model.reasoning && supports_developer_role {
            "developer"
        } else {
            "system"
        };
        messages.push(json!({ "role": role, "content": sanitize_surrogates(system_prompt) }));
    }

    for (msg_index, msg) in transformed_messages.iter().enumerate() {
        match msg {
            Message::User(user) => match &user.content {
                UserContent::Text(text) => messages.push(json!({
                    "role": "user",
                    "content": [{ "type": "input_text", "text": sanitize_surrogates(text) }]
                })),
                UserContent::Parts(parts) => {
                    let content: Vec<Value> = parts
                        .iter()
                        .map(|item| match item {
                            InputContent::Text(text) => json!({
                                "type": "input_text",
                                "text": sanitize_surrogates(&text.text)
                            }),
                            InputContent::Image(image) => json!({
                                "type": "input_image",
                                "detail": "auto",
                                "image_url": format!("data:{};base64,{}", image.mime_type, image.data)
                            }),
                        })
                        .collect();
                    if !content.is_empty() {
                        messages.push(json!({ "role": "user", "content": content }));
                    }
                }
            },
            Message::Assistant(assistant) => {
                let output = convert_assistant_message(model, assistant, msg_index);
                messages.extend(output);
            }
            Message::ToolResult(tool_result) => {
                messages.push(convert_tool_result_message(model, tool_result));
            }
        }
    }

    messages
}

fn convert_assistant_message(
    model: &Model,
    assistant: &AssistantMessage,
    msg_index: usize,
) -> ResponseInput {
    let is_different_model = assistant.model != model.id
        && assistant.provider == model.provider
        && assistant.api == model.api;
    let mut output = ResponseInput::new();
    let mut text_block_index = 0usize;

    for block in &assistant.content {
        match block {
            AssistantContent::Thinking(thinking) => {
                if let Some(signature) = &thinking.thinking_signature
                    && let Ok(value) = serde_json::from_str(signature)
                {
                    output.push(value);
                }
            }
            AssistantContent::Text(text) => {
                let parsed_signature = parse_text_signature(text.text_signature.as_deref());
                let fallback_message_id = if text_block_index == 0 {
                    format!("msg_pi_{msg_index}")
                } else {
                    format!("msg_pi_{msg_index}_{text_block_index}")
                };
                text_block_index += 1;
                let (mut msg_id, phase) = parsed_signature.unwrap_or((fallback_message_id, None));
                if msg_id.len() > 64 {
                    msg_id = format!("msg_{}", short_hash(&msg_id));
                }
                let mut item = json!({
                    "type": "message",
                    "role": "assistant",
                    "content": [{ "type": "output_text", "text": sanitize_surrogates(&text.text), "annotations": [] }],
                    "status": "completed",
                    "id": msg_id,
                });
                if let Some(phase) = phase {
                    item["phase"] = json!(phase.as_str());
                }
                output.push(item);
            }
            AssistantContent::ToolCall(tool_call) => {
                let (call_id, mut item_id) = tool_call
                    .id
                    .split_once('|')
                    .map(|(call, item)| (call.to_owned(), Some(item.to_owned())))
                    .unwrap_or_else(|| (tool_call.id.clone(), None));
                if is_different_model && item_id.as_ref().is_some_and(|id| id.starts_with("fc_")) {
                    item_id = None;
                }
                let mut item = json!({
                    "type": "function_call",
                    "call_id": call_id,
                    "name": tool_call.name,
                    "arguments": tool_call.arguments.to_string(),
                });
                if let Some(item_id) = item_id {
                    item["id"] = json!(item_id);
                }
                output.push(item);
            }
        }
    }

    output
}

fn convert_tool_result_message(model: &Model, tool_result: &ToolResultMessage) -> Value {
    let text_result = tool_result
        .content
        .iter()
        .filter_map(|content| match content {
            InputContent::Text(text) => Some(text.text.as_str()),
            InputContent::Image(_) => None,
        })
        .collect::<Vec<_>>()
        .join("\n");
    let has_images = tool_result
        .content
        .iter()
        .any(|content| matches!(content, InputContent::Image(_)));
    let has_text = !text_result.is_empty();
    let call_id = tool_result
        .tool_call_id
        .split_once('|')
        .map(|(call_id, _)| call_id)
        .unwrap_or(&tool_result.tool_call_id);

    let output = if has_images && has_image_input(model) {
        let mut content_parts = Vec::new();
        if has_text {
            content_parts
                .push(json!({ "type": "input_text", "text": sanitize_surrogates(&text_result) }));
        }
        for block in &tool_result.content {
            if let InputContent::Image(image) = block {
                content_parts.push(json!({
                    "type": "input_image",
                    "detail": "auto",
                    "image_url": format!("data:{};base64,{}", image.mime_type, image.data)
                }));
            }
        }
        Value::Array(content_parts)
    } else {
        json!(sanitize_surrogates(if has_text {
            &text_result
        } else if has_images {
            "(see attached image)"
        } else {
            "(no tool output)"
        }))
    };

    json!({ "type": "function_call_output", "call_id": call_id, "output": output })
}

/// Converts Pi tools into OpenAI Responses function tools.
#[must_use]
pub fn convert_responses_tools(
    tools: &[Tool],
    options: Option<ConvertResponsesToolsOptions>,
) -> Vec<OpenAITool> {
    let strict = options.and_then(|options| options.strict).unwrap_or(false);
    tools
        .iter()
        .map(|tool| {
            json!({
                "type": "function",
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.parameters,
                "strict": strict,
            })
        })
        .collect()
}

/// Stateful single-pass processor for OpenAI Responses stream events.
///
/// Pi consumes its async iterable once while retaining output-slot and partial tool-call state.
/// This processor preserves that behavior for transports that decode SSE incrementally.
#[derive(Debug, Default)]
pub(crate) struct ResponsesStreamProcessor {
    saw_terminal_response_event: bool,
    output_slots: HashMap<usize, ResponsesOutputSlot>,
    streaming_tool_calls: HashMap<usize, StreamingToolCall>,
}

impl ResponsesStreamProcessor {
    /// Processes one provider event and returns whether a terminal response event was seen.
    pub(crate) fn push(
        &mut self,
        event: ResponseStreamEvent,
        output: &mut AssistantMessage,
        stream: &mut AssistantMessageEventStream,
        model: &Model,
        options: Option<&OpenAIResponsesStreamOptions>,
    ) -> Result<bool> {
        match event {
            ResponseStreamEvent::ResponseCreated { response } => {
                output.response_id = response.id;
            }
            ResponseStreamEvent::ResponseOutputItemAdded { output_index, item } => {
                create_slot(
                    output_index,
                    &item,
                    output,
                    stream,
                    &mut self.output_slots,
                    &mut self.streaming_tool_calls,
                );
            }
            ResponseStreamEvent::ResponseReasoningSummaryTextDelta {
                output_index,
                delta,
            }
            | ResponseStreamEvent::ResponseReasoningTextDelta {
                output_index,
                delta,
            } => {
                if let Some(slot) = get_slot(&self.output_slots, output_index, SlotKind::Thinking) {
                    append_thinking(output, slot.content_index, &delta);
                    stream.push(AssistantMessageEvent::ThinkingDelta {
                        content_index: slot.content_index,
                        delta,
                        partial: output.clone(),
                    });
                }
            }
            ResponseStreamEvent::ResponseReasoningSummaryPartDone { output_index } => {
                if let Some(slot) = get_slot(&self.output_slots, output_index, SlotKind::Thinking) {
                    append_thinking(output, slot.content_index, "\n\n");
                    stream.push(AssistantMessageEvent::ThinkingDelta {
                        content_index: slot.content_index,
                        delta: "\n\n".to_owned(),
                        partial: output.clone(),
                    });
                }
            }
            ResponseStreamEvent::ResponseOutputTextDelta {
                output_index,
                delta,
            }
            | ResponseStreamEvent::ResponseRefusalDelta {
                output_index,
                delta,
            } => {
                if let Some(slot) = get_slot(&self.output_slots, output_index, SlotKind::Text) {
                    append_text(output, slot.content_index, &delta);
                    stream.push(AssistantMessageEvent::TextDelta {
                        content_index: slot.content_index,
                        delta,
                        partial: output.clone(),
                    });
                }
            }
            ResponseStreamEvent::ResponseFunctionCallArgumentsDelta {
                output_index,
                delta,
            } => {
                if let Some(slot) = get_slot(&self.output_slots, output_index, SlotKind::ToolCall)
                    && let Some(call) = self.streaming_tool_calls.get_mut(&output_index)
                {
                    call.partial_json.push_str(&delta);
                    call.tool_call.arguments = parse_streaming_json(&call.partial_json);
                    set_tool_call(output, slot.content_index, call.tool_call.clone());
                    stream.push(AssistantMessageEvent::ToolCallDelta {
                        content_index: slot.content_index,
                        delta,
                        partial: output.clone(),
                    });
                }
            }
            ResponseStreamEvent::ResponseFunctionCallArgumentsDone {
                output_index,
                arguments,
            } => {
                if let Some(slot) = get_slot(&self.output_slots, output_index, SlotKind::ToolCall)
                    && let Some(call) = self.streaming_tool_calls.get_mut(&output_index)
                {
                    let previous_partial_json = call.partial_json.clone();
                    call.partial_json = arguments.clone();
                    call.tool_call.arguments = parse_streaming_json(&call.partial_json);
                    set_tool_call(output, slot.content_index, call.tool_call.clone());
                    if arguments.starts_with(&previous_partial_json) {
                        let delta = arguments[previous_partial_json.len()..].to_owned();
                        if !delta.is_empty() {
                            stream.push(AssistantMessageEvent::ToolCallDelta {
                                content_index: slot.content_index,
                                delta,
                                partial: output.clone(),
                            });
                        }
                    }
                }
            }
            ResponseStreamEvent::ResponseOutputItemDone { output_index, item } => {
                if !self.output_slots.contains_key(&output_index) {
                    create_slot(
                        output_index,
                        &item,
                        output,
                        stream,
                        &mut self.output_slots,
                        &mut self.streaming_tool_calls,
                    );
                }
                finalize_item(
                    output_index,
                    item,
                    output,
                    stream,
                    &mut self.output_slots,
                    &mut self.streaming_tool_calls,
                );
            }
            ResponseStreamEvent::ResponseCompleted { response }
            | ResponseStreamEvent::ResponseIncomplete { response } => {
                self.saw_terminal_response_event = true;
                finalize_response(response, output, model, options)?;
            }
            ResponseStreamEvent::Error { code, message } => {
                return Err(OpenAIResponsesSharedError::StreamError { code, message });
            }
            ResponseStreamEvent::ResponseFailed { response } => {
                return Err(OpenAIResponsesSharedError::ResponseFailed {
                    message: failed_response_message(response.as_ref()),
                });
            }
        }
        Ok(self.saw_terminal_response_event)
    }

    pub(crate) fn finish(&self) -> Result<()> {
        if self.saw_terminal_response_event {
            Ok(())
        } else {
            Err(OpenAIResponsesSharedError::MissingTerminalEvent)
        }
    }
}

/// Processes OpenAI Responses stream events into a Pi assistant message and event stream.
///
/// # Errors
///
/// Returns an error when the provider emits an error/failure event, an unknown response status is
/// encountered, or the event iterator ends before a terminal response event.
pub fn process_responses_stream<I>(
    openai_stream: I,
    output: &mut AssistantMessage,
    stream: &mut AssistantMessageEventStream,
    model: &Model,
    options: Option<&OpenAIResponsesStreamOptions>,
) -> Result<()>
where
    I: IntoIterator<Item = ResponseStreamEvent>,
{
    let mut processor = ResponsesStreamProcessor::default();
    for event in openai_stream {
        processor.push(event, output, stream, model, options)?;
    }
    processor.finish()
}

fn get_slot(
    output_slots: &HashMap<usize, ResponsesOutputSlot>,
    output_index: usize,
    kind: SlotKind,
) -> Option<ResponsesOutputSlot> {
    output_slots
        .get(&output_index)
        .copied()
        .filter(|slot| slot.kind == kind)
}

fn create_slot(
    output_index: usize,
    item: &ResponseOutputItem,
    output: &mut AssistantMessage,
    stream: &mut AssistantMessageEventStream,
    output_slots: &mut HashMap<usize, ResponsesOutputSlot>,
    streaming_tool_calls: &mut HashMap<usize, StreamingToolCall>,
) -> Option<ResponsesOutputSlot> {
    let (kind, content) = match item {
        ResponseOutputItem::Reasoning { .. } => (
            SlotKind::Thinking,
            AssistantContent::Thinking(ThinkingContent::default()),
        ),
        ResponseOutputItem::Message { .. } => (
            SlotKind::Text,
            AssistantContent::Text(TextContent::default()),
        ),
        ResponseOutputItem::FunctionCall {
            id,
            call_id,
            name,
            arguments,
        } => {
            let tool_call = ToolCall {
                id: format!("{}|{}", call_id, id.as_deref().unwrap_or_default()),
                name: name.clone(),
                arguments: json!({}),
                thought_signature: None,
            };
            streaming_tool_calls.insert(
                output_index,
                StreamingToolCall {
                    tool_call: tool_call.clone(),
                    partial_json: arguments.clone(),
                },
            );
            (SlotKind::ToolCall, AssistantContent::ToolCall(tool_call))
        }
        ResponseOutputItem::Other { .. } => return None,
    };
    output.content.push(content);
    let slot = ResponsesOutputSlot {
        kind,
        content_index: output.content.len() - 1,
    };
    output_slots.insert(output_index, slot);
    match kind {
        SlotKind::Thinking => stream.push(AssistantMessageEvent::ThinkingStart {
            content_index: slot.content_index,
            partial: output.clone(),
        }),
        SlotKind::Text => stream.push(AssistantMessageEvent::TextStart {
            content_index: slot.content_index,
            partial: output.clone(),
        }),
        SlotKind::ToolCall => stream.push(AssistantMessageEvent::ToolCallStart {
            content_index: slot.content_index,
            partial: output.clone(),
        }),
    }
    Some(slot)
}

fn append_thinking(output: &mut AssistantMessage, content_index: usize, delta: &str) {
    if let Some(AssistantContent::Thinking(block)) = output.content.get_mut(content_index) {
        block.thinking.push_str(delta);
    }
}

fn append_text(output: &mut AssistantMessage, content_index: usize, delta: &str) {
    if let Some(AssistantContent::Text(block)) = output.content.get_mut(content_index) {
        block.text.push_str(delta);
    }
}

fn set_tool_call(output: &mut AssistantMessage, content_index: usize, tool_call: ToolCall) {
    if let Some(AssistantContent::ToolCall(block)) = output.content.get_mut(content_index) {
        *block = tool_call;
    }
}

fn finalize_item(
    output_index: usize,
    item: ResponseOutputItem,
    output: &mut AssistantMessage,
    stream: &mut AssistantMessageEventStream,
    output_slots: &mut HashMap<usize, ResponsesOutputSlot>,
    streaming_tool_calls: &mut HashMap<usize, StreamingToolCall>,
) {
    let Some(slot) = output_slots.get(&output_index).copied() else {
        return;
    };
    match item {
        ResponseOutputItem::Reasoning {
            summary,
            content,
            raw,
        } if slot.kind == SlotKind::Thinking => {
            if let Some(AssistantContent::Thinking(block)) =
                output.content.get_mut(slot.content_index)
            {
                let summary_text = summary
                    .iter()
                    .map(|part| part.text.as_str())
                    .collect::<Vec<_>>()
                    .join("\n\n");
                let content_text = content
                    .iter()
                    .map(|part| part.text.as_str())
                    .collect::<Vec<_>>()
                    .join("\n\n");
                if !summary_text.is_empty() {
                    block.thinking = summary_text;
                } else if !content_text.is_empty() {
                    block.thinking = content_text;
                }
                block.thinking_signature = Some(raw.to_string());
                let content = block.thinking.clone();
                stream.push(AssistantMessageEvent::ThinkingEnd {
                    content_index: slot.content_index,
                    content,
                    partial: output.clone(),
                });
            }
            output_slots.remove(&output_index);
        }
        ResponseOutputItem::Message { id, phase, content } if slot.kind == SlotKind::Text => {
            if let Some(AssistantContent::Text(block)) = output.content.get_mut(slot.content_index)
            {
                block.text = content
                    .iter()
                    .map(|part| {
                        if part.r#type == "output_text" {
                            part.text.as_deref().unwrap_or_default()
                        } else {
                            part.refusal.as_deref().unwrap_or_default()
                        }
                    })
                    .collect::<String>();
                block.text_signature = Some(encode_text_signature_v1(&id, phase));
                let content = block.text.clone();
                stream.push(AssistantMessageEvent::TextEnd {
                    content_index: slot.content_index,
                    content,
                    partial: output.clone(),
                });
            }
            output_slots.remove(&output_index);
        }
        ResponseOutputItem::FunctionCall { arguments, .. } if slot.kind == SlotKind::ToolCall => {
            if let Some(mut call) = streaming_tool_calls.remove(&output_index) {
                let final_json = if arguments.is_empty() {
                    if call.partial_json.is_empty() {
                        "{}".to_owned()
                    } else {
                        call.partial_json
                    }
                } else {
                    arguments
                };
                call.tool_call.arguments = parse_streaming_json(&final_json);
                set_tool_call(output, slot.content_index, call.tool_call.clone());
                stream.push(AssistantMessageEvent::ToolCallEnd {
                    content_index: slot.content_index,
                    tool_call: call.tool_call,
                    partial: output.clone(),
                });
            }
            output_slots.remove(&output_index);
        }
        _ => {}
    }
}

fn finalize_response(
    response: Response,
    output: &mut AssistantMessage,
    model: &Model,
    options: Option<&OpenAIResponsesStreamOptions>,
) -> Result<()> {
    if response.id.is_some() {
        output.response_id = response.id;
    }
    if let Some(usage) = response.usage {
        let cached_tokens = usage
            .input_tokens_details
            .map(|details| details.cached_tokens)
            .unwrap_or(0);
        output.usage = Usage {
            input: usage.input_tokens.saturating_sub(cached_tokens),
            output: usage.output_tokens,
            cache_read: cached_tokens,
            cache_write: 0,
            cache_write_1h: None,
            reasoning: Some(
                usage
                    .output_tokens_details
                    .map(|details| details.reasoning_tokens)
                    .unwrap_or(0),
            ),
            total_tokens: usage.total_tokens,
            cost: UsageCost::default(),
        };
    }
    calculate_cost(model, &mut output.usage);
    if let Some(options) = options
        && let Some(apply) = options.apply_service_tier_pricing
    {
        let tier = if let Some(resolve) = options.resolve_service_tier {
            resolve(
                response.service_tier.as_deref(),
                options.service_tier.as_deref(),
            )
        } else {
            response
                .service_tier
                .or_else(|| options.service_tier.clone())
        };
        apply(&mut output.usage, tier.as_deref());
    }
    output.stop_reason = map_stop_reason(response.status)?;
    if output
        .content
        .iter()
        .any(|block| matches!(block, AssistantContent::ToolCall(_)))
        && output.stop_reason == StopReason::Stop
    {
        output.stop_reason = StopReason::ToolUse;
    }
    Ok(())
}

fn failed_response_message(response: Option<&Response>) -> String {
    if let Some(error) = response.and_then(|response| response.error.as_ref()) {
        return format!(
            "{}: {}",
            error.code.as_deref().unwrap_or("unknown"),
            error.message.as_deref().unwrap_or("no message")
        );
    }
    if let Some(reason) = response
        .and_then(|response| response.incomplete_details.as_ref())
        .and_then(|details| details.reason.as_ref())
    {
        return format!("incomplete: {reason}");
    }
    "Unknown error (no error details in response)".to_owned()
}

fn map_stop_reason(status: Option<ResponseStatus>) -> Result<StopReason> {
    let Some(status) = status else {
        return Ok(StopReason::Stop);
    };
    match status {
        ResponseStatus::Completed | ResponseStatus::InProgress | ResponseStatus::Queued => {
            Ok(StopReason::Stop)
        }
        ResponseStatus::Incomplete => Ok(StopReason::Length),
        ResponseStatus::Failed | ResponseStatus::Cancelled => Ok(StopReason::Error),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model() -> Model {
        Model {
            id: "gpt".to_owned(),
            api: "openai-responses".to_owned(),
            provider: "openai".to_owned(),
            reasoning: true,
            input: vec!["text".to_owned(), "image".to_owned()],
            cost: ModelCost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.5,
                cache_write: 1.5,
            },
            compat: Some(OpenAIResponsesCompat {
                supports_developer_role: Some(true),
            }),
        }
    }

    #[test]
    fn converts_system_and_tool() {
        let response = convert_responses_messages(
            &model(),
            &Context {
                system_prompt: Some("sys".to_owned()),
                messages: vec![Message::ToolResult(ToolResultMessage {
                    tool_call_id: "call|fc_item".to_owned(),
                    tool_name: "tool".to_owned(),
                    content: vec![InputContent::Text(TextContent {
                        text: "ok".to_owned(),
                        text_signature: None,
                    })],
                    is_error: false,
                })],
            },
            &HashSet::new(),
            None,
        );

        assert_eq!(response[0]["role"], "developer");
        assert_eq!(response[1]["type"], "function_call_output");
        assert_eq!(response[1]["call_id"], "call");
    }

    #[test]
    fn incremental_processor_matches_single_pass_pi_event_processing() {
        let model = model();
        let response_item = ResponseOutputItem::Message {
            id: "msg_1".to_owned(),
            phase: None,
            content: Vec::new(),
        };
        let events = vec![
            ResponseStreamEvent::ResponseOutputItemAdded {
                output_index: 0,
                item: response_item,
            },
            ResponseStreamEvent::ResponseOutputTextDelta {
                output_index: 0,
                delta: "hello ".to_owned(),
            },
            ResponseStreamEvent::ResponseOutputTextDelta {
                output_index: 0,
                delta: "world".to_owned(),
            },
            ResponseStreamEvent::ResponseOutputItemDone {
                output_index: 0,
                item: ResponseOutputItem::Message {
                    id: "msg_1".to_owned(),
                    phase: None,
                    content: vec![ResponseMessageContent {
                        r#type: "output_text".to_owned(),
                        text: Some("hello world".to_owned()),
                        refusal: None,
                    }],
                },
            },
            ResponseStreamEvent::ResponseCompleted {
                response: Response {
                    id: Some("resp_1".to_owned()),
                    status: Some(ResponseStatus::Completed),
                    ..Response::default()
                },
            },
        ];
        let empty_output = || AssistantMessage {
            content: Vec::new(),
            api: model.api.clone(),
            provider: model.provider.clone(),
            model: model.id.clone(),
            response_id: None,
            usage: Usage::default(),
            stop_reason: StopReason::Stop,
        };

        let mut batch_output = empty_output();
        let mut batch_events = Vec::new();
        process_responses_stream(
            events.clone(),
            &mut batch_output,
            &mut batch_events,
            &model,
            None,
        )
        .expect("batch stream should finalize");

        let mut incremental_output = empty_output();
        let mut incremental_events = Vec::new();
        let mut processor = ResponsesStreamProcessor::default();
        for (index, event) in events.into_iter().enumerate() {
            let mut emitted = Vec::new();
            let terminal = processor
                .push(event, &mut incremental_output, &mut emitted, &model, None)
                .expect("incremental event should process");
            assert_eq!(terminal, index == 4);
            incremental_events.extend(emitted);
        }

        assert_eq!(incremental_output, batch_output);
        assert_eq!(incremental_events, batch_events);
    }

    #[test]
    fn removes_partial_json_from_persisted_tool_call_blocks_at_output_item_done() {
        let mut model = model();
        model.id = "gpt-5-mini".to_owned();
        let mut output = AssistantMessage {
            content: Vec::new(),
            api: model.api.clone(),
            provider: model.provider.clone(),
            model: model.id.clone(),
            response_id: None,
            usage: Usage::default(),
            stop_reason: StopReason::Stop,
        };
        let mut events = Vec::new();
        let arguments_json = "{\"path\":\"README.md\",\"content\":\"updated\"}";

        process_responses_stream(
            vec![
                ResponseStreamEvent::ResponseOutputItemAdded {
                    output_index: 0,
                    item: ResponseOutputItem::FunctionCall {
                        id: Some("fc_test".to_owned()),
                        call_id: "call_test".to_owned(),
                        name: "edit".to_owned(),
                        arguments: "".to_owned(),
                    },
                },
                ResponseStreamEvent::ResponseFunctionCallArgumentsDelta {
                    output_index: 0,
                    delta: "{\"path\":\"README.md\"".to_owned(),
                },
                ResponseStreamEvent::ResponseFunctionCallArgumentsDelta {
                    output_index: 0,
                    delta: ",\"content\":\"updated\"}".to_owned(),
                },
                ResponseStreamEvent::ResponseFunctionCallArgumentsDone {
                    output_index: 0,
                    arguments: arguments_json.to_owned(),
                },
                ResponseStreamEvent::ResponseOutputItemDone {
                    output_index: 0,
                    item: ResponseOutputItem::FunctionCall {
                        id: Some("fc_test".to_owned()),
                        call_id: "call_test".to_owned(),
                        name: "edit".to_owned(),
                        arguments: arguments_json.to_owned(),
                    },
                },
                ResponseStreamEvent::ResponseCompleted {
                    response: Response {
                        id: Some("resp_test".to_owned()),
                        status: Some(ResponseStatus::Completed),
                        ..Response::default()
                    },
                },
            ],
            &mut output,
            &mut events,
            &model,
            None,
        )
        .expect("stream should finalize");

        assert_eq!(output.content.len(), 1);
        let persisted_tool_call = match &output.content[0] {
            AssistantContent::ToolCall(tool_call) => tool_call,
            other => panic!("expected toolCall block, got {other:?}"),
        };
        assert_eq!(
            persisted_tool_call.arguments,
            json!({ "path": "README.md", "content": "updated" })
        );
        let persisted_json =
            serde_json::to_value(persisted_tool_call).expect("serializes tool call");
        assert!(persisted_json.get("partialJson").is_none());

        let tool_call_end = events.iter().find_map(|event| match event {
            AssistantMessageEvent::ToolCallEnd { tool_call, .. } => Some(tool_call),
            _ => None,
        });
        let tool_call_end = tool_call_end.expect("expected toolcall_end event");
        assert_eq!(tool_call_end, persisted_tool_call);
        let emitted_json = serde_json::to_value(tool_call_end).expect("serializes tool call");
        assert!(emitted_json.get("partialJson").is_none());
    }

    #[test]
    fn generates_unique_fallback_message_ids_for_multiple_text_blocks() {
        let model = Model {
            id: "gpt-5.5".to_owned(),
            api: "openai-codex-responses".to_owned(),
            provider: "openai-codex".to_owned(),
            reasoning: true,
            input: vec!["text".to_owned()],
            cost: ModelCost::default(),
            compat: None,
        };
        let mut allowed_providers = HashSet::new();
        allowed_providers.extend([
            "openai".to_owned(),
            "openai-codex".to_owned(),
            "opencode".to_owned(),
        ]);
        let response = convert_responses_messages(
            &model,
            &Context {
                system_prompt: Some("You are concise.".to_owned()),
                messages: vec![
                    Message::User(UserMessage {
                        content: UserContent::Text("hello".to_owned()),
                    }),
                    Message::Assistant(AssistantMessage {
                        content: vec![
                            AssistantContent::Thinking(ThinkingContent {
                                thinking: "private reasoning".to_owned(),
                                thinking_signature: None,
                                redacted: false,
                            }),
                            AssistantContent::Text(TextContent {
                                text: "visible answer".to_owned(),
                                text_signature: None,
                            }),
                        ],
                        api: "anthropic-messages".to_owned(),
                        provider: "anthropic".to_owned(),
                        model: "claude-opus-4-8".to_owned(),
                        response_id: None,
                        usage: Usage::default(),
                        stop_reason: StopReason::Stop,
                    }),
                ],
            },
            &allowed_providers,
            None,
        );

        let message_ids: Vec<&str> = response
            .iter()
            .filter(|item| item["type"] == "message" && item["id"].is_string())
            .filter_map(|item| item["id"].as_str())
            .collect();

        assert_eq!(message_ids, ["msg_pi_1", "msg_pi_1_1"]);
        assert_eq!(
            message_ids.iter().collect::<HashSet<_>>().len(),
            message_ids.len()
        );
    }

    #[test]
    fn hashes_foreign_copilot_tool_item_ids_into_bounded_codex_safe_shape() {
        const COPILOT_RAW_TOOL_CALL_ID: &str = "call_4VnzVawQXPB9MgYib7CiQFEY|I9b95oN1wD/cHXKTw3PpRkL6KkCtzTJhUxMouMWYwHeTo2j3htzfSk7YPx2vifiIM4g3A8XXyOj8q4Bt6SLUG7gqY1E3ELkrkVQNHglRfUmWj84lqxJY+Puieb3VKyX0FB+83TUzn91cDMF/4gzt990IzqVrc+nIb9RRscRD070Du16q1glydVjWR0SBJsE6TbY/esOjFpqplogQqrajm1eI++f3eLi73R6q7hVusY0QbeFySVxABCjhN0lXB04caBe1rzHjYzul6MAXj7uq+0r17VLq+yrtyYhN12wkmFqHeqTyEei6EFPbMy24Nc+IbJlkP0OCg02W+gOnyBFcbi2ctvJFSOhSjt1CqBdqCnnhwUqXjbWiT0wh3DmLScRgTHmGkaI+oAcQQjfic65nxj+TnEkReA==";

        let model = Model {
            id: "gpt-5.5".to_owned(),
            api: "openai-codex-responses".to_owned(),
            provider: "openai-codex".to_owned(),
            reasoning: true,
            input: vec!["text".to_owned(), "image".to_owned()],
            cost: ModelCost {
                input: 5.0,
                output: 30.0,
                cache_read: 0.5,
                cache_write: 0.0,
            },
            compat: None,
        };
        let assistant = AssistantMessage {
            content: vec![AssistantContent::ToolCall(ToolCall {
                id: COPILOT_RAW_TOOL_CALL_ID.to_owned(),
                name: "edit".to_owned(),
                arguments: json!({ "path": "src/styles/app.css" }),
                thought_signature: None,
            })],
            api: "openai-responses".to_owned(),
            provider: "github-copilot".to_owned(),
            model: "gpt-5.5".to_owned(),
            response_id: None,
            usage: Usage::default(),
            stop_reason: StopReason::ToolUse,
        };
        let tool_result = ToolResultMessage {
            tool_call_id: COPILOT_RAW_TOOL_CALL_ID.to_owned(),
            tool_name: "edit".to_owned(),
            content: vec![InputContent::Text(TextContent {
                text: "ok".to_owned(),
                text_signature: None,
            })],
            is_error: false,
        };
        let context = Context {
            system_prompt: Some("You are concise.".to_owned()),
            messages: vec![
                Message::User(UserMessage {
                    content: UserContent::Text("Use the tool.".to_owned()),
                }),
                Message::Assistant(assistant),
                Message::ToolResult(tool_result),
            ],
        };
        let input = convert_responses_messages(
            &model,
            &context,
            &HashSet::from([
                "openai".to_owned(),
                "openai-codex".to_owned(),
                "opencode".to_owned(),
            ]),
            None,
        );
        let function_call = input
            .iter()
            .find(|item| item["type"] == "function_call")
            .expect("function_call item");

        assert_eq!(function_call["type"], "function_call");
        let expected_item_id = format!(
            "fc_{}",
            crate::utils::hash::short_hash(
                COPILOT_RAW_TOOL_CALL_ID
                    .split_once('|')
                    .expect("raw Copilot tool call id contains item id")
                    .1
            )
        );
        let item_id = function_call["id"].as_str().expect("function_call id");
        assert_eq!(item_id, expected_item_id);
        assert!(item_id.len() <= 64);
        assert!(
            item_id.starts_with("fc_") && item_id[3..].chars().all(|ch| ch.is_ascii_alphanumeric())
        );
    }

    fn terminal_event_output(model: &Model) -> AssistantMessage {
        AssistantMessage {
            content: Vec::new(),
            api: model.api.clone(),
            provider: model.provider.clone(),
            model: model.id.clone(),
            response_id: None,
            usage: Usage::default(),
            stop_reason: StopReason::Stop,
        }
    }

    fn early_eof_events() -> Vec<ResponseStreamEvent> {
        vec![
            ResponseStreamEvent::ResponseCreated {
                response: Response {
                    id: Some("resp_early_eof".to_owned()),
                    ..Response::default()
                },
            },
            ResponseStreamEvent::ResponseOutputItemAdded {
                output_index: 0,
                item: ResponseOutputItem::Reasoning {
                    summary: Vec::new(),
                    content: Vec::new(),
                    raw: json!({ "type": "reasoning", "id": "rs_early_eof", "summary": [] }),
                },
            },
            ResponseStreamEvent::ResponseReasoningTextDelta {
                output_index: 0,
                delta: "partial reasoning before the stream ends".to_owned(),
            },
        ]
    }

    #[test]
    fn rejects_streams_that_end_before_terminal_response_event() {
        let model = model();
        let mut output = terminal_event_output(&model);
        let mut events = Vec::new();

        let error =
            process_responses_stream(early_eof_events(), &mut output, &mut events, &model, None)
                .expect_err("stream without terminal response event should fail");

        assert_eq!(
            error.to_string(),
            "OpenAI Responses stream ended before a terminal response event"
        );
    }

    #[test]
    fn finalizes_completed_terminal_events_as_stop() {
        let model = model();
        let mut output = terminal_event_output(&model);
        let mut events = Vec::new();

        process_responses_stream(
            vec![ResponseStreamEvent::ResponseCompleted {
                response: Response {
                    id: Some("resp_completed".to_owned()),
                    status: Some(ResponseStatus::Completed),
                    usage: Some(ResponseUsage {
                        input_tokens: 20,
                        output_tokens: 7,
                        total_tokens: 27,
                        input_tokens_details: Some(InputTokensDetails { cached_tokens: 2 }),
                        output_tokens_details: None,
                    }),
                    ..Response::default()
                },
            }],
            &mut output,
            &mut events,
            &model,
            None,
        )
        .expect("completed terminal event should finalize");

        assert_eq!(output.response_id.as_deref(), Some("resp_completed"));
        assert_eq!(output.stop_reason, StopReason::Stop);
        assert_eq!(output.usage.input, 18);
        assert_eq!(output.usage.output, 7);
        assert_eq!(output.usage.cache_read, 2);
        assert_eq!(output.usage.cache_write, 0);
        assert_eq!(output.usage.total_tokens, 27);
    }

    #[test]
    fn finalizes_incomplete_terminal_events_as_length_stops() {
        let model = model();
        let mut output = terminal_event_output(&model);
        let mut events = Vec::new();

        process_responses_stream(
            vec![ResponseStreamEvent::ResponseIncomplete {
                response: Response {
                    id: Some("resp_incomplete".to_owned()),
                    status: Some(ResponseStatus::Incomplete),
                    usage: Some(ResponseUsage {
                        input_tokens: 30,
                        output_tokens: 12,
                        total_tokens: 42,
                        input_tokens_details: Some(InputTokensDetails { cached_tokens: 5 }),
                        output_tokens_details: None,
                    }),
                    ..Response::default()
                },
            }],
            &mut output,
            &mut events,
            &model,
            None,
        )
        .expect("incomplete terminal event should finalize");

        assert_eq!(output.response_id.as_deref(), Some("resp_incomplete"));
        assert_eq!(output.stop_reason, StopReason::Length);
        assert_eq!(output.usage.input, 25);
        assert_eq!(output.usage.output, 12);
        assert_eq!(output.usage.cache_read, 5);
        assert_eq!(output.usage.cache_write, 0);
        assert_eq!(output.usage.total_tokens, 42);
    }

    #[test]
    fn rejects_failed_terminal_events_with_the_provider_error() {
        let model = model();
        let mut output = terminal_event_output(&model);
        let mut events = Vec::new();

        let error = process_responses_stream(
            vec![ResponseStreamEvent::ResponseFailed {
                response: Some(Response {
                    id: Some("resp_failed".to_owned()),
                    status: Some(ResponseStatus::Failed),
                    error: Some(ResponseError {
                        code: Some("server_error".to_owned()),
                        message: Some("boom".to_owned()),
                    }),
                    ..Response::default()
                }),
            }],
            &mut output,
            &mut events,
            &model,
            None,
        )
        .expect_err("failed terminal event should return provider error");

        assert_eq!(error.to_string(), "server_error: boom");
    }

    #[test]
    fn finalizes_stream_usage_and_tool_stop() {
        let model = model();
        let mut output = terminal_event_output(&model);
        let mut events = Vec::new();
        process_responses_stream(
            vec![
                ResponseStreamEvent::ResponseOutputItemAdded {
                    output_index: 0,
                    item: ResponseOutputItem::FunctionCall {
                        id: Some("fc_1".to_owned()),
                        call_id: "call".to_owned(),
                        name: "tool".to_owned(),
                        arguments: "".to_owned(),
                    },
                },
                ResponseStreamEvent::ResponseFunctionCallArgumentsDone {
                    output_index: 0,
                    arguments: "{\"x\":1}".to_owned(),
                },
                ResponseStreamEvent::ResponseOutputItemDone {
                    output_index: 0,
                    item: ResponseOutputItem::FunctionCall {
                        id: Some("fc_1".to_owned()),
                        call_id: "call".to_owned(),
                        name: "tool".to_owned(),
                        arguments: "{\"x\":1}".to_owned(),
                    },
                },
                ResponseStreamEvent::ResponseCompleted {
                    response: Response {
                        id: Some("resp".to_owned()),
                        status: Some(ResponseStatus::Completed),
                        usage: Some(ResponseUsage {
                            input_tokens: 10,
                            output_tokens: 5,
                            total_tokens: 15,
                            input_tokens_details: Some(InputTokensDetails { cached_tokens: 3 }),
                            output_tokens_details: Some(OutputTokensDetails {
                                reasoning_tokens: 2,
                            }),
                        }),
                        ..Response::default()
                    },
                },
            ],
            &mut output,
            &mut events,
            &model,
            None,
        )
        .expect("stream should finalize");

        assert_eq!(output.response_id.as_deref(), Some("resp"));
        assert_eq!(output.usage.input, 7);
        assert_eq!(output.stop_reason, StopReason::ToolUse);
        assert!(matches!(
            events.last(),
            Some(AssistantMessageEvent::ToolCallEnd { .. })
        ));
    }
}
