//! Generate zedflow-ai's top-level model catalog from Pi's generated catalog.

use std::fs;
use std::path::Path;

use regex::Regex;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let repo = crate_dir
        .parent()
        .and_then(Path::parent)
        .ok_or("cannot find repository root")?;
    let source = repo.join("references/pi/packages/ai/src/models.generated.ts");
    let target = crate_dir.join("src/models.generated.rs");

    let text = fs::read_to_string(&source)?;
    let re = Regex::new(r#"(?m)^\s*"([^"]+)":\s*[A-Z0-9_]+_MODELS,"#)?;
    let providers: Vec<_> = re
        .captures_iter(&text)
        .map(|cap| cap[1].to_owned())
        .collect();
    if providers.is_empty() {
        return Err(format!("no providers found in {}", source.display()).into());
    }

    let items = providers
        .iter()
        .map(|provider| format!("    \"{provider}\","))
        .collect::<Vec<_>>()
        .join("\n");
    fs::write(
        &target,
        format!(
            r#"// This file is auto-generated by scripts/generate-models.rs.
// Do not edit manually - run `make generate-models` from crates/zedflow-ai.

//! Generated built-in chat model catalog ported from Pi's `packages/ai/src/models.generated.ts`.
//!
//! Provider-specific model rows are ported separately; this catalog preserves the
//! provider keys and ordering from Pi's generated `MODELS` object.

/// Built-in provider id present in Pi's generated model catalog.
pub type BuiltinProvider = &'static str;

/// Provider ids from Pi's generated `MODELS` object.
pub const BUILTIN_PROVIDERS: &[BuiltinProvider] = &[
{items}
];

/// Returns true when `provider` is in the generated built-in catalog.
#[must_use]
pub fn has_builtin_provider(provider: &str) -> bool {{
    BUILTIN_PROVIDERS.contains(&provider)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn preserves_generated_provider_keys() {{
        assert_eq!(BUILTIN_PROVIDERS.len(), {});
        assert!(has_builtin_provider("openai"));
        assert!(has_builtin_provider("amazon-bedrock"));
    }}
}}
"#,
            providers.len()
        ),
    )?;
    println!("generated {} from {}", target.display(), source.display());
    Ok(())
}
