//! Generate zedflow-ai's image model catalog from Pi's generated catalog.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use regex::Regex;

fn rust_str(value: &str) -> String {
    format!("{:?}", value)
}

fn modalities(text: &str) -> String {
    let values = Regex::new(r#""(text|image)""#)
        .expect("valid modality regex")
        .captures_iter(text)
        .map(|cap| match &cap[1] {
            "text" => "ImageModelContent::Text",
            "image" => "ImageModelContent::Image",
            _ => unreachable!(),
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{values}]")
}

fn f64_literal(value: &str) -> String {
    if value.contains('.') {
        value.to_owned()
    } else {
        format!("{value}.0")
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let repo = crate_dir
        .parent()
        .and_then(Path::parent)
        .ok_or("cannot find repository root")?;
    let source = repo.join("references/pi/packages/ai/src/image-models.generated.ts");
    let target = crate_dir.join("src/image-models.generated.rs");

    let text = fs::read_to_string(&source)?;
    let model_re = Regex::new(
        r#"(?s)id: "([^"]+)",\s*name: "((?:[^"\\]|\\.)*)",\s*api: "([^"]+)",\s*provider: "([^"]+)",\s*baseUrl: "([^"]+)",\s*input: \[([^\]]*)\],\s*output: \[([^\]]*)\],\s*cost: \{\s*input: ([0-9.]+),\s*output: ([0-9.]+),\s*cacheRead: ([0-9.]+),\s*cacheWrite: ([0-9.]+),"#,
    )?;

    let mut grouped: BTreeMap<String, Vec<[String; 11]>> = BTreeMap::new();
    for cap in model_re.captures_iter(&text) {
        let row = std::array::from_fn(|i| cap[i + 1].to_owned());
        grouped.entry(cap[4].to_owned()).or_default().push(row);
    }
    if grouped.is_empty() {
        return Err(format!("no image models found in {}", source.display()).into());
    }

    let mut providers = Vec::new();
    for (provider, models) in &grouped {
        let rows = models
            .iter()
            .map(|m| {
                format!(
                    r#"        ImageModel {{
            id: {},
            name: {},
            api: {},
            provider: {},
            base_url: {},
            input: {},
            output: {},
            cost: ImageModelCost {{
                input: {},
                output: {},
                cache_read: {},
                cache_write: {},
            }},
        }},"#,
                    rust_str(&m[0]),
                    rust_str(&m[1].replace(r#"\""#, r#"""#)),
                    rust_str(&m[2]),
                    rust_str(&m[3]),
                    rust_str(&m[4]),
                    modalities(&m[5]),
                    modalities(&m[6]),
                    f64_literal(&m[7]),
                    f64_literal(&m[8]),
                    f64_literal(&m[9]),
                    f64_literal(&m[10]),
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        providers.push(format!(
            r#"    ImageProviderModels {{
        provider: {},
        models: &[
{rows}
        ],
    }},"#,
            rust_str(provider)
        ));
    }

    fs::write(
        &target,
        format!(
            r#"// This file is auto-generated by scripts/generate-image-models.rs.
// Do not edit manually - run `make generate-image-models` from crates/zedflow-ai.

//! Generated Pi image model metadata.

/// Text or image content accepted or produced by an image model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ImageModelContent {{
    /// Plain text content.
    Text,
    /// Image content.
    Image,
}}

/// Per-million-unit pricing metadata for an image model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ImageModelCost {{
    /// Input cost.
    pub input: f64,
    /// Output cost.
    pub output: f64,
    /// Prompt-cache read cost.
    pub cache_read: f64,
    /// Prompt-cache write cost.
    pub cache_write: f64,
}}

/// Metadata for a Pi image model.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ImageModel {{
    /// Model identifier.
    pub id: &'static str,
    /// Human-readable model name.
    pub name: &'static str,
    /// Image API identifier.
    pub api: &'static str,
    /// Provider identifier.
    pub provider: &'static str,
    /// Provider base URL.
    pub base_url: &'static str,
    /// Accepted input content types.
    pub input: &'static [ImageModelContent],
    /// Produced output content types.
    pub output: &'static [ImageModelContent],
    /// Pricing metadata.
    pub cost: ImageModelCost,
}}

/// Image models grouped by provider, matching Pi's generated `IMAGE_MODELS` shape.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ImageProviderModels {{
    /// Provider identifier.
    pub provider: &'static str,
    /// Models available for the provider.
    pub models: &'static [ImageModel],
}}

/// Generated image model catalog ported from Pi.
pub const IMAGE_MODELS: &[ImageProviderModels] = &[
{}
];
"#,
            providers.join("\n")
        ),
    )?;
    println!("generated {} with image models", target.display());
    Ok(())
}
