// This file is auto-generated by scripts/generate-models.rs.
// Do not edit manually - run `make generate-models` from crates/zedflow-ai.

//! Generated built-in chat model catalog ported from Pi's `packages/ai/src/models.generated.ts`.
//!
//! Provider-specific model rows are ported separately; this catalog preserves the
//! provider keys and ordering from Pi's generated `MODELS` object.

/// Built-in provider id present in Pi's generated model catalog.
pub type BuiltinProvider = &'static str;

/// Provider ids from Pi's generated `MODELS` object.
pub const BUILTIN_PROVIDERS: &[BuiltinProvider] = &[
    "amazon-bedrock",
    "ant-ling",
    "anthropic",
    "azure-openai-responses",
    "cerebras",
    "cloudflare-ai-gateway",
    "cloudflare-workers-ai",
    "deepseek",
    "fireworks",
    "github-copilot",
    "google",
    "google-vertex",
    "groq",
    "huggingface",
    "kimi-coding",
    "minimax",
    "minimax-cn",
    "mistral",
    "moonshotai",
    "moonshotai-cn",
    "nvidia",
    "openai",
    "openai-codex",
    "opencode",
    "opencode-go",
    "openrouter",
    "together",
    "vercel-ai-gateway",
    "xai",
    "xiaomi",
    "xiaomi-token-plan-ams",
    "xiaomi-token-plan-cn",
    "xiaomi-token-plan-sgp",
    "zai",
    "zai-coding-cn",
];

/// Returns true when `provider` is in the generated built-in catalog.
#[must_use]
pub fn has_builtin_provider(provider: &str) -> bool {
    BUILTIN_PROVIDERS.contains(&provider)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_generated_provider_keys() {
        assert_eq!(BUILTIN_PROVIDERS.len(), 35);
        assert!(has_builtin_provider("openai"));
        assert!(has_builtin_provider("amazon-bedrock"));
    }
}
