<script setup lang="ts">
import { computed, ref } from 'vue'
import { Download, RefreshCw } from 'lucide-vue-next'
import type { RunSummary, Workspace } from '@zedflow/sdk'
import { statuses } from '../composables/useZedflow'
const props=defineProps<{runs:RunSummary[];workspaces:Workspace[];workspaceId:string;currentId?:string;busy:boolean}>()
const emit=defineEmits<{open:[run:RunSummary];export:[run:RunSummary];refresh:[]}>()
const query=ref('')
const items=computed(()=>props.runs.filter(run=>run.interactive===false&&run.workspaceId===props.workspaceId&&run.name.toLocaleLowerCase().includes(query.value.toLocaleLowerCase())).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)))
</script>
<template><details class="autonomous-history"><summary>Exécutions autonomes <small>{{items.length}}</small></summary><p class="autonomous-history-help">Runs de flows sans conversation interactive. Lancez-en un depuis « Utiliser » sur un flow autonome.</p><div class="autonomous-history-filter"><input v-model="query" aria-label="Rechercher une exécution" placeholder="Rechercher…"/><button class="icon-button" aria-label="Actualiser les exécutions" :disabled="busy" @click="emit('refresh')"><RefreshCw :size="14"/></button></div><div class="autonomous-history-list"><div v-for="run in items" :key="run.id" class="autonomous-history-row" :class="{selected:currentId===run.id}" :data-execution-id="run.id"><button @click="emit('open',run)"><span>{{run.name}}</span><small>{{statuses[run.status]||run.status}}</small></button><button class="icon-button" :disabled="run.status==='running'||run.runtimeActive" :aria-label="`Exporter l’exécution ${run.name}`" @click="emit('export',run)"><Download :size="13"/></button></div><p v-if="!items.length">Aucune exécution autonome dans ce workspace.</p></div></details></template>
<style scoped>.autonomous-history{border-top:1px solid #34343b;margin:0 10px;flex-shrink:0;padding:12px 0;font-size:12px}.autonomous-history-help{font-size:11px;color:#9394a1;line-height:1.5;margin:10px 0}.autonomous-history summary{cursor:pointer;color:#bfc0cb}.autonomous-history summary small{float:right;color:#81828f}.autonomous-history-filter{display:flex;gap:5px;margin:10px 0}.autonomous-history input{width:100%;min-width:0;background:#24242a;border:1px solid #393941;border-radius:5px;color:#ddd;padding:6px}.autonomous-history-list{overflow:auto;max-height:260px}.autonomous-history-row{display:flex;align-items:center;border-radius:5px;margin:2px 0}.autonomous-history-row.selected{background:#33343e}.autonomous-history-row>button:first-child{display:flex;flex:1;min-width:0;flex-direction:column;align-items:start;gap:3px;background:transparent;border:0;text-align:left;padding:7px}.autonomous-history-row span{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.autonomous-history-row small,.autonomous-history-list p{font-size:10px;color:#9394a1}.autonomous-history-row .icon-button{opacity:0}.autonomous-history-row:hover .icon-button,.autonomous-history-row:focus-within .icon-button{opacity:1}</style>
