<script setup lang="ts">
import { modelSelectionSchema, jsonValueSchema } from '@zedflow/sdk'
import type { HistoricalModelSelection } from '@zedflow/sdk'
import type { InspectionSelection } from '../composables/useExecutedDefinition'
import type { ModelEntry, JsonValue } from '@zedflow/sdk'

import { computed, ref, watch } from 'vue'
import { GitBranch, Play, SlidersHorizontal, Square } from 'lucide-vue-next'
import type { Composition, FlowFile, ModelSelection, Run } from '@zedflow/sdk'
import type { ModelNode } from '../harness'
import type { RuntimePreparation } from '../compositionEngine'

import { flowExports } from '../compositionEngine'

import ContextValueEditor from './context/ContextValueEditor.vue'
import ModelBindingsPanel from './ModelBindingsPanel.vue'
import ModelPicker from './ModelPicker.vue'
import ChatTimeline from './ChatTimeline.vue'
const input=defineModel<JsonValue>('input',{required:true})
const props=defineProps<{run:Run|null;composition:Composition;flows:FlowFile[];flowKey?:string;prepared?:RuntimePreparation|null;models:ModelEntry[];nodes:ModelNode[];bindings:Record<string,HistoricalModelSelection>;busy:boolean;initialized:boolean}>()
const emit=defineEmits<{launch:[input:JsonValue];flow:[file:FlowFile];composition:[];definition:[];inspect:[selection:InspectionSelection];details:[tab?:'activity'|'models'|'context'|'state'];change:[path:string,value:ModelSelection];answer:[value:JsonValue,waitId:string];command:[action:'abort'|'resume'];earlier:[];new:[]}>()
const showModels=ref(false),waitingSelection=ref<ModelSelection>()
const blocked=computed(()=>props.run?.import?.resumeBlocked||[])
const hasContract=computed(()=>!!flowExports(props.composition))
const waitPath=computed(()=>props.run?.wait?.nodePath||props.run?.wait?.node||'')
watch(()=>[props.run?.wait?.id,props.bindings[waitPath.value]],()=>{waitingSelection.value=modelSelectionSchema.safeParse(props.bindings[waitPath.value]).data},{immediate:true})
function selectFlow(event:Event){const file=props.flows.find(file=>file.key===(event.target as HTMLSelectElement).value);if(file)emit('flow',file)}
</script>
<template><section class="autonomous-execution" aria-label="Exécution autonome"><header class="autonomous-toolbar"><span><GitBranch :size="16"/> Exécution autonome</span><div class="actions"><button @click="emit('details','activity')"><SlidersHorizontal :size="14"/> Inspecter</button><button v-if="run?.status==='running'" :disabled="busy" @click="emit('command','abort')"><Square :size="13"/> Arrêter</button><button v-if="run&&['stopped','interrupted'].includes(run.status)" :disabled="busy||!!blocked.length" @click="emit('command','resume')">Reprendre</button><button v-if="run" @click="emit('new')">Nouvelle exécution</button></div></header>
<div v-if="!run" class="autonomous-launch"><h1>{{composition.name}}</h1><p>Fournissez la donnée d’entrée, puis lancez le graphe. Les résultats et les passages sont conservés dans l’historique des exécutions.</p><label>Flow<select aria-label="Flow à exécuter" :value="flowKey" :disabled="busy" @change="selectFlow"><option v-for="file in flows.filter(file=>file.composition)" :key="file.key" :value="file.key">{{file.name}}</option></select></label><div class="actions"><button :disabled="busy" @click="emit('definition')">Définition</button><button :disabled="busy" @click="emit('composition')">{{prepared?'Entrée et bridges':'Configurer l’entrée et les bridges'}}</button><button v-if="nodes.length" @click="showModels=!showModels">Modèles · {{nodes.length}}</button></div><ModelBindingsPanel v-if="showModels" :nodes="nodes" :models="models" :bindings="bindings" :busy="busy" @change="(path,value)=>emit('change',path,value)" @close="showModels=false"/>
<form v-if="prepared||!hasContract" @submit.prevent="emit('launch',input)"><fieldset :disabled="busy||!initialized"><ContextValueEditor v-model="input" :type="prepared?.inputType||{kind:'text'}" :types="prepared?.overview.types" label="Donnée d’entrée"/><button class="primary" type="submit"><Play :size="14"/> Lancer l’exécution</button></fieldset></form><button v-else class="primary" :disabled="busy||!initialized" @click="emit('composition')"><GitBranch :size="14"/> Préparer cette exécution</button></div>
<template v-else><div v-if="blocked.length" role="alert" class="banner error"><strong>Reprise indisponible</strong><p v-for="reason in blocked" :key="reason">{{reason}}</p></div><div v-if="run.status==='waiting'" class="autonomous-wait"><template v-if="run.wait?.kind==='model_selection'"><strong>{{run.wait.config.prompt||'Choisir le modèle pour continuer'}}</strong><ModelPicker :selection="waitingSelection" :models="models" :disabled="busy" @change="waitingSelection=$event"/><button class="primary" :disabled="!waitingSelection||busy||!!blocked.length" @click="emit('answer',jsonValueSchema.parse(waitingSelection),run.wait!.id)">Choisir et reprendre</button></template><template v-else><strong>L’exécution attend à une frontière.</strong><p>Consultez le passage et son état pour comprendre cette interruption.</p><button @click="emit('details','activity')">Inspecter l’attente</button></template></div><p v-if="run.status==='running'" role="status">Exécution en cours…</p><p v-if="run.error" role="alert" class="banner error">{{run.error}}</p><button v-if="run.timelineHasMore" :disabled="busy" @click="emit('earlier')">Charger les résultats précédents</button><ChatTimeline :run="run" results @inspect="emit('inspect',$event)"/><p v-if="run.status==='completed'&&!(run.timeline||[]).some(entry=>entry.kind==='message'&&entry.role==='assistant')" class="autonomous-no-output">Exécution terminée. Consultez l’état pour les valeurs produites.<button @click="emit('details','state')">Voir l’état</button></p></template></section></template>
<style scoped>.autonomous-execution{flex:1;min-width:0;overflow:auto;padding:22px clamp(20px,5vw,72px)}.autonomous-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:30px}.autonomous-toolbar>span{display:flex;align-items:center;gap:8px;color:#acadb8;font-size:12px}.autonomous-launch{max-width:720px;margin:30px auto}.autonomous-launch h1{font-size:24px;font-weight:500}.autonomous-launch p,.autonomous-no-output,.autonomous-wait p{color:#9293a0;font-size:13px;line-height:1.6}.autonomous-launch label{display:flex;flex-direction:column;gap:8px;font-size:12px;margin:20px 0}.autonomous-launch :deep(input),.autonomous-launch :deep(select),.autonomous-launch :deep(textarea){background:#25252b;color:#dedee7;border:1px solid #45454f;border-radius:5px;padding:9px;max-width:100%;font:inherit}.autonomous-launch fieldset{border:0;padding:0;margin:24px 0}.autonomous-launch :deep(textarea){min-height:120px;resize:vertical}.autonomous-wait{border:1px solid #45454f;border-radius:8px;padding:16px;margin-bottom:20px}.autonomous-wait>*+*{margin-top:12px}.autonomous-execution :deep(.execution-results){max-width:880px;margin:auto}.autonomous-no-output button{margin-left:12px}@media(max-width:760px){.autonomous-toolbar{flex-direction:column;align-items:flex-start}.autonomous-toolbar .actions{flex-wrap:wrap}}</style>
