<script setup lang="ts">
import { computed, ref } from 'vue'
import { CircleAlert, Copy, FileCode2, Globe, Pencil, Plus, MoreHorizontal, RefreshCw, Search, Trash2 } from 'lucide-vue-next'
import type { FlowFile, Workspace } from '@zedflow/sdk'
import { DropdownMenuRoot, DropdownMenuTrigger, DropdownMenuPortal, DropdownMenuContent, DropdownMenuItem } from 'reka-ui'
import '../graph.css'
const props=defineProps<{flows:FlowFile[];workspaces:Workspace[];workspaceId:string;selectedKey?:string;busy:boolean}>()
const emit=defineEmits<{open:[flow:FlowFile];create:[kind:'harness'|'tools'|'interactive'|'autonomous'];rename:[flow:FlowFile];duplicate:[flow:FlowFile];delete:[flow:FlowFile];refresh:[];workspace:[id:string]}>()
const query=ref('')
const starters=[{kind:'harness',name:'Harness de workspace',description:'Agent, fichiers et boucle d’outils'},{kind:'tools',name:'Modèle et outils',description:'Une boucle simple avec un outil fixture'},{kind:'interactive',name:'Boucle interactive',description:'Échanger sur plusieurs tours'},{kind:'autonomous',name:'Exécution autonome',description:'Une demande, un résultat'}] as const
const groups=computed(()=>[{scope:'workspace',name:'Dans ce workspace'},{scope:'global',name:'Globaux'}].map(group=>({...group,items:props.flows.filter(file=>file.scope===group.scope&&`${file.name} ${file.path}`.toLowerCase().includes(query.value.toLowerCase()))})))
</script>
<template>
  <aside class="flow-library"><header><h2>Flows</h2><button class="icon-button" aria-label="Actualiser les flows" :disabled="busy" @click="emit('refresh')"><RefreshCw :size="15"/></button></header>
    <label class="library-workspace">Workspace<select :value="workspaceId" aria-label="Workspace de conception" @change="emit('workspace',($event.target as HTMLSelectElement).value)"><option v-for="item in workspaces.filter(workspace=>workspace.open)" :key="item.id" :value="item.id">{{item.name}}</option></select></label>
    <div class="library-search"><Search :size="14"/><input v-model="query" aria-label="Rechercher dans la bibliothèque" placeholder="Rechercher un flow…"/></div>
    <div class="flow-library-list"><section v-for="group in groups" :key="group.scope"><h3><Globe v-if="group.scope==='global'" :size="12"/>{{group.name}}</h3><article v-for="file in group.items" :key="file.key" class="flow-file" :class="{selected:selectedKey===file.key,invalid:!file.composition}" :data-flow-key="file.key"><button class="flow-file-open" :title="file.path" @click="emit('open',file)"><FileCode2 v-if="file.composition" :size="16"/><CircleAlert v-else :size="16"/><span><strong>{{file.name}}</strong><small>{{file.path.includes('/.agents/')?'.agents/flows':'.zedflow/flows'}} · Rust</small></span></button><p v-if="!file.composition" class="flow-diagnostic">{{file.diagnostics.join(' · ')}}</p><DropdownMenuRoot><DropdownMenuTrigger class="icon-button flow-file-menu-trigger" :aria-label="`Actions du flow ${file.name}`" :disabled="busy"><MoreHorizontal :size="14"/></DropdownMenuTrigger><DropdownMenuPortal><DropdownMenuContent class="flow-actions-menu" side="right" align="start" :side-offset="8" :collision-padding="12"><DropdownMenuItem :disabled="!file.composition||busy" @select="emit('rename',file)"><Pencil :size="13"/>Renommer {{file.name}}</DropdownMenuItem><DropdownMenuItem :disabled="!file.composition||busy" @select="emit('duplicate',file)"><Copy :size="13"/>Dupliquer {{file.name}}</DropdownMenuItem><DropdownMenuItem :disabled="busy" @select="emit('delete',file)"><Trash2 :size="13"/>Supprimer {{file.name}}</DropdownMenuItem></DropdownMenuContent></DropdownMenuPortal></DropdownMenuRoot></article><p v-if="!group.items.length" class="library-empty">Aucun flow {{group.scope==='global'?'global':'dans ce workspace'}}.</p></section></div>
    <div class="flow-templates"><DropdownMenuRoot><DropdownMenuTrigger class="create-flow-trigger"><Plus :size="15"/>Créer un flow</DropdownMenuTrigger><DropdownMenuPortal><DropdownMenuContent class="flow-starters-menu" side="right" align="end" :side-offset="10" :collision-padding="12"><DropdownMenuItem v-for="starter in starters" :key="starter.kind" class="flow-starter" @select="emit('create',starter.kind)"><strong>{{starter.name}}</strong><small>{{starter.description}}</small></DropdownMenuItem></DropdownMenuContent></DropdownMenuPortal></DropdownMenuRoot></div>
  </aside>
</template>
