<script setup lang="ts">
import { computed, ref } from 'vue'
import type { ExecutedDefinition, RunRevisions } from '@zedflow/sdk'
import AppDialog from './AppDialog.vue'
const props=defineProps<{definition?:ExecutedDefinition;revisions?:RunRevisions;loading:boolean;error:string}>()
const emit=defineEmits<{refresh:[]}>()
const sourceOpen=ref(false)
const issues=computed(()=>props.revisions?.instances.flatMap(instance=>instance.scopes.filter(scope=>scope.diagnostic).map(scope=>({...scope,instance:instance.instance,key:instance.key,publishedHash:instance.publishedHash})))||[])
function issueText(issue:NonNullable<typeof issues.value[number]['diagnostic']>){return issue.message||({pending_tool_calls:'Les appels d’outils engagés doivent se terminer avant cette adoption.',context_state_incompatible:'Le contexte requis par la nouvelle version est incompatible avec l’état actuel.',frontier_incompatible:'La structure de la nouvelle version ne peut pas être adoptée à cette étape.',pending_node_removed:'La nouvelle version retire un nœud encore attendu.'} as Record<string,string>)[issue.code]||issue.code}
</script>
<template><section class="run-revisions" aria-label="Versions de cette exécution"><div class="run-revision-heading"><span v-if="loading">Chargement de la version…</span><span v-else-if="definition?.exact">Version du passage <code>{{definition.hash.slice(0,12)}}</code></span><span v-else>Versions d’exécution</span><button v-if="definition?.exact" @click="sourceOpen=true">Source du passage</button><button aria-label="Actualiser les révisions" @click="emit('refresh')">↻</button></div><p v-if="error" class="field-error" role="alert">{{error}}</p><p v-if="definition&&!definition.exact" class="muted">{{definition.diagnostic.message}} Le graphe initial reste une référence de consultation.</p><div v-for="issue in issues" :key="`${issue.threadId}/${issue.scope}/${issue.step}`" class="run-revision-issue" role="status"><strong>Révision conservée · {{issue.scope||issue.instance||'flow principal'}}</strong><p>{{issueText(issue.diagnostic!)}}</p><small>Active {{issue.hash.slice(0,12)}} · publiée {{issue.publishedHash.slice(0,12)}} · étape {{issue.step}}</small></div><details v-if="revisions?.instances.length"><summary>Définitions et adoption · {{revisions.instances.length}}</summary><article v-for="instance in revisions.instances" :key="instance.instance"><strong>{{instance.instance||'Flow principal'}} · {{instance.key}}</strong><p>Initiale <code>{{instance.initialHash.slice(0,12)}}</code> · publiée <code>{{instance.publishedHash.slice(0,12)}}</code></p><p v-for="scope in instance.scopes" :key="`${scope.threadId}/${scope.scope}`">{{scope.scope||'Racine'}} · étape {{scope.step}} · <code>{{scope.hash.slice(0,12)}}</code> · {{scope.pending?'adoption en attente':'adoptée'}}</p></article></details><AppDialog v-model:open="sourceOpen" title="Source Rust exacte du passage" wide><template v-if="definition?.exact"><p>{{definition.key}} · {{definition.instance||'Flow principal'}} · {{definition.hash}}</p><pre class="source-preview">{{definition.source}}</pre></template></AppDialog></section></template>
<style scoped>.run-revisions{flex:none;padding:8px 12px;border-bottom:1px solid #36363e;font-size:11px;max-height:220px;overflow:auto}.run-revision-heading{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.run-revision-heading>span{flex:1}.run-revision-heading button{font-size:10px;padding:4px 6px}.run-revisions code{color:#b2afc4;font-size:10px;overflow-wrap:anywhere}.run-revisions summary{cursor:pointer;margin-top:9px}.run-revisions article{padding:8px 0;border-top:1px solid #33333b}.run-revisions p{margin:5px 0;line-height:1.5}.run-revision-issue{border-left:2px solid #cba26b;padding:7px 9px;margin:8px 0;background:#302a21}.run-revision-issue small{color:#bab2a5}</style>
