import { test, expect, type Page, type Locator } from '@playwright/test'
import { readFile, writeFile } from 'node:fs/promises'
import type { ContextFile, ContextStrategy } from '@zedflow/sdk'
import { designTemplate, fixturePath, waitRun } from './helpers'

async function studio(page: Page) {
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await page.getByRole('navigation', { name: 'Espace de conception' }).getByRole('button', { name: 'Contexte', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Studio de contexte' })).toBeVisible()
  await page.getByRole('button', { name: 'Créer une stratégie', exact: true }).click()
  return page.locator('.context-studio:not(.bridge-studio)')
}
async function addBlock(page: Page, container: ReturnType<Page['locator']>, kind: 'Groupe' | 'Fragment' | 'Condition') {
  await container.getByRole('button', { name: /Ajouter un bloc$/ }).last().click()
  const label = { Groupe: 'Groupe', Fragment: 'Ajouter au contexte', Condition: 'Si… Alors… Sinon…' }[kind]
  await page.getByRole('menuitem', { name: new RegExp(`^${label}`) }).click()
}
async function declareTextSource(page: Page, panel: Locator, name: string) {
  await panel.getByRole('button', { name: 'Ajouter des types', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Ajouter des types de sources', exact: true })
  await dialog.getByText('Définir un type personnalisé', { exact: true }).click()
  await dialog.getByLabel('Nom du type personnalisé', { exact: true }).fill(name)
  await dialog.getByLabel('Schéma du type personnalisé', { exact: true }).selectOption('text')
  await dialog.getByRole('button', { name: 'Déclarer ce type', exact: true }).click()
}
async function manualSource(panel: Locator, name: string) {
  const source = panel.locator(`[data-resource="${name}"]`)
  const disclosure = source.locator('.ctx-source-disclosure')
  if (await disclosure.getAttribute('aria-expanded') !== 'true') await disclosure.click()
  const manual = source.locator('details').filter({ hasText: `Fournir ${name} pour l’aperçu` })
  if (await manual.getAttribute('open') === null) await manual.locator('summary').click()
  return source
}
async function expressionDetails(block: Locator) {
  await block.getByRole('button', { name: /^Configurer l’expression : Contenu du fragment/ }).click()
  return block.getByRole('combobox', { name: /^Contenu du fragment ·/ })
}
async function dependencies(panel: Locator) {
  const details = panel.locator('.ctx-studio-dependencies')
  if (await details.getAttribute('open') === null) await details.locator('summary').click()
}
function literal(value: string) { return { kind: 'literal' as const, dataType: { kind: 'text' as const }, value } }

test('context studio edits nested blocks with the keyboard, saves actual Rust and reloads its preview', async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const panel = await studio(page)
  const tabs=panel.getByRole('navigation',{name:'Éditeur de contexte',exact:true})
  await expect.poll(()=>tabs.evaluate(element=>{const outer=element.getBoundingClientRect();return [...element.querySelectorAll('button')].every(button=>{const rect=button.getBoundingClientRect();return rect.left>=outer.left&&rect.right<=outer.right&&rect.top>=outer.top&&rect.bottom<=outer.bottom})})).toBe(true)
  await panel.getByLabel('Nom de la stratégie', { exact: true }).fill('Contexte édité visuellement')
  await declareTextSource(page, panel, 'question')
  await manualSource(panel, 'question')
  await panel.getByLabel('Fournir question pour l’aperçu', { exact: true }).check()
  await panel.getByLabel('Valeur de question', { exact: true }).fill('Question explicitement fournie')
  await addBlock(page, panel.locator('.ctx-program-panel'), 'Groupe')
  const group = panel.locator('[data-block-kind="group"]').first()
  await group.getByRole('button', { name: 'Actions du bloc 1', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Renommer le groupe', exact: true }).click()
  await group.getByLabel('Nom du groupe', { exact: true }).fill('Working system')
  await group.getByLabel('Nom du groupe', { exact: true }).press('Enter')
  await addBlock(page, group, 'Fragment')
  const first = group.locator('[data-block-kind="emit"]').first()
  await first.getByRole('button', { name: /^Choisir un champ pour Contenu du fragment/ }).click()
  await page.getByRole('menuitem', { name: /^question\b/ }).click()
  await addBlock(page, group, 'Fragment')
  const second = group.locator('[data-block-kind="emit"]').nth(1)
  await second.getByRole('textbox', { name: /^Contenu du fragment ·/ }).fill('Instruction stable')
  await second.getByRole('button', { name: 'Configurer le rôle et la représentation', exact: true }).click()
  await second.getByLabel('Rôle', { exact: true }).selectOption('instruction')
  const secondId = await second.getAttribute('data-context-block')
  await second.locator('.ctx-block-grip').focus()
  await page.keyboard.press('Alt+ArrowUp')
  await expect(group.locator('[data-block-kind="emit"]').first()).toHaveAttribute('data-context-block', secondId!)
  await expect(group.locator('[data-block-kind="emit"]').first().locator('.ctx-block-grip')).toBeFocused()
  await page.keyboard.press('Delete')
  await expect(group.locator('[data-block-kind="emit"]')).toHaveCount(1)
  await group.getByRole('button', { name: 'Annuler la suppression du bloc', exact: true }).click()
  await expect(group.locator('[data-block-kind="emit"]').first()).toHaveAttribute('data-context-block', secondId!)
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment').first()).toContainText('Instruction stable')
  await expect(panel.locator('.ctx-preview-fragment').nth(1)).toContainText('Question explicitement fournie')
  await page.screenshot({ path: test.info().outputPath('context-studio-desktop.png') })
  await panel.locator('.ctx-preview-fragment').nth(1).click()
  const questionId = await group.locator('[data-block-kind="emit"]').nth(1).getAttribute('data-context-block')
  await expect(panel.locator(`[data-context-block="${questionId}"]`)).toHaveClass(/selected/)
  await panel.getByLabel('Nom de la stratégie', { exact: true }).focus()
  await page.keyboard.press('Control+s')
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const files: ContextFile[] = await (await request.get(`/api/context-strategies?workspaceId=${health.defaultWorkspaceId}`)).json()
  const file = files.find(file => file.strategy?.name === 'Contexte édité visuellement')!
  expect(file.path).toContain(fixturePath('workspace-a', '.zedflow', 'context'))
  const source = await readFile(file.path, 'utf8')
  expect(source).toContain('ContextStrategy::new')
  expect(source).toContain('Working system')
  expect(source).not.toContain('Question explicitement fournie') // Preview fixture values are not strategy declarations.
  expect(file.strategy?.program[0]?.kind).toBe('group')
  await page.getByRole('button', { name: 'Exécution', exact: true }).click()
  await expect(panel).not.toBeVisible()
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await manualSource(panel, 'question')
  await expect(panel.getByLabel('Valeur de question', { exact: true })).toHaveValue('Question explicitement fournie')
  await studio(page)
  await page.locator(`[data-context-key="${file.key}"]`).click()
  await expect(panel.locator('[data-block-kind=group] > .ctx-block-content > .ctx-block-header .ctx-block-title')).toHaveText('Working system')
  await expect(panel.locator('[data-block-kind="emit"]')).toHaveCount(2)
  await manualSource(panel, 'question')
  await panel.getByLabel('Fournir question pour l’aperçu', { exact: true }).check()
  await panel.getByLabel('Valeur de question', { exact: true }).fill('Nouvelle observation')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment').nth(1)).toContainText('Nouvelle observation')
  await panel.getByRole('button', { name: 'Afficher le Rust de la stratégie', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Rust de la stratégie', exact: true }).locator('.ctx-rust-source')).toHaveText(source)
})

test('context studio preserves dirty workspace drafts and reports a real external source conflict', async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const workspaceB = await (await request.post('/api/workspaces', { data: { path: fixturePath('workspace-b') } })).json()
  const strategy: ContextStrategy = { version: 1, id: `context-conflict-${Date.now()}`, name: 'Source en conflit', requirements: {}, capabilities: [], program: [{ kind: 'emit', id: 'fragment', role: 'data', format: 'text', value: literal('Version disque') }] }
  const saved = await request.post('/api/context-strategies', { data: { workspaceId: health.defaultWorkspaceId, strategy } })
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const file: ContextFile = await saved.json()
  const panel = await studio(page)
  await page.locator(`[data-context-key="${file.key}"]`).click()
  await panel.getByRole('textbox', { name: /^Contenu du fragment ·/ }).fill('Brouillon préservé')
  await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(workspaceB.id)
  await expect(panel).toHaveAttribute('data-context-workspace', workspaceB.id)
  await panel.getByLabel('Nom de la stratégie', { exact: true }).fill('Brouillon du workspace B')
  await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(health.defaultWorkspaceId)
  await expect(panel.getByRole('textbox', { name: /^Contenu du fragment ·/ })).toHaveValue('Brouillon préservé')
  await writeFile(file.path, (await readFile(file.path, 'utf8')).replace('Version disque', 'Modification externe'))
  await page.getByRole('button', { name: 'Actualiser les stratégies', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: /^Contenu du fragment ·/ })).toHaveValue('Brouillon préservé')
  await panel.getByRole('button', { name: 'Enregistrer la stratégie', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('Votre brouillon est conservé')
  expect(await readFile(file.path, 'utf8')).toContain('Modification externe')
  await panel.getByRole('button', { name: 'Dupliquer la stratégie', exact: true }).click()
  await panel.getByRole('button', { name: 'Enregistrer la stratégie', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const files: ContextFile[] = await (await request.get(`/api/context-strategies?workspaceId=${health.defaultWorkspaceId}`)).json()
  const copy = files.find(item => item.strategy?.name === 'Source en conflit · copie')!
  expect(await readFile(copy.path, 'utf8')).toContain('Brouillon préservé')
  expect(copy.key).not.toBe(file.key)
  await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(workspaceB.id)
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue('Brouillon du workspace B')
})

for (const editing of [false, true]) test(`context catalogue arrival ${editing ? 'preserves an ongoing name replacement' : 'opens the default when untouched'}`, async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const workspaceB = await (await request.post('/api/workspaces', { data: { path: fixturePath('workspace-b') } })).json()
  const panel = await studio(page)
  let release!: () => void, received!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  const arrived = new Promise<void>(resolve => { received = resolve })
  await page.route(url => url.pathname === '/api/context-strategies' && url.searchParams.get('workspaceId') === workspaceB.id, async route => {
    const response = await route.fetch()
    received()
    await gate
    await route.fulfill({ response })
  })
  try {
    await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(workspaceB.id)
    await arrived
    await expect(panel).toHaveAttribute('data-context-workspace', workspaceB.id)
    const name = panel.getByLabel('Nom de la stratégie', { exact: true })
    await expect(name).toHaveValue('Nouvelle stratégie')
    if (editing) {
      await expect(name).toBeEditable()
      await name.focus()
      await page.keyboard.press('Control+a')
    }
    release()
    await expect(page.getByRole('button', { name: 'Actualiser les stratégies', exact: true })).toBeEnabled()
    if (editing) {
      await page.keyboard.insertText('Brouillon du workspace B')
      await expect(name).toHaveValue('Brouillon du workspace B')
      await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(health.defaultWorkspaceId)
      await expect(panel).toHaveAttribute('data-context-workspace', health.defaultWorkspaceId)
      await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(workspaceB.id)
      await expect(name).toHaveValue('Brouillon du workspace B')
      // Explicit navigation still opens the catalogue definition after an edit.
      await page.locator('[data-context-key="workspace-default"]').click()
    }
    await expect(name).toHaveValue('Assistant de workspace')
  } finally { release() }
})

test('context preview distinguishes inactive branches, structured needs and typed errors on narrow screens', async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const strategy: ContextStrategy = { version: 1, id: `context-conditional-${Date.now()}`, name: 'Contexte conditionnel', requirements: { optional: { kind: 'text' } }, capabilities: [], program: [{ kind: 'if', id: 'choice', condition: { kind: 'present', value: { kind: 'resource', name: 'optional' } }, then: [{ kind: 'emit', id: 'provided', role: 'data', format: 'text', value: { kind: 'resource', name: 'optional' } }], else: [{ kind: 'emit', id: 'fallback', role: 'instruction', format: 'text', value: literal('Continuer sans option') }] }] }
  const saved = await request.post('/api/context-strategies', { data: { workspaceId: health.defaultWorkspaceId, strategy } })
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const file: ContextFile = await saved.json()
  const panel = await studio(page)
  await page.locator(`[data-context-key="${file.key}"]`).click()
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toContainText('Continuer sans option')
  await expect(panel.locator('.ctx-needs')).toHaveCount(0)
  await panel.getByLabel('Opérateur de la condition', { exact: true }).selectOption('eq')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-needs')).toContainText('optional')
  await expect(panel.locator('.ctx-preview-fragment')).toHaveCount(0)
  await panel.getByLabel('Opérateur de la condition', { exact: true }).selectOption('present')
  await page.setViewportSize({ width: 720, height: 900 })
  await page.getByRole('button', { name: 'Masquer la navigation', exact: true }).click()
  await panel.getByRole('navigation', { name: 'Panneaux du studio' }).getByRole('button', { name: 'Sources', exact: true }).click()
  await manualSource(panel, 'optional')
  await panel.getByLabel('Fournir optional pour l’aperçu', { exact: true }).check()
  await panel.getByLabel('Valeur de optional', { exact: true }).fill('Option présente')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toContainText('Option présente')
  await page.screenshot({ path: test.info().outputPath('context-studio-mobile.png') })
  await panel.locator('.ctx-preview-fragment').click()
  await expect(panel.locator('[data-context-block="provided"]')).toHaveClass(/selected/)
  await panel.locator('[data-context-block="provided"]').getByRole('button', { name: 'Configurer le rôle et la représentation', exact: true }).click()
  await panel.locator('[data-context-block="provided"]').getByLabel('Représentation', { exact: true }).selectOption('media')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-alert[role=alert]')).toBeVisible()
  await expect(panel.getByRole('region', { name: 'Diagnostics de stratégie' })).toBeVisible()
  const dimensions = await page.evaluate(() => ({ viewport: window.innerWidth, content: document.documentElement.scrollWidth }))
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport)
})

test('a node binds a saved context strategy explicitly and uses its frozen Rust in the real fixture model call', async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const strategy: ContextStrategy = { version: 1, id: `context-node-${Date.now()}`, name: 'Question explicite du modèle', requirements: { question: { kind: 'text' } }, capabilities: [], program: [{ kind: 'emit', id: 'question-fragment', role: 'data', format: 'text', value: { kind: 'resource', name: 'question' } }] }
  const saved = await request.post('/api/context-strategies', { data: { workspaceId: health.defaultWorkspaceId, strategy } })
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const file: ContextFile = await saved.json()
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await designTemplate(page, 'autonomous')
  await page.locator('.flow-card.context').first().click()
  const binding = page.locator('.ctx-binding-editor')
  await binding.getByLabel('Stratégie Rust', { exact: true }).selectOption(file.key)
  await binding.getByLabel('Source de question', { exact: true }).selectOption('state')
  await binding.getByLabel('Champ d’état pour question', { exact: true }).fill('input')
  await binding.getByRole('button', { name: 'Vérifier les contrats', exact: true }).click()
  await expect(binding.getByRole('status')).toContainText('Contrats de types et capacités vérifiés')
  await binding.getByRole('button', { name: 'Ouvrir le studio de contexte', exact: true }).click()
  await expect(page.locator('.context-studio:not(.bridge-studio)').getByLabel('Nom de la stratégie', { exact: true })).toHaveValue(strategy.name)
  await page.getByRole('navigation', { name: 'Espace de conception' }).getByRole('button', { name: 'Flows', exact: true }).click()
  await expect(binding.getByLabel('Champ d’état pour question', { exact: true })).toHaveValue('input')
  await page.getByRole('button', { name: 'Utiliser', exact: true }).click()
  const started = page.waitForResponse(response => new URL(response.url()).pathname === '/api/runs' && response.request().method() === 'POST')
  await page.getByLabel('Donnée d’entrée',{exact:true}).fill('Demande transmise par la stratégie')
  await page.getByRole('button',{name:'Lancer l’exécution',exact:true}).click()
  const response = await started
  expect(response.ok(), await response.text()).toBeTruthy()
  const ack = await response.json()
  const run = await waitRun(request, ack.id, 'completed')
  const model = run.composition.nodes.find(node => node.data.kind === 'context')!
  expect(model.data.config.contextProgram.strategy).toEqual(strategy)
  expect(model.data.config.contextProgram.hash).toBe(file.hash)
  expect(model.data.config.contextProgram.source).toBe(await readFile(file.path, 'utf8'))
  expect(run.messages.at(-1)?.text).toContain('Demande transmise par la stratégie')
})

test('the visual library editor persists a typed function in Rust and an explicit call uses that catalogue', async ({ page, request }) => {
  const health = await (await request.get('/api/health')).json()
  const panel = await studio(page)
  await panel.getByRole('navigation', { name: 'Éditeur de contexte' }).getByRole('button', { name: 'Bibliothèques de fonctions', exact: true }).click()
  const editor = panel.getByRole('region', { name: 'Éditeur de bibliothèques' })
  const key = `library-ui-${Date.now()}`
  await editor.getByLabel('Identifiant de la bibliothèque', { exact: true }).fill(key)
  await editor.getByLabel('Nom de la fonction', { exact: true }).fill('identity')
  await editor.getByLabel('Nom de la fonction', { exact: true }).press('Enter')
  await editor.getByLabel('Nom du paramètre', { exact: true }).fill('message')
  await editor.getByLabel('Nom du paramètre', { exact: true }).press('Enter')
  await editor.getByLabel('Corps de la fonction', { exact: true }).selectOption('variable')
  await editor.getByLabel('Variable locale', { exact: true }).selectOption('message')
  await editor.getByRole('button', { name: 'Enregistrer la bibliothèque', exact: true }).click()
  await expect(editor.getByRole('status')).toContainText('Bibliothèque enregistrée en Rust')
  const response = await request.get(`/api/context-libraries/${key}?workspaceId=${health.defaultWorkspaceId}`)
  expect(response.ok(), await response.text()).toBeTruthy()
  const file = await response.json()
  expect(file.library.projections.identity).toEqual({ parameters: { message: { kind: 'text' } }, output: { kind: 'text' }, body: { kind: 'variable', name: 'message' } })
  expect(file.path).toContain(fixturePath('workspace-a', '.zedflow', 'context', 'libraries'))
  expect(await readFile(file.path, 'utf8')).toBe(file.source)
  expect(file.source).toContain('ContextExpr::variable')
  await panel.getByRole('navigation', { name: 'Éditeur de contexte' }).getByRole('button', { name: 'Stratégie', exact: true }).click()
  await panel.getByLabel('Nom de la stratégie', { exact: true }).fill('Appel de projection visuel')
  await dependencies(panel)
  await panel.getByLabel('Bibliothèque de fonctions', { exact: true }).selectOption(key)
  await addBlock(page, panel.locator('.ctx-program-panel'), 'Fragment')
  const block = panel.locator('[data-block-kind="emit"]')
  await (await expressionDetails(block)).selectOption('call')
  await block.getByLabel('Programme', { exact: true }).fill('identity')
  await block.getByLabel('Nom du paramètre', { exact: true }).fill('message')
  await block.getByLabel('Nom du paramètre', { exact: true }).press('Enter')
  await block.getByRole('textbox', { name: 'message', exact: true }).fill('Résultat du sous-programme pur')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toContainText('Résultat du sous-programme pur')
  await panel.getByRole('button', { name: 'Enregistrer la stratégie', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const strategyFiles: ContextFile[] = await (await request.get(`/api/context-strategies?workspaceId=${health.defaultWorkspaceId}`)).json()
  const strategy = strategyFiles.find(file => file.strategy?.name === 'Appel de projection visuel')!
  await studio(page)
  await page.locator(`[data-context-key="${strategy.key}"]`).click()
  // The composition owns catalogue selection; it is explicit again in a fresh preview.
  await dependencies(panel)
  await panel.getByLabel('Bibliothèque de fonctions', { exact: true }).selectOption(key)
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toContainText('Résultat du sous-programme pur')
})

test('the block editor constructs a named projection and emits it as JSON in a v2 strategy',async({page,request})=>{
  const workspaceId=(await(await request.get('/api/health')).json()).defaultWorkspaceId
  const types={Personne:{kind:'record',fields:{name:{kind:'text'}}}}
  const strategy={version:2,id:`construct-${crypto.randomUUID()}`,name:'Projection nominale',requirements:{document:{kind:'record',fields:{name:{kind:'text'},extra:{kind:'text'}}}},capabilities:[],program:[{kind:'emit',id:'person',role:'data',format:'json',value:{kind:'literal',dataType:{kind:'text'},value:''}}]}
  const saved=await request.post('/api/context-strategies',{data:{workspaceId,strategy}});expect(saved.ok(),await saved.text()).toBeTruthy();const file=await saved.json()
  const typeSave=await request.post('/api/context-types',{data:{workspaceId,key:`types-${strategy.id}`,types}});expect(typeSave.ok(),await typeSave.text()).toBeTruthy();const typesFile=await typeSave.json()
  const panel=await studio(page);await page.locator(`[data-context-key="${file.key}"]`).click()
  await dependencies(panel)
  await panel.getByLabel('Catalogue de types',{exact:true}).selectOption(typesFile.key)
  const block=panel.locator('[data-context-block="person"]')
  await (await expressionDetails(block)).selectOption('construct')
  await block.getByLabel('Type construit',{exact:true}).selectOption('Personne')
  await block.getByRole('button',{name:'Configurer l’expression : Source',exact:true}).click()
  await block.getByRole('combobox',{name:'Source',exact:true}).selectOption('project')
  await block.getByLabel('Champs sélectionnés',{exact:true}).fill('name')
  await block.getByLabel('Champs sélectionnés',{exact:true}).press('Tab')
  await manualSource(panel, 'document')
  await panel.getByLabel('Fournir document pour l’aperçu',{exact:true}).check()
  const resource=panel.locator('[data-resource="document"]')
  await resource.getByLabel('name',{exact:true}).fill('Ada')
  await resource.getByLabel('extra',{exact:true}).fill('Champ exclu')
  await panel.getByRole('button',{name:'Prévisualiser',exact:true}).click()
  await expect(panel.locator('.ctx-preview-fragment')).toContainText('Ada')
  await expect(panel.locator('.ctx-preview-fragment')).not.toContainText('Champ exclu')
  await page.screenshot({path:test.info().outputPath('context-engine-editor.png')})
  await panel.getByRole('button',{name:'Enregistrer la stratégie',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const result=await(await request.get(`/api/context-strategies/${file.key}?workspaceId=${workspaceId}`)).json()
  expect(result.source).toContain('ContextStrategy::new_v2')
  expect(result.source).toContain('ContextExpr::construct')
  expect(result.strategy.program[0].value).toEqual({kind:'construct',name:'Personne',value:{kind:'project',value:{kind:'resource',name:'document'},fields:['name']}})
})

test('legacy context conversion creates an explicit v2 copy without rewriting its source',async({page,request})=>{
  const workspaceId=(await(await request.get('/api/health')).json()).defaultWorkspaceId
  const strategy={version:1,id:`convert-${crypto.randomUUID()}`,name:'Contexte historique',requirements:{history:{kind:'list',item:{kind:'record',fields:{role:{kind:'text'},text:{kind:'text'}}}}},capabilities:[],program:[{kind:'emit',id:'history',role:'data',format:'json',value:{kind:'resource',name:'history'}}]}
  const saved=await request.post('/api/context-strategies',{data:{workspaceId,strategy}});expect(saved.ok(),await saved.text()).toBeTruthy();const file=await saved.json()
  const panel=await studio(page);await page.locator(`[data-context-key="${file.key}"]`).click()
  await panel.getByRole('button',{name:'Créer une copie v2',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Créer une copie de contexte v2'})
  await dialog.getByRole('button',{name:'Créer le brouillon v2',exact:true}).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByLabel('Représentation v2 de history',{exact:true}).selectOption('adkMessages')
  await dialog.getByRole('button',{name:'Créer le brouillon v2',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await panel.getByRole('button',{name:'Configurer le rôle et la représentation',exact:true}).click()
  await expect(panel.getByLabel('Représentation',{exact:true})).toHaveValue('adkMessages')
  await panel.getByRole('button',{name:'Enregistrer la stratégie',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const retained=await(await request.get(`/api/context-strategies/${file.key}?workspaceId=${workspaceId}`)).json();expect(retained.hash).toBe(file.hash);expect(retained.source).toBe(file.source)
  const files=await(await request.get(`/api/context-strategies?workspaceId=${workspaceId}`)).json()
  const copy=files.find((item:any)=>item.strategy?.id===`${strategy.id}-v2`)
  expect(copy.strategy.version).toBe(2);expect(copy.strategy.program[0].format).toBe('adkMessages')
})
