import { test, expect, type Page, type Locator } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import { fixturePath } from './helpers'

async function studio(page: Page) {
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await page.getByRole('navigation', { name: 'Espace de conception' }).getByRole('button', { name: 'Contexte', exact: true }).click()
  return page.getByRole('region', { name: 'Studio de contexte', exact: true })
}

async function manualSource(panel: Locator, name: string) {
  const source = panel.locator(`[data-resource="${name}"]`)
  const disclosure = source.locator('.ctx-source-disclosure')
  if (await disclosure.getAttribute('aria-expanded') !== 'true') await disclosure.click()
  const manual = source.locator('details').filter({ hasText: `Fournir ${name} pour l’aperçu` })
  if (await manual.getAttribute('open') === null) await manual.locator('summary').click()
  return source
}
async function declareTextSource(page: Page, panel: Locator, name: string) {
  await panel.getByRole('button', { name: 'Ajouter des types', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Ajouter des types de sources', exact: true })
  await dialog.getByText('Définir un type personnalisé', { exact: true }).click()
  await dialog.getByLabel('Nom du type personnalisé', { exact: true }).fill(name)
  await dialog.getByLabel('Schéma du type personnalisé', { exact: true }).selectOption('text')
  await dialog.getByRole('button', { name: 'Déclarer ce type', exact: true }).click()
}

test('the default context is opened from its real catalogue while new drafts survive refresh', async ({ page, request }) => {
  const workspacePath = fixturePath(`context-guide-${crypto.randomUUID()}`)
  await mkdir(workspacePath, { recursive: true })
  const opened = await request.post('/api/workspaces', { data: { path: workspacePath } })
  expect(opened.ok(), await opened.text()).toBeTruthy()
  const workspace = await opened.json()
  const files = await (await request.get(`/api/context-strategies?workspaceId=${workspace.id}`)).json()
  const existing = files.find((file: { key: string }) => file.key === 'workspace-default')
  const saved = await request.post('/api/context-strategies', { data: {
    workspaceId: workspace.id, ...(existing ? { expectedHash: existing.hash } : {}),
    strategy: { version: 2, id: 'workspace-default', name: 'Contexte disponible du workspace', requirements: {}, capabilities: [], program: [
      { kind: 'emit', id: 'default-instruction', role: 'instruction', format: 'text', value: { kind: 'literal', dataType: { kind: 'text' }, value: 'Consigne du workspace de test' } },
    ] },
  } })
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const file = await saved.json()
  const panel = await studio(page)
  await page.getByLabel('Workspace des stratégies', { exact: true }).selectOption(workspace.id)
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue('Contexte disponible du workspace')
  await expect(page.locator(`[data-context-key="${file.key}"]`)).toHaveClass(/chosen/)
  await page.getByRole('button', { name: 'Créer une stratégie', exact: true }).click()
  await panel.getByLabel('Nom de la stratégie', { exact: true }).fill('Mon brouillon conservé')
  await page.getByRole('button', { name: 'Actualiser les stratégies', exact: true }).click()
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue('Mon brouillon conservé')
  await expect(page.locator('.ctx-library:visible .ctx-file.chosen')).toContainText('Mon brouillon conservé')
  const current = await (await request.get(`/api/context-strategies/workspace-default?workspaceId=${workspace.id}`)).json()
  expect(current.hash).toBe(file.hash)
})

test('the guided example previews real resource values and saves a reusable program without its trial data', async ({ page, request }) => {
  const panel = await studio(page)
  await page.getByRole('button', { name: 'Créer une stratégie', exact: true }).click()
  await panel.getByLabel('Nom de la stratégie', { exact: true }).fill('Travail avant l’exemple')
  const guide = panel.getByRole('region', { name: 'Guide de composition du contexte', exact: true })
  await guide.getByRole('button', { name: 'Comprendre les blocs', exact: true }).click()
  await expect(guide).toContainText('Une déclaration n’injecte aucun contenu')
  await guide.getByRole('button', { name: 'Instructions et demande', exact: true }).click()
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue('Instructions et demande')
  await manualSource(panel, 'question')
  await panel.getByLabel('Valeur de question', { exact: true }).fill('Une question qui reste dans cet aperçu')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toHaveCount(2)
  await expect(panel.locator('.ctx-preview-fragment').first()).toContainText('Répondez en français')
  await expect(panel.locator('.ctx-preview-fragment').nth(1)).toContainText('Une question qui reste dans cet aperçu')
  await panel.locator('.ctx-preview-fragment').nth(1).click()
  await expect(panel.locator('[data-context-block="question"]')).toHaveClass(/selected/)
  await panel.getByRole('button', { name: 'Enregistrer la stratégie', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Stratégie enregistrée en Rust')
  const workspaceId = await panel.getAttribute('data-context-workspace')
  const files = await (await request.get(`/api/context-strategies?workspaceId=${workspaceId}`)).json()
  const saved = files.find((file: { strategy?: { name: string } }) => file.strategy?.name === 'Instructions et demande')
  expect(saved.strategy.requirements.question).toEqual({ kind: 'text' })
  expect(saved.strategy.program[1].value).toEqual({ kind: 'resource', name: 'question' })
  expect(await readFile(saved.path, 'utf8')).not.toContain('Une question qui reste dans cet aperçu')
  await page.screenshot({ path: test.info().outputPath('context-guided-example.png') })
  await page.locator('.ctx-library .ctx-file').filter({ hasText: 'Travail avant l’exemple' }).click()
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue('Travail avant l’exemple')
  await expect(panel.locator('[data-context-block]')).toHaveCount(0)
})

test('a conditional example switches branches and a declared resource enters the program explicitly on a narrow screen', async ({ page }) => {
  const panel = await studio(page)
  await page.getByRole('button', { name: 'Créer une stratégie', exact: true }).click()
  await panel.getByRole('button', { name: 'Comprendre les blocs', exact: true }).click()
  await panel.getByRole('button', { name: 'Résultat d’outil conditionnel', exact: true }).click()
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment').nth(1)).toContainText('La documentation décrit trois étapes')
  await manualSource(panel, 'toolResult')
  await panel.getByLabel('Fournir toolResult pour l’aperçu', { exact: true }).uncheck()
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment').nth(1)).toContainText('Aucun résultat d’outil disponible')
  await expect(panel.locator('.ctx-needs')).toHaveCount(0)
  await page.setViewportSize({ width: 720, height: 900 })
  await page.getByRole('button', { name: 'Masquer la navigation', exact: true }).click()
  const tabs = panel.getByRole('navigation', { name: 'Panneaux du studio', exact: true })
  await tabs.getByRole('button', { name: 'Sources', exact: true }).click()
  await declareTextSource(page, panel, 'note')
  await manualSource(panel, 'note')
  await panel.getByLabel('Fournir note pour l’aperçu', { exact: true }).check()
  await panel.getByLabel('Valeur de note', { exact: true }).fill('Une donnée ajoutée depuis Sources')
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toHaveCount(2)
  await tabs.getByRole('button', { name: 'Sources', exact: true }).click()
  await panel.getByRole('button', { name: 'Ajouter note au programme', exact: true }).click()
  await page.getByRole('dialog', { name: 'Insérer un champ dans le programme', exact: true }).getByRole('button', { name: 'Ajouter ce champ au contexte', exact: true }).click()
  const block = panel.locator('.ctx-program-panel > fieldset > .ctx-block-list > .ctx-block').last()
  await expect(block.locator('.ctx-source-token')).toContainText('note')
  await block.getByRole('button', { name: /^Configurer l’expression : Contenu du fragment/ }).click()
  await expect(block.getByLabel('Ressource', { exact: true })).toHaveValue('note')
  const transformer = block.getByRole('button', { name: 'Transformer cette expression', exact: true })
  await transformer.click()
  await expect(page.getByRole('menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).not.toBeVisible()
  await expect(transformer).toBeFocused()
  await transformer.click()
  const outside = await page.locator('.context-studio:not(.bridge-studio) .ctx-strategy-title input').boundingBox()
  expect(outside).not.toBeNull()
  await page.mouse.click(outside!.x + 8, outside!.y + 8)
  await expect(page.getByRole('menu')).not.toBeVisible()
  await panel.getByRole('button', { name: 'Prévisualiser', exact: true }).click()
  await expect(panel.locator('.ctx-preview-fragment')).toHaveCount(3)
  await expect(panel.locator('.ctx-preview-fragment').last()).toContainText('Une donnée ajoutée depuis Sources')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('context-guided-mobile.png') })
})
