import { expect, test } from '@playwright/test'
import { conversationToolsDocumentsExample } from './fixtures/context-example'

test('structured studio matches the reference states and preserves precise preview navigation', async ({ page, request }) => {
  await page.setViewportSize({ width: 1922, height: 912 })
  const health = await (await request.get('/api/health')).json()
  const { strategy } = conversationToolsDocumentsExample(`structured-${crypto.randomUUID()}`)
  const saved = await request.post('/api/context-strategies', { data: { workspaceId: health.defaultWorkspaceId, strategy } })
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const file = await saved.json()
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await page.getByRole('navigation', { name: 'Espace de conception' }).getByRole('button', { name: 'Contexte', exact: true }).click()
  await page.getByRole('button', { name: 'Créer une stratégie', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Studio de contexte', exact: true })
  await expect(panel.locator('[data-resource]')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('01-empty-strategy.png') })
  await panel.getByRole('button', { name: 'Ajouter des types', exact: true }).click()
  const gallery = page.getByRole('dialog', { name: 'Ajouter des types de sources' })
  await expect(gallery.getByLabel('Sélectionner Instructions', { exact: true })).toBeVisible()
  for (const name of ['Instructions', 'Message utilisateur', 'Sortie du modèle', 'Appel d’outil', 'Résultat d’outil', 'Document']) await gallery.getByLabel(`Sélectionner ${name}`, { exact: true }).first().check()
  await page.screenshot({ path: test.info().outputPath('02-source-type-gallery.png') })
  await page.keyboard.press('Escape')
  await expect(panel.getByRole('button', { name: 'Ajouter des types', exact: true })).toBeFocused()
  await panel.getByRole('button', { name: 'Comprendre les blocs', exact: true }).click()
  await panel.getByRole('button', { name: 'Conversation, outils et documents', exact: true }).click()
  await expect(panel.locator('[data-resource]')).toHaveCount(6)
  await expect(panel.locator('.ctx-preview-footer')).toContainText('Aperçu à jour')
  await expect(panel.locator('[data-origin-block="document-excerpt"]')).toHaveCount(1)
  await page.locator(`[data-context-key="${file.key}"]`).click()
  await expect(panel.getByLabel('Nom de la stratégie', { exact: true })).toHaveValue(strategy.name)
  await panel.getByLabel('Jeu de données d’essai', { exact: true }).selectOption('failure')
  await expect(panel.locator('[data-tool-call-id="17"]')).toHaveCount(1)
  await expect(panel.locator('[data-tool-result-id="17"]')).toHaveCount(1)
  await expect(panel.locator('.ctx-preview-footer')).toContainText('Aperçu à jour')
  await expect(panel.locator('.ctx-preview-panel')).toContainText('Fichier indisponible : docs/terms.md')
  await expect(panel.locator('.ctx-diagnostics')).toHaveCount(0)
  await panel.getByRole('button', { name: 'Déplier la source toolResult', exact: true }).click()
  await page.screenshot({ path: test.info().outputPath('03-field-composition.png') })
  const separator = panel.getByRole('separator', { name: 'Largeur du panneau Sources' })
  const before = Number(await separator.getAttribute('aria-valuenow'))
  await separator.focus(); await page.keyboard.press('ArrowRight')
  expect(Number(await separator.getAttribute('aria-valuenow'))).toBe(before + 16)
  await page.keyboard.press('ArrowLeft')
  await panel.getByRole('button', { name: 'Structure', exact: true }).click()
  await expect(panel.locator('.ctx-result-structure')).toContainText(['Instruction', 'Donnée', 'Donnée', 'Donnée', 'Donnée'])
  await panel.locator('[data-origin-block="document-excerpt"] .ctx-result-title').click()
  await expect(panel.locator('[data-context-block="document-excerpt"]')).toHaveClass(/selected/)
  await panel.getByRole('button', { name: 'Voir la trace', exact: true }).click()
  const trace = page.getByRole('dialog', { name: 'Trace de composition du contexte' })
  await expect(trace).toContainText('documents-loop')
  await expect(trace).toContainText('Vrai')
  await page.keyboard.press('Escape')
  await panel.getByRole('button', { name: 'Contexte', exact: true }).click()
  await panel.getByRole('button', { name: 'Voir les valeurs', exact: true }).click()
  const fixtures = page.getByRole('dialog', { name: 'Données d’essai du contexte' })
  await fixtures.getByRole('button', { name: 'JSON', exact: true }).click()
  const values = JSON.parse(await fixtures.getByLabel('Valeurs JSON des sources').inputValue())
  values.documents.push({ title: 'Deuxième document', content: 'Contenu associé au second élément', path: 'docs/second.md' })
  await fixtures.getByLabel('Valeurs JSON des sources').fill(JSON.stringify(values))
  await fixtures.getByRole('button', { name: 'Appliquer les valeurs JSON' }).click()
  await page.keyboard.press('Escape')
  await expect(panel.locator('[data-origin-block="document-excerpt"]')).toHaveCount(2)
  const occurrences = await panel.locator('[data-origin-block="document-excerpt"]').evaluateAll(elements => elements.map(element => element.getAttribute('data-fragment-id')))
  expect(new Set(occurrences).size).toBe(2)
  await panel.locator('[data-origin-block="document-excerpt"] .ctx-result-title').last().click()
  await expect(panel.locator('[data-origin-block="document-excerpt"].selected')).toHaveCount(1)
  await expect(panel.locator('[data-origin-block="document-excerpt"].selected')).toHaveAttribute('data-fragment-id', occurrences[1]!)
  await page.setViewportSize({ width: 720, height: 900 })
  await page.getByRole('button', { name: 'Fermer la navigation', exact: true }).click()
  const tabs = panel.getByRole('navigation', { name: 'Panneaux du studio' })
  await tabs.getByRole('button', { name: 'Aperçu', exact: true }).click()
  await expect(panel.locator('[data-origin-block="document-excerpt"]').last()).toContainText('Deuxième document')
  await page.screenshot({ path: test.info().outputPath('04-narrow-preview.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(720)
})
