import { test, expect } from '@playwright/test'
import { legacyTemplate as template } from './fixtures/templates'
import { openSession, waitRun } from './helpers'

test('a captured context window is revised visually and selected explicitly for exactly the next model pass',async({page,request})=>{
  const health=await(await request.get('/api/health')).json(),workspaceId=health.defaultWorkspaceId
  const strategy={version:1,id:`window-ui-${Date.now()}`,name:'Fenêtre contrôlée',requirements:{question:{kind:'text'}},capabilities:[],program:[{kind:'group',id:'instructions',label:'Instructions',items:[{kind:'emit',id:'instruction',role:'instruction',format:'text',value:{kind:'literal',dataType:{kind:'text'},value:'Consigne originale'}}]},{kind:'group',id:'documents',label:'Documents',items:[{kind:'emit',id:'question',role:'data',format:'text',value:{kind:'resource',name:'question'}}]}]}
  const saved=await request.post('/api/context-strategies',{data:{workspaceId,strategy}});expect(saved.ok(),await saved.text()).toBeTruthy();const context=await saved.json()
  const composition=template(true),node=composition.nodes.find(node=>node.data.kind==='agent')!
  node.data.config.contextStrategy={key:context.key,hash:context.hash};node.data.config.contextBindings={question:{kind:'state',field:'input'}};node.data.config.contextWindow={alias:'working-window'}
  const stored=await request.post('/api/flows',{data:{workspaceId,composition}});expect(stored.ok(),await stored.text()).toBeTruthy();const flow=await stored.json()
  const started=await request.post('/api/runs',{data:{workspaceId,flowKey:flow.key,flowHash:flow.hash,input:{input:'Question initiale'}}});expect(started.ok(),await started.text()).toBeTruthy();const ack=await started.json()
  await waitRun(request,ack.id,'waiting',workspaceId)
  await page.goto('/');await expect(page.getByText('Daemon connecté',{exact:true})).toBeVisible();await openSession(page,ack.id,workspaceId)
  await page.getByRole('button',{name:'Afficher les détails',exact:true}).click();await page.getByRole('tab',{name:'Contexte',exact:true}).click()
  const panel=page.getByRole('region',{name:'Fenêtre de contexte révisable'})
  await expect(panel).toBeVisible();await expect(panel).toContainText('Consigne originale')
  const originalRevision=await panel.getByLabel('Révision de la fenêtre',{exact:true}).inputValue()
  const initial=await(await request.get(`/api/runs/${ack.id}/context-window?workspaceId=${workspaceId}&nodePath=model&alias=working-window&revision=${originalRevision}`)).json()
  await panel.getByRole('button',{name:'Inspecter le fragment instruction',exact:true}).click()
  await panel.getByLabel('Valeur du fragment',{exact:true}).fill('Consigne éditée explicitement')
  await panel.getByRole('button',{name:'Enregistrer cette représentation',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Nouvelle révision enregistrée')
  let changedRevision=await panel.getByLabel('Révision de la fenêtre',{exact:true}).inputValue();expect(changedRevision).not.toBe(originalRevision)
  await panel.getByLabel('Révision de la fenêtre',{exact:true}).selectOption(originalRevision)
  await expect(panel).toContainText('Consigne originale');await expect(panel.getByRole('button',{name:'Enregistrer cette représentation',exact:true})).toBeDisabled()
  await panel.getByLabel('Révision de la fenêtre',{exact:true}).selectOption(changedRevision)
  await expect(panel.locator('[data-fragment-id="instruction"]')).toContainText('Consigne éditée explicitement')
  await panel.getByRole('button',{name:'Voir la définition de ce fragment',exact:true}).click()
  const definition=page.getByRole('dialog',{name:'Définition de contexte exécutée'})
  await expect(definition.locator('[data-frozen-block="instruction"]')).toBeVisible()
  await expect(definition.getByLabel('Valeur littérale',{exact:true})).toHaveValue('Consigne originale')
  await definition.getByRole('button',{name:'Source Rust exacte',exact:true}).click()
  await expect(definition.locator('.source-preview')).toContainText('Consigne originale')
  await expect(definition.locator('.source-preview')).not.toContainText('Consigne éditée explicitement')
  await page.keyboard.press('Escape')
  const old=await(await request.get(`/api/runs/${ack.id}/context-window?workspaceId=${workspaceId}&nodePath=model&alias=working-window&revision=${originalRevision}`)).json();expect(old).toEqual(initial)
  await panel.getByRole('button',{name:'Inspecter le fragment question',exact:true}).click()
  await panel.locator('.window-relocate>summary').click()
  await panel.getByLabel('Groupe de destination',{exact:true}).selectOption('instructions')
  await panel.getByRole('button',{name:'Déplacer l’élément',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Nouvelle révision enregistrée')
  await expect(panel.locator('[data-fragment-id="instructions"] [data-fragment-id="question"]')).toBeVisible()
  await panel.getByRole('button',{name:'Inspecter le groupe documents',exact:true}).click()
  await panel.getByRole('button',{name:'Remplacer cet élément',exact:true}).click()
  const replacement=page.getByRole('dialog',{name:'Remplacer un élément de fenêtre'})
  await replacement.getByLabel('Nom du groupe de fenêtre',{exact:true}).fill('Documents révisés')
  await replacement.getByRole('button',{name:'Ajouter un fragment',exact:true}).click()
  await replacement.getByLabel('Contenu du remplacement',{exact:true}).fill('Ajout explicite de fenêtre')
  await replacement.getByRole('button',{name:'Enregistrer le remplacement',exact:true}).click()
  await expect(replacement).not.toBeVisible()
  await expect(panel).toContainText('Ajout explicite de fenêtre')
  changedRevision=await panel.getByLabel('Révision de la fenêtre',{exact:true}).inputValue()
  const selection=page.waitForResponse(response=>new URL(response.url()).pathname.endsWith('/context-window/select')&&response.request().method()==='POST')
  await panel.getByRole('button',{name:'Utiliser cette révision au prochain passage',exact:true}).click()
  const selected=await selection;expect(selected.ok(),await selected.text()).toBeTruthy();await expect(panel.getByRole('status')).toContainText('sélectionnée pour le prochain passage')
  const command=selected.request().postDataJSON();expect(command.revision).toBe(changedRevision);expect(command.programHash).toBe(initial.window.programRevision||initial.window.strategyRevision)
  await page.getByRole('button',{name:'Fermer les détails',exact:true}).click()
  await page.locator('.composer textarea').fill('Deuxième passage');await page.locator('.composer textarea').press('Enter')
  await expect.poll(async()=>{const run=await(await request.get(`/api/runs/${ack.id}?workspaceId=${workspaceId}`)).json();return run.status==='waiting'?run.activities.filter((item:any)=>item.node==='model'&&item.status==='completed').length:0}).toBe(2)
  const after=await(await request.get(`/api/runs/${ack.id}?workspaceId=${workspaceId}`)).json()
  expect(JSON.stringify(after.contextSnapshots)).toContain(command.id)
  expect(JSON.stringify(after.contextSnapshots)).toContain('Consigne éditée explicitement')
  await page.locator('.composer textarea').fill('Troisième passage frais');await page.locator('.composer textarea').press('Enter')
  await expect.poll(async()=>{const run=await(await request.get(`/api/runs/${ack.id}?workspaceId=${workspaceId}`)).json();return run.status==='waiting'?run.activities.filter((item:any)=>item.node==='model'&&item.status==='completed').length:0}).toBe(3)
  const fresh=await(await request.get(`/api/runs/${ack.id}?workspaceId=${workspaceId}`)).json()
  expect(JSON.stringify(fresh.contextSnapshots.at(-1))).not.toContain(command.id)
  expect(JSON.stringify(fresh.contextSnapshots.at(-1))).toContain('Consigne originale')
  expect(JSON.stringify(fresh.contextSnapshots.at(-1))).not.toContain('Consigne éditée explicitement')
  await page.screenshot({path:test.info().outputPath('context-window-revised.png')})
})

test('a historical window opens its exact program when the same Rust strategy used two type revisions',async({page,request})=>{
  const workspaceId=(await(await request.get('/api/health')).json()).defaultWorkspaceId,key=`window-types-${crypto.randomUUID()}`
  const typeSave=await request.post('/api/context-types',{data:{workspaceId,key,types:{Document:{kind:'text'}}}});expect(typeSave.ok(),await typeSave.text()).toBeTruthy();const types=await typeSave.json()
  const strategy={version:1,id:`strategy-${crypto.randomUUID()}`,name:'Source constante',requirements:{},capabilities:[],program:[{kind:'emit',id:'instruction',role:'instruction',format:'text',value:{kind:'literal',dataType:{kind:'text'},value:'Même source de stratégie'}}]}
  const saved=await request.post('/api/context-strategies',{data:{workspaceId,strategy}});expect(saved.ok(),await saved.text()).toBeTruthy();const context=await saved.json()
  const composition=template(true),node=composition.nodes.find(node=>node.id==='model')!
  node.data.config.contextStrategy={key:context.key,hash:context.hash};node.data.config.contextTypesRef={key,hash:types.hash};node.data.config.contextWindow={alias:'same-source'}
  const stored=await request.post('/api/flows',{data:{workspaceId,composition}});expect(stored.ok(),await stored.text()).toBeTruthy();const flow=await stored.json()
  const started=await request.post('/api/runs',{data:{workspaceId,flowKey:flow.key,flowHash:flow.hash,input:{input:'Premier programme'}}});expect(started.ok(),await started.text()).toBeTruthy();const ack=await started.json(),first=await waitRun(request,ack.id,'waiting',workspaceId)
  const windowPath=`/api/runs/${ack.id}/context-window?workspaceId=${workspaceId}&nodePath=model&alias=same-source`
  const original=await(await request.get(windowPath)).json()
  const updated=await request.post('/api/context-types',{data:{workspaceId,key,types:{Document:{kind:'number'}},expectedHash:types.hash}});expect(updated.ok(),await updated.text()).toBeTruthy()
  const answered=await request.post(`/api/runs/${ack.id}/answer?workspaceId=${workspaceId}`,{data:{waitId:first.wait!.id,value:'Deuxième programme'}});expect(answered.ok(),await answered.text()).toBeTruthy()
  await expect.poll(async()=>{const run=await(await request.get(`/api/runs/${ack.id}?workspaceId=${workspaceId}`)).json();return run.status==='waiting'?run.activities.filter((item:any)=>item.node==='model'&&item.status==='completed').length:0}).toBe(2)
  const current=await(await request.get(windowPath)).json()
  expect(current.window.strategyRevision).toBe(original.window.strategyRevision)
  expect(current.window.programRevision).not.toBe(original.window.programRevision)
  await page.goto('/');await openSession(page,ack.id,workspaceId)
  await page.getByRole('button',{name:'Afficher les détails',exact:true}).click()
  await page.locator('.passage-index [data-node="model"]').first().click()
  await page.getByLabel('Passage du nœud',{exact:true}).selectOption(first.activities!.find(item=>item.node==='model')!.occurrenceId)
  await page.getByRole('tab',{name:'Contexte',exact:true}).click()
  const panel=page.getByRole('region',{name:'Fenêtre de contexte révisable'})
  await expect(panel.getByLabel('Révision de la fenêtre',{exact:true})).toHaveValue(original.revision)
  await panel.getByRole('button',{name:'Inspecter le fragment instruction',exact:true}).click()
  const program=page.waitForResponse(response=>new URL(response.url()).pathname.endsWith('/context-program'))
  await panel.getByRole('button',{name:'Voir la définition de ce fragment',exact:true}).click()
  const response=await program;expect(response.ok(),await response.text()).toBeTruthy()
  expect(new URL(response.url()).searchParams.get('hash')).toBe(original.window.programRevision)
  const exact=await response.json();expect(exact.types.Document.kind).toBe('text');expect(exact.typeSources[0].hash).toBe(types.hash)
  const dialog=page.getByRole('dialog',{name:'Définition de contexte exécutée'})
  await dialog.locator('.frozen-context-source summary').click()
  await expect(dialog.locator('.frozen-context-source')).toContainText('DataType::Text')
  await expect(dialog.locator('.frozen-context-source')).not.toContainText('DataType::Number')
  await page.screenshot({path:test.info().outputPath('context-engine-window-program.png')})
})
