import { test, expect, type Page } from '@playwright/test'
import type { Composition, FlowFile } from '@zedflow/sdk'
import { harnessTemplate, legacyHarnessTemplate, legacyTemplate, template } from './fixtures/templates'
import { parallelJoinFixture } from './fixtures/templates'
import { saveFlow, waitRun } from './helpers'

async function authoring(page: Page, composition: Composition) {
  let saved = structuredClone(composition)
  let savedWorkspace: string | undefined
  const file = (): FlowFile => ({key:saved.id,id:saved.id,name:saved.name,composition:saved,path:`/fixture/.zedflow/flows/${saved.id}.rs`,scope:'workspace',workspaceId:'pair-workspace',hash:'fixture-hash',diagnostics:[]})
  await page.route('**/api/**', async route => {
    const request=route.request(),path=new URL(request.url()).pathname.replace('/api','')
    const respond=(value:unknown)=>route.fulfill({contentType:'application/json',body:JSON.stringify(value)})
    if(path==='/health')return respond({defaultWorkspaceId:'pair-workspace',workspace:{host:'fixture',path:'/fixture'}})
    if(path==='/workspaces')return respond([{id:'pair-workspace',name:'Fixture',path:'/fixture',open:true},{id:'other-workspace',name:'Autre workspace',path:'/other',open:true}])
    if(path==='/runs')return respond([])
    if(path==='/context')return respond({instructions:[],skills:[],diagnostics:[]})
    if(path==='/context-strategies')return respond([{key:'harness-default',hash:'context-hash',path:'/fixture/.zedflow/context/harness-default.rs',strategy:{version:2,id:'harness-default',name:'Contexte du workspace',requirements:{instructions:{kind:'text'}},capabilities:[],program:[]},diagnostics:[]}])
    if(path==='/flows'&&request.method()==='POST'){const body=request.postDataJSON();saved=body.composition;savedWorkspace=body.workspaceId;return respond(file())}
    if(path==='/flows')return respond(new URL(request.url()).searchParams.get('workspaceId')==='other-workspace'?[]:[file()])
    if(path.startsWith('/flows/'))return respond(file())
    if(path==='/models')return respond({models:[{provider:'fixture',id:'fixture',label:'Fixture',reasoningLevels:[]}]})
    if(path==='/rtc/config'||path.endsWith('/events'))return route.fulfill({status:503,body:'HTTP fixture'})
    return respond([])
  })
  await page.goto('/')
  await expect(page.getByText('Daemon connecté',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Conception',exact:true}).click()
  await page.locator('.flow-file-open').click()
  await expect(page.locator('.canvas .vue-flow__node')).toHaveCount(composition.nodes.length)
  return Object.assign(()=>saved,{workspace:()=>savedWorkspace})
}

test('context and prediction are separate editable steps and every connection has a visible arrow',async({page})=>{
  const flow=harnessTemplate(),saved=await authoring(page,flow)
  const context=page.locator('.canvas .vue-flow__node[data-id="context"]'),model=page.locator('.canvas .vue-flow__node[data-id="model"]')
  await expect(context).toContainText('1 · Préparer le contexte')
  await expect(model).toContainText('2 · Appeler le modèle')
  await expect(model.locator('.attachment-piece')).toHaveCount(0)
  await model.locator('.node-heading').click()
  await expect(page.getByRole('combobox',{name:'Choix du modèle',exact:true})).toBeVisible()
  await expect(page.locator('.ctx-binding-editor')).toHaveCount(0)
  await page.locator('.graph-context-link').getByRole('button',{name:'Configurer',exact:true}).click()
  await expect(page.getByLabel('Stratégie Rust',{exact:true})).toHaveValue('harness-default')
  await expect(page.getByLabel('Source de instructions',{exact:true})).toHaveValue('attachments')
  await expect(page.getByLabel('Ressources de instructions',{exact:true})).toHaveValue('instructions')
  await expect(page.getByRole('combobox',{name:'Choix du modèle',exact:true})).toHaveCount(0)
  await expect.poll(()=>page.locator('.canvas .vue-flow__edge-path').evaluateAll(paths=>paths.length>0&&paths.every(path=>{
    const marker=path.getAttribute('marker-end'),id=marker?.match(/#([^)]*)/)?.[1]
    return !!id&&!!document.getElementById(id)?.querySelector('path')
  }))).toBe(true)
  await page.getByRole('button',{name:'Ajouter des nœuds',exact:true}).click()
  await expect(page.locator('.palette-item.context')).toContainText('Contexte')
  await expect(page.locator('.palette-item.model')).toContainText('Modèle')
  await expect(page.locator('.palette-item.agent')).toHaveCount(0)
  await page.screenshot({path:test.info().outputPath('context-model-definition.png')})
  await page.locator('.palette-item.model').click()
  await expect(page.locator('.canvas .vue-flow__node')).toHaveCount(flow.nodes.length+2)
  await page.getByRole('button',{name:'Enregistrer',exact:true}).click()
  await expect.poll(()=>saved().nodes.length).toBe(flow.nodes.length+2)
  const added=saved().nodes.filter(node=>!flow.nodes.some(old=>old.id===node.id)),inference=added.find(node=>node.data.kind==='model')!,preparation=added.find(node=>node.data.kind==='context')!
  expect(inference.data.config.contextNode).toBe(preparation.id)
  expect(preparation.data.config.modelNode).toBe(inference.id)
  expect(preparation.position.y).toBeGreaterThan(Math.max(...flow.nodes.map(node=>node.position.y)))
  expect(saved().edges.some(edge=>edge.source===preparation.id&&edge.target===inference.id)).toBe(true)
  await page.screenshot({path:test.info().outputPath('context-model-pair.png')})
})

test('separating a historical agent creates a new flow and keeps the old definition intact',async({page})=>{
  const original=legacyHarnessTemplate(),read=await authoring(page,original)
  await page.getByLabel('Workspace de conception',{exact:true}).selectOption('other-workspace')
  await expect(page.locator('.flow-file-open')).toHaveCount(0)
  await expect(page.locator('.graph-legacy-banner')).toBeVisible()
  await expect(page.locator('.canvas .attachment-piece')).toHaveCount(0)
  await expect(page.getByLabel('Choix du modèle',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'Ajouter des nœuds',exact:true}).click()
  await expect(page.locator('.palette-item.agent')).toHaveCount(0)
  await page.getByRole('button',{name:'Séparer contexte et modèle',exact:true}).click()
  await expect(page.locator('.canvas .flow-card.model')).toHaveCount(1)
  await expect(page.locator('.canvas .flow-card.context')).toHaveCount(1)
  expect(read()).toEqual(original)
  await page.getByRole('button',{name:'Enregistrer',exact:true}).click()
  await expect.poll(()=>read().formatVersion).toBe(3)
  expect(read.workspace()).toBe('pair-workspace')
  expect(read().id).not.toBe(original.id)
  expect(read().nodes.find(node=>node.id==='context')!.data.config.attachments).toEqual(original.nodes.find(node=>node.id==='model')!.data.config.attachments)
  expect(read().nodes.find(node=>node.id==='model')!.position).toEqual(original.nodes.find(node=>node.id==='model')!.position)
  expect(read().edges.filter(edge=>edge.target==='model')).toEqual([{id:'context-model',source:'context',target:'model'}])
})

test('the Harness exposes a routing point before context and binds its result explicitly',async({page})=>{
  const original=legacyHarnessTemplate(),flow=harnessTemplate(),read=await authoring(page,flow)
  expect(original.nodes.some(node=>node.data.kind==='context'||node.data.kind==='route')).toBe(false)
  expect(original.nodes.find(node=>node.id==='model')!.data.kind).toBe('agent')
  const dispatch=page.locator('.canvas .vue-flow__node[data-id="dispatch"]')
  await expect(dispatch).toContainText('Routage du travail')
  await expect(dispatch).toContainText('continuer si aucune route')
  await dispatch.locator('.node-heading').click()
  await expect(page.getByLabel('Point de branchement',{exact:true})).toHaveValue('work')
  await expect(page.getByLabel('Déclenchement de la route',{exact:true})).toHaveValue('condition')
  await page.locator('.canvas .vue-flow__node[data-id="start"] .node-heading').click()
  await page.getByLabel('Famille de contrats',{exact:true}).selectOption('branches')
  await expect(page.getByLabel('Nœud du branchement work',{exact:true})).toHaveValue('dispatch')
  await expect(page.getByLabel('Déclenchement work',{exact:true})).toHaveValue('condition')
  await page.getByRole('button',{name:'Enregistrer',exact:true}).click()
  const saved=read(),context=saved.nodes.find(node=>node.id==='context')!
  expect(saved.edges.some(edge=>edge.source==='steering'&&edge.target==='dispatch')).toBe(true)
  expect(saved.edges.some(edge=>edge.source==='dispatch'&&edge.target===context.id)).toBe(true)
  expect(context.data.config.contextBindings.routeResult).toEqual({kind:'state',field:'routeResult'})
  expect(context.data.config.attachments).toEqual(original.nodes.find(node=>node.id==='model')!.data.config.attachments)
  expect(saved.channels).toContainEqual({name:'routeResult',reducer:'overwrite',default:''})
  await page.screenshot({path:test.info().outputPath('harness-routing-contract.png')})
})

test('the new Harness can run without a bridge and resets its absent routing result before model preparation',async({request})=>{
  const flow=harnessTemplate()
  flow.name=`Harness autonome sans bridge ${Date.now()}`
  const model=flow.nodes.find(node=>node.id==='model')!
  model.data.config.modelBinding='fixed';model.data.config.provider='fixture';model.data.config.model='fixture'
  flow.nodes.find(node=>node.id==='start')!.data.config.exports.contract.inferenceNodes.model.model={kind:'fixed',provider:'fixture',model:'fixture'}
  const file=await saveFlow(request,flow)
  const response=await request.post('/api/runs',{data:{flowKey:file.key,flowHash:file.hash,input:{input:'Continuer sans route externe',routeResult:'Ancien résultat à ne pas réutiliser'}}})
  expect(response.ok(),await response.text()).toBeTruthy()
  const ack=await response.json(),run=await waitRun(request,ack.id,'waiting')
  const completed=run.activities!.filter(activity=>activity.status==='completed')
  const preparations=completed.filter(activity=>['dispatch','context','model'].includes(activity.node)).map(activity=>activity.node)
  expect(preparations.length).toBeGreaterThanOrEqual(3)
  expect(preparations.length%3).toBe(0)
  for(let index=0;index<preparations.length;index+=3)expect(preparations.slice(index,index+3)).toEqual(['dispatch','context','model'])
  expect(run.state.routeResult).toBe('')
  expect(run.messages.at(-1)?.text).toContain('Continuer sans route externe')
})

test('converting a parallel join preserves the default all-predecessors barrier before context preparation',async({request})=>{
  const converted=parallelJoinFixture()
  expect(converted.nodes.find(node=>node.id==='context')!.data.config.fanIn).toBe('all')
  const file=await saveFlow(request,converted)
  const response=await request.post('/api/runs',{data:{flowKey:file.key,flowHash:file.hash,input:{input:'Attendre les deux branches'}}})
  expect(response.ok(),await response.text()).toBeTruthy()
  const ack=await response.json(),run=await waitRun(request,ack.id,'completed')
  const completed=(run.activities||[]).filter(activity=>activity.status==='completed')
  const preparation=completed.filter(activity=>activity.kind==='context'),prediction=completed.filter(activity=>activity.kind==='model')
  expect(preparation).toHaveLength(1)
  expect(prediction).toHaveLength(1)
  for(const branch of ['fast','slow'])expect(completed.find(activity=>activity.node===branch)!.endedSeq).toBeLessThan(preparation[0].startedSeq!)
  expect(preparation[0].endedSeq).toBeLessThan(prediction[0].startedSeq!)
})

test('the actual starter commits a context passage before each prediction and survives a new turn',async({request})=>{
  const flow=template(true)
  flow.name=`Contexte puis modèle ${Date.now()}`
  const file=await saveFlow(request,flow)
  const response=await request.post('/api/runs',{data:{flowKey:file.key,flowHash:file.hash,input:{input:'Premier passage explicite'}}})
  expect(response.ok(),await response.text()).toBeTruthy()
  const ack=await response.json(),first=await waitRun(request,ack.id,'waiting')
  const steps=(first.activities||[]).filter(item=>item.status==='completed'&&['context','model'].includes(item.kind))
  expect(steps.map(item=>item.kind)).toEqual(['context','model'])
  expect(steps[0].endedSeq).toBeLessThan(steps[1].startedSeq!)
  expect(first.messages.at(-1)?.text).toContain('Premier passage explicite')
  expect(first.composition.nodes.find(node=>node.id==='context')!.data.config.contextProgram).toBeTruthy()
  expect(first.composition.nodes.find(node=>node.id==='model')!.data.config.contextProgram).toBeUndefined()
  const answer=await request.post(`/api/runs/${ack.id}/answer`,{data:{waitId:first.wait!.id,value:'Deuxième passage explicite'}})
  expect(answer.ok(),await answer.text()).toBeTruthy()
  await expect.poll(async()=>{const run=await (await request.get(`/api/runs/${ack.id}`)).json();return run.status==='waiting'&&run.wait?.id!==first.wait!.id}).toBe(true)
  const second=await (await request.get(`/api/runs/${ack.id}`)).json()
  expect(second.activities.filter((item:any)=>item.status==='completed'&&['context','model'].includes(item.kind)).map((item:any)=>item.kind)).toEqual(['context','model','context','model'])
  expect(second.messages.at(-1)?.text).toContain('Deuxième passage explicite')
  expect(new Set(second.timeline.map((item:any)=>item.id)).size).toBe(second.timeline.length)
})
