import { test, expect } from '@playwright/test'
import { legacyHarnessTemplate as harnessTemplate } from './fixtures/templates'
import { inspector, openSession, waitRun } from './helpers'

test('compact navigation resizes, menus dismiss and drafts survive spaces and full-page inspection',async({page,request})=>{
  const flow=harnessTemplate(),creation=await request.post('/api/runs',{data:{composition:flow,input:{input:'Session du rail'},modelBindings:{model:{provider:'fixture',model:'fixture'}}}})
  expect(creation.ok(),await creation.text()).toBeTruthy()
  const run=await creation.json();await waitRun(request,run.id,'waiting')
  await page.goto('/');await openSession(page,run.id)
  const resize=page.getByRole('separator',{name:'Redimensionner la navigation',exact:true})
  await expect(resize).toHaveAttribute('aria-valuenow','280')
  await resize.focus();await page.keyboard.press('ArrowRight');await expect(resize).toHaveAttribute('aria-valuenow','300')
  await page.locator('.composer textarea').fill('Brouillon conservé')
  await page.getByRole('button',{name:'Choisir un flow',exact:true}).click()
  await expect(page.locator('.flow-menu')).toBeVisible()
  await page.locator('.session-heading').click();await expect(page.locator('.flow-menu')).toHaveCount(0)
  await page.getByRole('button',{name:'Choisir un flow',exact:true}).click();await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Choisir un flow',exact:true})).toBeFocused()
  await page.getByRole('button',{name:'Conception',exact:true}).click()
  await page.getByRole('textbox',{name:'Nom de composition'}).fill('Brouillon de conception conservé')
  await page.getByRole('button',{name:'Exécution',exact:true}).click()
  await expect(page.locator('.composer textarea')).toHaveValue('Brouillon conservé')
  await expect(page.locator('.wait-card')).toHaveCount(0)
  await expect(page.locator('.composer-wait-prompt')).toContainText('Sur quoi continuer')
  const snapshot=await(await request.get(`/api/runs/${run.id}`)).json()
  expect(snapshot.activities.filter((activity:any)=>activity.startedSeq===undefined)).toHaveLength(0)
  const answer=snapshot.timeline.find((entry:any)=>entry.kind==='message'&&entry.role==='assistant')
  expect(answer.origin.occurrenceId).toBeTruthy()
  await page.locator(`.rail-origin[data-occurrence-id="${answer.origin.occurrenceId}"]`).click()
  await expect(page.getByRole('combobox',{name:'Passage du nœud',exact:true})).toHaveValue(answer.origin.occurrenceId)
  const viewport=page.locator('.run-canvas .vue-flow__transformationpane')
  // Vue Flow hides the pane until its initial fit has finished.
  await expect(viewport).toHaveCSS('opacity','1')
  const compactCamera=await viewport.getAttribute('style')
  const compactTransform=await viewport.evaluate(element=>getComputedStyle(element).transform)
  await page.getByRole('button',{name:'Agrandir le graphe',exact:true}).click()
  await expect(page.locator('.session-inspector.expanded')).toBeVisible()
  await expect(page.locator('.conversation-pane')).not.toBeVisible()
  await expect(viewport).not.toHaveCSS('transform',compactTransform)
  const expandedTransform=await viewport.evaluate(element=>getComputedStyle(element).transform)
  await page.locator('.run-canvas .vue-flow__controls-zoomin').click()
  await expect(viewport).not.toHaveCSS('transform',expandedTransform)
  const camera=await viewport.getAttribute('style')
  await page.getByRole('button',{name:'Revenir au chat',exact:true}).click()
  await expect(page.locator('.composer textarea')).toHaveValue('Brouillon conservé')
  await expect(viewport).toHaveAttribute('style',compactCamera!)
  await page.getByRole('button',{name:'Agrandir le graphe',exact:true}).click()
  await expect(viewport).toHaveAttribute('style',camera!)
  await page.getByRole('button',{name:'Revenir au chat',exact:true}).click()
  await page.getByRole('button',{name:'Conception',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Nom de composition'})).toHaveValue('Brouillon de conception conservé')
  await page.getByRole('button',{name:'Exécution',exact:true}).click()
  await page.getByRole('button',{name:'Fermer les détails',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:'Masquer la navigation',exact:true}).click()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await inspector(page)
  await page.getByRole('button',{name:'Agrandir le graphe',exact:true}).click()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Fermer les détails',exact:true}).click()
  await page.setViewportSize({width:1512,height:982});await page.reload()
  await expect(page.getByRole('separator',{name:'Redimensionner la navigation'})).toHaveAttribute('aria-valuenow','300')
})
