import {test,expect} from '@playwright/test'
import { designTemplate, inspector, openSession, useDesign } from './helpers'
const node=(id:string,kind:string,config:Record<string,any>,x:number)=>({id,type:'flow',position:{x,y:160},data:{label:id,kind,config}})
const document=()=>({id:crypto.randomUUID(),name:'Observation WebRTC',revision:0,nodes:[node('start','start',{},50),node('slow-tool','tool',{tool:'delay',arguments:{milliseconds:5000},field:'output',ui:{renderer:'table',title:'Délai asynchrone'}},320),node('end','end',{},650)],edges:[{id:'a',source:'start',target:'slow-tool'},{id:'b',source:'slow-tool',target:'end'}]})
test('WebRTC displays a node while executing, then renders the real tool result',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/');await expect(page.getByText('Daemon connecté')).toBeVisible()
 const response=await request.post('/api/runs',{data:{composition:document(),input:{input:'Observer un outil en cours'}}})
 expect(response.ok()).toBeTruthy();const run=await response.json()
 await openSession(page,run.id)
 await inspector(page)
 await page.getByRole('button',{name:'Connexion au daemon',exact:true}).click()
 await expect(page.locator('[data-transport=webrtc]')).toBeVisible({timeout:12000})
 await page.keyboard.press('Escape')
 await page.locator('.passage-index [data-node=slow-tool]').click()
 await expect(page.locator('[data-node=slow-tool][data-status=running]')).toBeVisible()
 expect((await (await request.get(`/api/runs/${run.id}`)).json()).status).toBe('running')
 await page.screenshot({path:test.info().outputPath('04-webrtc-running.png')})
 await expect(page.locator('[data-node=slow-tool][data-status=completed]')).toBeVisible({timeout:15000})
 await expect(page.locator('.result-table')).toContainText('5000')
 await page.getByRole('button',{name:'Connexion au daemon',exact:true}).click()
 await expect(page.locator('[data-transport=webrtc]')).toBeVisible()
 await page.keyboard.press('Escape')
 await page.screenshot({path:test.info().outputPath('05-tool-completed.png')})
 expect(errors).toEqual([])
})
test('an explicit tool graph returns results to its model and remains interactive',async({page})=>{
 await page.goto('/');await expect(page.getByText('Daemon connecté')).toBeVisible()
 await designTemplate(page,'tools')
 await page.getByRole('button',{name:'Paramètres ADK'}).click()
 await page.getByLabel('Limite d’étapes').fill('80')
 await page.screenshot({path:test.info().outputPath('06-adk-settings.png')})
 await page.getByRole('dialog',{name:/Paramètres ADK/}).getByRole('button',{name:'Fermer',exact:true}).click()
 await useDesign(page)
 await expect(page.locator('.composer-wait-prompt')).toBeVisible({timeout:20000})
 await inspector(page)
 await page.screenshot({path:test.info().outputPath('08-interaction-overview.png')})

 await expect(page.locator('[data-node=model][data-status=completed]')).toHaveCount(2)
 await expect(page.locator('[data-node=tools][data-status=completed]')).toBeVisible()
 await expect(page.locator('.assistant-markdown')).toContainText('inspect_json')
 await page.screenshot({path:test.info().outputPath('07-tool-loop.png')})
})
test('RTC failure is explicitly identified as SSE fallback',async({page})=>{
 await page.route('**/api/rtc/config',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'ICE indisponible pour ce test'})}))
 await page.goto('/');await expect(page.getByText('Daemon connecté')).toBeVisible()
 await designTemplate(page,'interactive')
 await useDesign(page)
 await page.getByRole('button',{name:'Connexion au daemon',exact:true}).click()
 await expect(page.locator('[data-transport=sse]')).toContainText('SSE · repli')
 await expect(page.locator('.composer-wait-prompt')).toBeVisible()
 await expect(page.locator('[data-transport=webrtc]')).toHaveCount(0)
})
