import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { designTemplate, fixturePath, waitRun } from './helpers'

test('the multiflow example installs real definitions and uses the documentation directory only in its worker', async ({ page, request }) => {
  const workspaceId = (await (await request.get('/api/health')).json()).defaultWorkspaceId
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await expect(page.locator('.autonomous-history')).toBeVisible()
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await expect(page.locator('.autonomous-history')).toHaveCount(0)
  await page.getByRole('button', { name: 'Exemple multiflow', exact: true }).click()
  const installer = page.getByRole('dialog', { name: 'Exemple Working System', exact: true })
  await installer.getByLabel('Répertoire du flow Working System', { exact: true }).fill('../workspace-b')
  const installing = page.waitForResponse(response => new URL(response.url()).pathname === '/api/examples/working-system' && response.request().method() === 'POST')
  await installer.getByRole('button', { name: 'Créer l’exemple', exact: true }).click()
  const installation = await installing
  expect(installation.ok(), await installation.text()).toBeTruthy()
  const example = await installation.json()
  expect(example.workingDirectory).toBe(fixturePath('workspace-b'))
  expect(example.worker.composition.settings.workingDirectory).toBe('../workspace-b')
  expect(example.root.composition.settings.workingDirectory).toBeUndefined()
  await expect(installer).not.toBeVisible()
  await expect(page.getByLabel('Nom de composition', { exact: true })).toHaveValue('Harness · Working System')
  await expect(page.locator('.design-editor .flow-card.context')).toHaveCount(1)
  await expect(page.locator('.design-editor .flow-card.model')).toHaveCount(1)
  for (const file of [example.root, example.worker]) {
    expect(file.path).toContain(fixturePath('workspace-a', '.zedflow', 'flow'))
    expect(await readFile(`${file.path}/flow.rs`, 'utf8')).toContain(file.composition.id)
    expect(file.composition.nodes.some((node: any) => node.data.kind === 'agent')).toBeFalsy()
    const context = file.composition.nodes.find((node: any) => node.data.kind === 'context')
    const model = file.composition.nodes.find((node: any) => node.data.kind === 'model')
    expect(context.data.config.modelNode).toBe(model.id)
    expect(model.data.config.contextNode).toBe(context.id)
    expect(file.composition.edges.some((edge: any) => edge.source === context.id && edge.target === model.id)).toBeTruthy()
  }
  expect(await readFile(example.bridge.path, 'utf8')).toContain('BridgeDefinition::new')
  expect(example.bridge.bridge.connections.documentation.mode).toBe('callAwait')
  expect(example.bridge.bridge.imports.documentation.flow).toBe(example.worker.key)
  const reinstalled = await request.post('/api/examples/working-system', { data: { workspaceId, workingDirectory: '../workspace-b' } })
  expect(reinstalled.ok(), await reinstalled.text()).toBeTruthy()
  const unchanged = await reinstalled.json()
  expect([unchanged.root.hash, unchanged.worker.hash, unchanged.bridge.hash]).toEqual([example.root.hash, example.worker.hash, example.bridge.hash])
  const files = await (await request.get(`/api/flows?workspaceId=${workspaceId}`)).json()
  expect(files.filter((file: any) => [example.root.key, example.worker.key].includes(file.key))).toHaveLength(2)

  await page.getByRole('button', { name: 'Utiliser', exact: true }).click()
  await page.getByRole('button', { name: 'Composer', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Composer une exécution', exact: true })
  await expect(dialog.getByLabel('Flow d’entrée', { exact: true })).toHaveValue(example.root.key)
  await dialog.getByRole('checkbox', { name: /^working-system / }).check()
  const preparing = page.waitForResponse(response => new URL(response.url()).pathname === '/api/runtime-graphs/prepare' && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Préparer le graphe résolu', exact: true }).click()
  const preparedResponse = await preparing
  expect(preparedResponse.ok(), await preparedResponse.text()).toBeTruthy()
  const prepared = await preparedResponse.json()
  expect(Object.keys(prepared.runtime.flows)).toEqual(['root', 'working-system/documentation'])
  await expect(dialog.locator('[data-runtime-route="working-system/documentation"]')).toBeVisible()
  await expect(dialog.locator('.model-binding-row')).toHaveCount(2)
  await expect(dialog.getByRole('region', { name: 'Contextes des inférences', exact: true }).locator('select')).toHaveCount(2)
  for (const path of ['root/model', 'working-system/documentation/model']) {
    const row = dialog.locator(`[data-model-path="${path}"]`)
    await row.getByLabel('Fournisseur du modèle', { exact: true }).selectOption('fixture')
    await row.getByLabel('Modèle', { exact: true }).fill('fixture-echo')
    await row.getByLabel('Modèle', { exact: true }).press('Tab')
  }
  await dialog.getByRole('button', { name: 'Utiliser cette composition', exact: true }).click()
  const launched = page.waitForResponse(response => new URL(response.url()).pathname === '/api/runs' && response.request().method() === 'POST')
  await page.locator('.composer textarea').fill('AGENTS.md')
  await page.locator('.composer textarea').press('Enter')
  const response = await launched
  expect(response.ok(), await response.text()).toBeTruthy()
  const ack = await response.json()
  expect(response.request().postDataJSON().runtimeSelection.bridges).toEqual(['working-system'])
  const run = await waitRun(request, ack.id, 'waiting', workspaceId)
  expect(run.workspacePath).toBe(fixturePath('workspace-a'))
  expect(run.modelBindings?.['root/model']?.provider).toBe('fixture')
  expect(run.modelBindings?.['working-system/documentation/model']?.provider).toBe('fixture')
  expect(run.activities?.some(activity => activity.path === 'working-system/documentation/context' && activity.status === 'completed')).toBeTruthy()
  expect(run.activities?.some(activity => activity.path === 'working-system/documentation/model' && activity.status === 'completed')).toBeTruthy()
  const workerContext = run.contextSnapshots?.find(snapshot => snapshot.agentPath === 'working-system/documentation/model')
  expect(workerContext).toBeDefined()
  expect(JSON.stringify(workerContext)).toContain('Workspace B')
  expect(JSON.stringify(workerContext)).toContain(fixturePath('workspace-b'))
  expect(JSON.stringify(workerContext)).not.toContain('Workspace A')
  const rootContext = run.contextSnapshots?.find(snapshot => snapshot.agentPath === 'root/model')
  expect(rootContext).toBeDefined()
  expect(rootContext?.tools).toEqual([])
  expect(workerContext?.tools).toEqual(['read', 'exec'])
  const receipt = run.toolActivities?.find(activity => activity.name === 'read' && activity.status === 'completed')
  expect(receipt).toBeDefined()
  expect(JSON.stringify(receipt)).toContain('Workspace B')
  expect(JSON.stringify(receipt)).toContain(fixturePath('workspace-b'))
  expect(run.state.workingSystemResult).toBeTruthy()
  await expect(page.locator(`[data-session-id="${ack.id}"]`)).toBeVisible()
  await expect(page.locator('.composer-wait-prompt')).toContainText('Sur quoi continuer ?')
  await page.locator('.composer textarea').fill('Brouillon de la session composée')
  await page.locator('.autonomous-history summary').click()
  await expect(page.locator('.autonomous-history')).toContainText('sans conversation interactive')
  await expect(page.locator('.composer textarea')).toHaveValue('Brouillon de la session composée')
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await expect(page.locator('.autonomous-history')).toHaveCount(0)
  await page.getByRole('button', { name: 'Exécution', exact: true }).click()
  await expect(page.locator('.composer textarea')).toHaveValue('Brouillon de la session composée')
  await expect(page.locator(`[data-session-id="${ack.id}"]`)).toHaveClass(/chosen/)
  await page.screenshot({ path: test.info().outputPath('working-system-composed-session.png') })
})

test('installing an example preserves an edited flow until its save-and-open decision', async ({ page, request }) => {
  const workspaceId = (await (await request.get('/api/health')).json()).defaultWorkspaceId
  await page.goto('/')
  await expect(page.getByText('Daemon connecté', { exact: true })).toBeVisible()
  await designTemplate(page, 'interactive')
  const name = page.getByLabel('Nom de composition', { exact: true })
  await name.fill('Flow avant installation')
  const savedResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/flows' && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  const saved = await savedResponse
  expect(saved.ok(), await saved.text()).toBeTruthy()
  const original = await saved.json()
  await expect(page.locator('.design-title')).not.toContainText('Modifications non enregistrées')
  await name.fill('Modification à préserver')

  async function install() {
    await page.getByRole('button', { name: 'Exemple multiflow', exact: true }).click()
    const installer = page.getByRole('dialog', { name: 'Exemple Working System', exact: true })
    await installer.getByLabel('Répertoire du flow Working System', { exact: true }).fill('../workspace-b')
    await installer.getByRole('button', { name: 'Créer l’exemple', exact: true }).click()
    await expect(installer).not.toBeVisible()
  }
  const decision = page.getByRole('dialog', { name: 'Conserver le brouillon ?', exact: true })
  await install()
  await expect(decision).toBeVisible()
  await decision.press('Escape')
  await expect(decision).not.toBeVisible()
  await expect(name).toHaveValue('Modification à préserver')
  await expect(page.locator('.design-title')).toContainText('Modifications non enregistrées')
  const untouched = await (await request.get(`/api/flows?workspaceId=${workspaceId}`)).json()
  expect(untouched.find((file: any) => file.key === original.key)?.hash).toBe(original.hash)

  await install()
  await expect(decision).toBeVisible()
  await decision.getByRole('button', { name: 'Enregistrer et ouvrir', exact: true }).click()
  await expect(decision).not.toBeVisible()
  await expect(name).toHaveValue('Harness · Working System')
  const persisted = await (await request.get(`/api/flows?workspaceId=${workspaceId}`)).json()
  expect(persisted.find((file: any) => file.key === original.key)?.name).toBe('Modification à préserver')
})
