import { test, expect } from '@playwright/test'
import { readFile, writeFile, copyFile, access } from 'node:fs/promises'
import { unzipSync } from 'fflate'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { legacyTemplate as template } from './fixtures/templates'
import type { FlowFile, Run, Workspace } from '@zedflow/sdk'
import { designTemplate, fixturePath, inspector, openSession, saveFlow, waitRun } from './helpers'


test('daemon folder browsing groups sessions by workspace and closing a workspace preserves its sessions', async ({ page, request }) => {
  const initial = await (await request.get('/api/health')).json()
  const flowA = template(true); flowA.name = 'Session du workspace A'
  const createdA = await request.post('/api/runs', { data: { workspaceId: initial.defaultWorkspaceId, composition: flowA, input: { input: 'Workspace A' } } })
  expect(createdA.ok()).toBeTruthy()
  const runA: Run = await createdA.json()
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Interagir', exact: true })).toHaveCount(0)
  await expect(page.locator('.conversation-pane')).toBeVisible()
  await page.locator('.open-workspace').click()
  const browser = page.getByRole('dialog', { name: 'Ouvrir un workspace', exact: true })
  await browser.getByLabel('Chemin du dossier').fill(fixturePath())
  await browser.getByRole('button', { name: 'Aller', exact: true }).click()
  await browser.locator('.directory-list').getByRole('button', { name: 'workspace-b', exact: true }).click()
  await expect(browser.locator('.directory-selected')).toHaveText(fixturePath('workspace-b'))
  await browser.getByRole('button', { name: 'Ouvrir ce dossier', exact: true }).click()
  await expect(browser).toHaveCount(0)
  const workspaces: Workspace[] = await (await request.get('/api/workspaces')).json()
  const workspaceB = workspaces.find(workspace => workspace.path === fixturePath('workspace-b'))!
  const flowB = template(true); flowB.name = 'Session du workspace B'
  const createdB = await request.post('/api/runs', { data: { workspaceId: workspaceB.id, composition: flowB, input: { input: 'Workspace B' } } })
  expect(createdB.ok()).toBeTruthy()
  const createdRunB = await createdB.json()
  const runB: Run = await (await request.get(`/api/runs/${createdRunB.id}?workspaceId=${workspaceB.id}`)).json()
  await openSession(page, runB.id, workspaceB.id)
  await expect(page.locator(`[data-workspace-id="${initial.defaultWorkspaceId}"] [data-session-id="${runA.id}"]`)).toBeVisible()
  await expect(page.locator(`[data-workspace-id="${workspaceB.id}"] [data-session-id="${runB.id}"]`)).toBeVisible()
  await page.getByRole('button', { name: 'Contexte de la session', exact: true }).click()
  await expect(page.locator('.session-context-popover')).toContainText(fixturePath('workspace-b'))
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: `Actions de ${runB.name}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Renommer la session', exact: true }).click()
  const rename = page.getByRole('dialog', { name: 'Renommer la session', exact: true })
  await rename.getByLabel('Nom', { exact: true }).fill('Travail renommé dans B')
  await rename.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.locator(`[data-session-id="${runB.id}"]`)).toContainText('Travail renommé dans B')
  await page.getByRole('button', { name: 'Actions du workspace workspace-b', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Fermer le workspace', exact: true }).click()
  await expect(page.locator(`[data-workspace-id="${workspaceB.id}"]`)).toHaveCount(0)
  expect((await (await request.get(`/api/runs/${runB.id}?workspaceId=${workspaceB.id}`)).json()).workspaceId).toBe(workspaceB.id)
  let releaseBrowse!: () => void
  const browsePending = new Promise<void>(resolve => { releaseBrowse = resolve })
  await page.route('**/api/filesystem?*', async route => {
    const response = await route.fetch()
    await browsePending
    await route.fulfill({ response })
  }, { times: 1 })
  try {
    const initialBrowse = page.waitForRequest(observed => new URL(observed.url()).pathname === '/api/filesystem')
    await page.locator('.open-workspace').click()
    await initialBrowse
    await expect(browser.getByLabel('Chemin du dossier')).not.toBeEditable()
    releaseBrowse()
    await browser.getByLabel('Chemin du dossier').fill(fixturePath('workspace-b'))
    await browser.getByRole('button', { name: 'Aller', exact: true }).click()
    await browser.getByRole('button', { name: 'Ouvrir ce dossier', exact: true }).click()
  } finally { releaseBrowse() }
  await expect(page.locator(`[data-workspace-id="${workspaceB.id}"] [data-session-id="${runB.id}"]`)).toContainText('Travail renommé dans B')
})

test('visual flows are Rust files with global and workspace scope, discovery, and external edit conflicts', async ({ page, request }) => {
  const workspaceB: Workspace = await (await request.post('/api/workspaces', { data: { path: fixturePath('workspace-b') } })).json()
  const initial = await (await request.get('/api/health')).json()
  await page.goto('/')
  await expect(page.getByText('Daemon connecté')).toBeVisible()
  await designTemplate(page, 'autonomous')
  await page.getByRole('textbox', { name: 'Nom de composition' }).fill('Flow local de fichiers')
  await page.locator('.flow-card.output').click()
  await page.getByLabel('Contenu', { exact: true }).fill('Réponse locale initiale')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Flow enregistré')
  let files: FlowFile[] = await (await request.get(`/api/flows?workspaceId=${initial.defaultWorkspaceId}`)).json()
  const local = files.find(file => file.name === 'Flow local de fichiers')!
  expect(local.path).toContain(fixturePath('workspace-a', '.zedflow', 'flow'))
  const source = await readFile(join(local.path, "flow.rs"), 'utf8')
  expect(source).toContain('const ZEDFLOW_FORMAT: u32 = 3')
  expect(source).toContain('models::context_node_with_services')
  expect(source).toContain('models::inference_node_with_services')
  expect(source).toContain('graph.add_node')
  await page.getByRole('button', { name: 'Enregistrer sous', exact: true }).click()
  const saveAs = page.getByRole('dialog', { name: 'Enregistrer sous', exact: true })
  await saveAs.getByLabel('Nom', { exact: true }).fill('Flow global partagé')
  await saveAs.getByLabel('Emplacement').selectOption('global')
  await saveAs.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(saveAs).toHaveCount(0)
  files = await (await request.get(`/api/flows?workspaceId=${initial.defaultWorkspaceId}`)).json()
  const global = files.find(file => file.name === 'Flow global partagé')!
  expect(global.path).toContain(fixturePath('home', '.zedflow', 'flow'))
  expect(await readFile(join(global.path, "flow.rs"), 'utf8')).toContain('Flow global partagé')
  await page.getByLabel('Workspace de conception').selectOption(workspaceB.id)
  await expect(page.locator(`[data-flow-key="${global.key}"]`)).toBeVisible()
  await expect(page.locator(`[data-flow-key="${local.key}"]`)).toHaveCount(0)
  await page.getByLabel('Workspace de conception').selectOption(initial.defaultWorkspaceId)
  await page.locator(`[data-flow-key="${local.key}"] .flow-file-open`).click()
  await page.locator('.flow-card.output').click()
  await page.getByLabel('Contenu', { exact: true }).fill('Brouillon non enregistré')
  const external = source.replace('Réponse locale initiale', 'Réponse modifiée depuis Rust')
  await writeFile(join(local.path, "flow.rs"), external)
  await page.getByRole('button', { name: 'Actualiser les flows', exact: true }).click()
  await expect(page.getByLabel('Contenu', { exact: true })).toHaveValue('Brouillon non enregistré')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('modifié')
  expect(await readFile(join(local.path, "flow.rs"), 'utf8')).toBe(external)
  const imported = join(fixturePath('workspace-a', '.agents', 'flows'), 'imported.rs')
  await copyFile(join(local.path, 'flow.rs'), imported)
  const importedSource = external.replace('Flow local de fichiers', 'Flow chargé depuis agents').replaceAll(local.id!, 'imported-legacy-discovery')
  await writeFile(imported, importedSource)
  const invalid = join(fixturePath('workspace-a', '.agents', 'flows'), 'unsupported.rs')
  const untouched = 'fn main() { std::fs::write("must-not-execute", "unexpected").unwrap(); }'
  await writeFile(invalid, untouched)
  await page.getByRole('button', { name: 'Actualiser les flows', exact: true }).click()
  await expect(page.locator('.flow-file').filter({ hasText: 'Flow chargé depuis agents' }).locator('.flow-file-open')).toHaveAttribute('title', imported)
  expect(await readFile(imported, 'utf8')).toBe(importedSource)
  await expect(page.locator('.flow-file.invalid').filter({ hasText: 'unsupported' })).toBeVisible()
  expect(await readFile(invalid, 'utf8')).toBe(untouched)
  expect(await access(fixturePath('workspace-a', 'must-not-execute')).then(() => true, () => false)).toBe(false)
})

test('editing and deleting a Rust flow preserves existing sessions and their downloadable Cargo source', async ({ page, request }) => {
  const initial = await (await request.get('/api/health')).json()
  const composition = template(false)
  composition.name = 'Versions indépendantes'
  composition.nodes.find(node => node.data.kind === 'output')!.data.config.text = 'Version initiale'
  const file = await saveFlow(request, composition, initial.defaultWorkspaceId)
  const response = await request.post('/api/runs', { data: { workspaceId: initial.defaultWorkspaceId, flowKey: file.key, flowHash: file.hash, input: { input: 'Ancienne session' } } })
  expect(response.ok()).toBeTruthy()
  const old: Run = await response.json()
  await waitRun(request, old.id, 'completed')
  const original = await readFile(join(file.path, "flow.rs"), 'utf8')
  await writeFile(join(file.path, "flow.rs"), original.replace('Version initiale', 'Nouvelle version'))
  const updated: FlowFile = await (await request.get(`/api/flows/${file.key}?workspaceId=${initial.defaultWorkspaceId}`)).json()
  expect(updated.hash).not.toBe(file.hash)
  const responseNew = await request.post('/api/runs', { data: { workspaceId: initial.defaultWorkspaceId, flowKey: updated.key, flowHash: updated.hash, input: { input: 'Nouvelle session' } } })
  expect(responseNew.ok()).toBeTruthy()
  const next: Run = await responseNew.json()
  expect((await waitRun(request, next.id, 'completed')).messages.at(-1)?.text).toBe('Nouvelle version')
  await page.goto('/')
  await openSession(page, old.id)
  await expect(page.locator('.assistant-markdown')).toHaveText('Version initiale')
  await page.getByRole('button', { name: 'Conception', exact: true }).click()
  await page.getByRole('button', { name: 'Actions du flow Versions indépendantes', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Supprimer Versions indépendantes', exact: true }).click()
  await page.getByRole('dialog', { name: 'Supprimer le flow', exact: true }).getByRole('button', { name: 'Supprimer', exact: true }).click()
  await expect(page.locator(`[data-flow-key="${file.key}"]`)).toHaveCount(0)
  expect(await access(file.path).then(() => true, () => false)).toBe(false)
  await page.getByRole('button', { name: 'Exécution', exact: true }).click()
  await expect(page.locator('.assistant-markdown')).toHaveText('Version initiale')
  const saved = await (await request.get(`/api/runs/${old.id}`)).json()
  expect(saved.flowSource).toBe(original)
  expect(saved.flowRef.hash).toBe(file.hash)

  const flowWrites: string[] = []
  page.on('request', observed => {
    if (observed.method() === 'POST' && new URL(observed.url()).pathname.startsWith('/api/flows')) flowWrites.push(observed.url())
  })
  const frozen = page.waitForResponse(result => new URL(result.url()).pathname === `/api/runs/${old.id}/definition`)
  await inspector(page)
  await page.getByRole('button', { name: 'Rust initial du run', exact: true }).click()
  const frozenResponse = await frozen
  expect(new URL(frozenResponse.url()).searchParams.has('nodePath')).toBe(false)
  expect(new URL(frozenResponse.url()).searchParams.has('occurrenceId')).toBe(false)
  expect(frozenResponse.ok(), await frozenResponse.text()).toBeTruthy()
  const frozenDefinition = await frozenResponse.json()
  expect(frozenDefinition.source).toBe(original)
  expect(frozenDefinition.hash).toBe(file.sourceHash)
  expect(frozenDefinition.package.root).toBe(file.hash)
  expect(frozenDefinition.definitionRevision).not.toBe(file.hash)
  expect(frozenDefinition.definitionRevision).not.toBe(file.sourceHash)
  const sourceDialog = page.getByRole('dialog', { name: 'Rust initial du run', exact: true })
  await expect(sourceDialog.locator('.source-preview')).toContainText(original)
  await expect(sourceDialog.locator('.source-preview')).not.toContainText('Nouvelle version')
  const generated = page.waitForResponse(result => new URL(result.url()).pathname === '/api/generate' && result.request().method() === 'POST')
  const downloading = page.waitForEvent('download')
  await sourceDialog.getByRole('button', { name: 'Télécharger le projet Cargo', exact: true }).click()
  const generatedResponse = await generated
  expect(generatedResponse.request().postDataJSON()).toMatchObject({ runId: old.id, workspaceId: old.workspaceId,hash:frozenDefinition.definitionRevision ?? frozenDefinition.hash })
  expect(generatedResponse.request().postDataJSON()).not.toHaveProperty('occurrenceId')
  expect(generatedResponse.request().postDataJSON()).not.toHaveProperty('nodePath')
  expect(generatedResponse.ok()).toBeTruthy()
  const generatedFiles: { files: { path: string; content: string }[] } = await generatedResponse.json()
  const download = await downloading
  expect(download.suggestedFilename()).toBe(`zedflow-session-${old.id}.zip`)
  const archivePath = fixturePath(download.suggestedFilename())
  await download.saveAs(archivePath)
  const archive = unzipSync(await readFile(archivePath))
  expect(Object.keys(archive).sort()).toEqual(generatedFiles.files.map(file => file.path).sort())
  for (const file of generatedFiles.files) {
    expect(Buffer.from(archive[file.path]!).toString('utf8')).toBe(file.content)
    expect(file.content).not.toContain(fileURLToPath(new URL('../../', import.meta.url)))
  }
  expect(Buffer.from(archive['flows/instance-0/flow.rs']!).toString('utf8')).toBe(original)
  expect(Buffer.from(archive['Cargo.toml']!).toString('utf8')).toContain('[workspace]')
  expect(Buffer.from(archive['Cargo.toml']!).toString('utf8')).toContain('default-members = ["runner"]')
  expect(Buffer.from(archive['runner/Cargo.toml']!).toString('utf8')).toContain('[package]')
  expect(Buffer.from(archive['runner/src/main.rs']!).toString('utf8')).toContain('zf_execution::runtime_export::run')
  expect(Buffer.from(archive['Cargo.lock']!).toString('utf8')).toContain('name = "adk-graph"')
  expect(Buffer.from(archive['rust-toolchain.toml']!).toString('utf8')).toContain('1.96.1')
  expect(flowWrites).toEqual([])
  expect(await access(file.path).then(() => true, () => false)).toBe(false)
})
